### ISSUE TITLE
Quests and Magic!

### ISSUE THREAD

**Issue by McJoker123** [FlyingPikachu/Quests#400] opened 2018-05-12 18:48 UTC
I address once again and shortly! Your plugin does not read magic murder in the journal! Or counts crookedly! You need to work on this! When the monster dies from the effect of the potion, which uses the magic plugin!

**Comment by FlyingPikachu** [comment] 2018-05-13 01:13
Duplicate of #397 

It is difficult to understand you; please find a better translation service. The Magic plugin is not owned by me. The module to link Quests and Magic is not owned by me. You are asking the wrong person.

Ask here - https://github.com/elBukkit/MagicPlugin/issues

**Closed by FlyingPikachu** 2018-05-13 01:13 UTC
