### ISSUE TITLE
Levitation error and Custom Potion error??

### ISSUE THREAD

**Issue by topthat177** [FlyingPikachu/Quests#129] opened 2017-09-04 11:18 UTC
Version: 3.0.0-Naomi

Hello, i've been using quests for about a week now and Its a fantastic plugin with amazing capabilities however it appears to be extremely easy to break from one wrong command or action. I've encountered two problems 1) I was making an event to start a quest and was adding potion effects to a player and say LEVITATION on the list and selected it for 2min with level 1 assuming that it would enable players to fly temporarily. However this proceeded to break the event and Quests skipped that event and I had to make a new one (All console reports and events/quest yml in pastebin). 2) When I was making another quest I used a custom made potion spawned from a commandblock as an item for delivery to an NPC, and I set the quest to have a 20min fail timer, however whenever I start the quest, it comes up with QUEST FAILED instantly and I cannot give the potion to the second NPC. Is it the custom effects that are causing the problem? After this happens, I can no longer use the event editor which puts an error to the consol with /quests events and the plugin is completly broken. This has happened twice now and its a pain to start all over again. Any help would be hugely appreciated.

https://pastebin.com/Up2ESBjh

I hope we can save it without needing to completly restart again.

Thanks,
topthat177

**Comment by FlyingPikachu** [comment] 2017-09-04 18:49
Duplicate of #107

**Closed by FlyingPikachu** 2017-09-04 18:49 UTC
