### ISSUE TITLE
MythicMobs Module error

### ISSUE THREAD

**Issue by InfroDaz** [FlyingPikachu/Quests#280] opened 2018-02-07 20:47 UTC
(Required) What is your Quests version 3.2.4/ build 255 ?

(__Required__) I am not sure why but sometimes the console is getting filled with this:https://pastebin.com/es11j2TK

(__Optional__) This module installed: https://www.spigotmc.org/resources/mythicmobs-quests-module.7261/

**Comment by Vestle** [comment] 2018-02-07 22:26
https://pastebin.com/XifuhVeQ
Duplicate issue

**Comment by FlyingPikachu** [comment] 2018-02-07 23:21
Duplicate of #265

Use the latest dev build, released today.

**Closed by FlyingPikachu** 2018-02-07 23:21 UTC
