### ISSUE TITLE
Quests editor does not save quests.

### ISSUE THREAD

**Issue by ErenBlack** [FlyingPikachu/Quests#3] opened 2017-06-22 21:58 UTC
Just as the title says- i make a quest in the quests editor, save it, then exit. Then i did the command /quests list, and it was not in the list- so i tried /questsadmin reload, and it still did not have the quest in there.

I have tried making this quest twice.

**Comment by FlyingPikachu** [comment] 2017-06-23 01:59
Thank you, I will take this into account when investigating the issue. However, this a duplicate of #1 and for that reason, I must close it.

**Closed by FlyingPikachu** 2017-06-23 01:59 UTC

**Comment by FlyingPikachu** [comment] 2017-06-23 06:29
@ErenBlack Version 2.8.6 should resolve this issue. If you still experience issues, you may need to manually add block durability for affected quests. Post your quests.yml if you would like assistance. Thanks!
