### ISSUE TITLE
1.13 update? as theres issues

### ISSUE THREAD

**Issue by Castiella** [FlyingPikachu/Quests#493] opened 2018-10-19 16:28 UTC
VERSION: 3.3.4

(__Required__) Please describe the problem and how to replicate it. Any console errors?
When i try to set a crate key as an iitem reward and save/reload the quests it disappears from the item rewards, as if it was never configured.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/eZft035C

we are running 1.13 paper, so not sure if this is supported

**Comment by Castiella** [comment] 2018-10-19 16:36
UPDATE: OTHER items can be used,just not this crate key

**Comment by smmmadden** [comment] 2018-10-27 15:49
will there be an update for 1.13.2 - the latest that fixes many bugs introduced since 1.13 and 1.13.1 ?  I'm also using PaperSpigot and would love an update here. 👍

**Comment by FlyingPikachu** [comment] 2018-10-30 21:43
Duplicate of #468 

Try http://ci.ac3-servers.eu/job/Quests/489/

**Closed by FlyingPikachu** 2018-10-30 21:43 UTC

**Comment by smmmadden** [comment] 2018-10-31 02:38
thanks, will give that build a try.
