### ISSUE TITLE
No Kills Counting

### ISSUE THREAD

**Issue by alugilak** [FlyingPikachu/Quests#175] opened 2017-12-09 12:45 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.1.2-b192

(__Required__) Please describe the problem and how to replicate it. Any console errors?
no errors! kills are not counted. Not in the journal nor in the background!

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/TGtyhRQ3
You can see it here: https://youtu.be/ERVzHaDclB0

**Comment by FlyingPikachu** [comment] 2017-12-10 17:59
Duplicate of #143

**Closed by FlyingPikachu** 2017-12-10 17:59 UTC
