### ISSUE TITLE
Spamming Console

### ISSUE THREAD

**Issue by LoJoSho** [FlyingPikachu/Quests#606] opened 2018-12-31 22:23 UTC
**What is your Quests version / build number (do _not_ say "latest")?**

3.5.7

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

I am sorry, however, I have no clue how to replicate this. https://pastebin.com/L06nuZZJ 

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/unK5fWgi

**Comment by FlyingPikachu** [comment] 2018-12-31 22:32
Duplicate of #594

Use latest dev build.

**Closed by FlyingPikachu** 2018-12-31 22:32 UTC
