### ISSUE TITLE
API Issues / Denizen support

### ISSUE THREAD

**Issue by Fortifier42** [FlyingPikachu/Quests#281] opened 2016-02-13 00:54 UTC
Hi,

I'm using Quests as a depend of a plugin, to add the ability to retrieve information from Quests in Denizen. I was hoping you would be able to add this, otherwise I can add it and send in a PR.

However, it would be nice to see more informational methods of Quester.

**Comment by Fortifier42** [comment] 2016-02-13 02:26
Methods I'd like to see.
`Quester.getQuestPoints();`
`Quester.setQuestPoints(int);`

**Comment by FlyingPikachu** [comment] 2016-03-22 01:50
Duplicate of #87

**Closed by FlyingPikachu** 2016-03-22 01:50 UTC
