### ISSUE TITLE
spamming on console

### ISSUE THREAD

**Issue by newbie029** [FlyingPikachu/Quests#267] opened 2018-01-29 18:00 UTC
quests 3.2.3 b250

> [17:54:35 ERROR]: Could not pass event EntityDeathEvent to Quests v3.2.3-b250
java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensAPI
at me.blackvein.quests.PlayerListener.killMob(PlayerListener.java:495) ~[?:?]
at me.blackvein.quests.PlayerListener.onEntityDeath(PlayerListener.java:475) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor804.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1318]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1318]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1318]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1318]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1318]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:396) ~[patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1137) ~[patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:979) ~[patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) ~[patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1021) ~[patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1352) ~[patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1703) ~[patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1318]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1318]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
> [17:54:51 ERROR]: Could not pass event EntityDeathEvent to Quests v3.2.3-b250
java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensAPI
at me.blackvein.quests.PlayerListener.killMob(PlayerListener.java:495) ~[?:?]
at me.blackvein.quests.PlayerListener.onEntityDeath(PlayerListener.java:475) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor804.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1318]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1318]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1318]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1318]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1318]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:396) ~[patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1137) ~[patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:979) ~[patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) ~[patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1021) ~[patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1352) ~[patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1703) ~[patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1318]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1318]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1318]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by FlyingPikachu** [comment] 2018-01-29 19:06
Your  issue with your Citizens; not Quests.

**Comment by newbie029** [comment] 2018-02-06 09:38
i dont use citizens plugin

**Comment by FlyingPikachu** [comment] 2018-02-06 21:07
Ah, I see. That may be the cause. Will post a fix for this soon!

**Comment by FlyingPikachu** [comment] 2018-02-07 18:11
Fix will be available here:

http://ci.ac3-servers.eu/job/Quests/256/

Thanks for using Quests!

**Closed** 2018-02-07 18:11 UTC
Labels: bug
