### ISSUE TITLE
Quests not loading custom objective listener correctly

### ISSUE THREAD

**Issue by rubinusp** [FlyingPikachu/Quests#524] opened 2018-11-15 21:50 UTC
Custom Objectives were able to be shown in the quests editor. But listeners for the objectives were not able to trigger. 
Quests version: Quests-3.4.2
Spigot Version: spigot-1.12.2

https://pastebin.com/zG1MSQW3

**Comment by FlyingPikachu** [comment] 2018-11-16 04:17
I've moved your error to Pastebin. Please do this yourself in the future, or your issues may be closed for not following the directions.

It appears the plugin is trying to load a 1.13 particle even though your server is running 1.12. Are you maybe using PaperSpigot?

**Comment by FlyingPikachu** [comment] 2018-11-17 21:50
Possibly. Quests detected a 1.13 server, so it’s trying to load those particles, even though you’re on 1.12.

Are you using ViaVersion?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rubinusp** [comment] 2018-11-22 05:12
No we do not. We are using some plugins however. Would it be better for you if I give you the list?

**Comment by rubinusp** [comment] 2018-11-30 22:37
Hi I just want to follow up on the problem. I tried the newest Quest-3.4.3 build and the problem still remains. I would appreciate if you can fix the problem!

**Comment by FlyingPikachu** [comment] 2018-11-30 23:07
Duplicate of #516

http://ci.ac3-servers.eu/job/Quests/514/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2018-11-30 23:08 UTC
Labels: bug, duplicate
