### ISSUE TITLE
Could not pass event PlayerInteractEvent to Quests v3.5.7-b573

### ISSUE THREAD

**Issue by keodeovn** [FlyingPikachu/Quests#593] opened 2018-12-27 05:22 UTC
Version: v3.5.7-b573

I dont know how and why it appeared

log: https://pastebin.com/43KpR8JN
quests.yml: https://pastebin.com/uzLF1n0h

Thanks for reading!

**Comment by FlyingPikachu** [comment] 2018-12-27 06:14
Possible duplicate of #592 

Try http://ci.ac3-servers.eu/job/Quests/574/ and let me know if it resolves the issue.

**Comment by keodeovn** [comment] 2018-12-27 09:52
thanks so much

**Closed** 2018-12-28 19:07 UTC
