### ISSUE TITLE
Issue with consumables/weapons/potions

### ISSUE THREAD

**Issue by Ryan56k** [FlyingPikachu/Quests#450] opened 2018-08-07 01:41 UTC
(__Required__) 3.3.4

(__Required__)No console errors show up. I have a quest to deliver a "Water Bottle" to an NPC. When I try to deliver it says in game "Potion x1 is not a required item for this quest!" I have tried different ways of inputing it but it keeps defaulting to "Potion".

(__Optional__) https://pastebin.com/3XA3gig1

**Comment by FlyingPikachu** [comment] 2018-08-07 15:47
Duplicate of #107

**Closed by FlyingPikachu** 2018-08-07 15:47 UTC
