### ISSUE TITLE
Language file not working right

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#20] opened 2015-02-18 12:35 UTC
I use quests 2.2.0. I made a german language file called de.yml and i set the language to de in the config. this worked bevore but since i updated quests it does not work anymore. 
the only way to make it work is to delete the english file and rename the german to en.yml. and set it to en in the config.

**Comment by FlyingPikachu** [comment] 2015-02-18 17:22
Would you mind uploading your de.yml so I can test it?

**Comment by ScuroK** [comment] 2015-02-18 23:20
https://dl.dropboxusercontent.com/u/30946963/de.yml

**Comment by FlyingPikachu** [comment] 2015-02-19 18:27
Unable to reproduce. I used your config and set 'language: de' in config.yml. Works like a charm!

I have however changed the update system to update the current language file (so instead of always en.yml -> en_new.yml it'll be de.yml -> de_new.yml).

**Comment by FlyingPikachu** [comment] 2015-02-27 18:44
Closing as I could not reproduce the issue. If this persists, please open a new issue.

**Closed by FlyingPikachu** 2015-02-27 18:44 UTC
