### ISSUE TITLE
Can´t give item from hand to NPC

### ISSUE THREAD

**Issue by Marek2810** [FlyingPikachu/Quests#491] opened 2018-10-17 20:16 UTC
Hello.

Quest version: 3.3.8-b488
Vault version: v1.7.1-b91
Spigot version: git-Spigot-6b015b4-26c8927 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT) 

When I load item from hand (for example fishing rod) to quest and press "Done" console show me error message and I can´t use chat to do another command or quit editor.

Error message:

> [22:14:09 WARN]: [Quests] Plugin Quests v3.3.8-b488 generated an exception whilst handling conversation input 
> java.lang.NoClassDefFoundError: net/milkbowl/vault/item/Items 
> at me.blackvein.quests.util.ItemUtil.getName(ItemUtil.java:279) ~[?:?] 
> at me.blackvein.quests.util.ItemUtil.getDisplayString(ItemUtil.java:243) ~[?:?] 
> at me.blackvein.quests.prompts.CreateStagePrompt$DeliveryListPrompt.getPromptText(CreateStagePrompt.java:2031) ~[?:?] 
> at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:284) ~[server.jar:git-Spigot-6b015b4-26c8927] 
> at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) ~[server.jar:git-Spigot-6b015b4-26c8927] 
> at org.bukkit.craftbukkit.v1_13_R2.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:60) [server.jar:git-Spigot-6b015b4-26c8927] 
> at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1203) [server.jar:git-Spigot-6b015b4-26c8927] 
> at net.minecraft.server.v1_13_R2.PlayerConnection$2.evaluate(PlayerConnection.java:1493) [server.jar:git-Spigot-6b015b4-26c8927] 
> at org.bukkit.craftbukkit.v1_13_R2.util.Waitable.run(Waitable.java:24) [server.jar:git-Spigot-6b015b4-26c8927] 
> at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:913) [server.jar:git-Spigot-6b015b4-26c8927] 
> at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-6b015b4-26c8927] 
> at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [server.jar:git-Spigot-6b015b4-26c8927] 
> at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [server.jar:git-Spigot-6b015b4-26c8927] 
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by FlyingPikachu** [comment] 2018-11-12 02:43
Duplicate of #468 

Use latest release of Quests

**Closed by FlyingPikachu** 2018-11-12 02:43 UTC
