### ISSUE TITLE
Quests-3.4.2.jar / At the launch without any configuration in spigot version 1.13.2 / "Material cannot be null"

### ISSUE THREAD

**Issue by MalowZer** [FlyingPikachu/Quests#533] opened 2018-11-24 21:33 UTC
[21:26:41] [Server thread/WARN]: [Quests] Task #1704 for Quests v3.4.2-b500 generated an exception
java.lang.IllegalArgumentException: Material cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot.jar:git-Spigot-9b4b0a2-f489f0f]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:69) ~[spigot.jar:git-Spigot-9b4b0a2-f489f0f]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:57) ~[spigot.jar:git-Spigot-9b4b0a2-f489f0f]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:45) ~[spigot.jar:git-Spigot-9b4b0a2-f489f0f]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:35) ~[spigot.jar:git-Spigot-9b4b0a2-f489f0f]
	at me.blackvein.quests.util.ItemUtil.readItemStack(ItemUtil.java:112) ~[?:?]
	at me.blackvein.quests.Quests.loadQuestRequirements(Quests.java:2338) ~[?:?]
	at me.blackvein.quests.Quests.loadQuests(Quests.java:2176) ~[?:?]
	at me.blackvein.quests.Quests$1.run(Quests.java:296) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-9b4b0a2-f489f0f]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-9b4b0a2-f489f0f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot.jar:git-Spigot-9b4b0a2-f489f0f]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-9b4b0a2-f489f0f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-9b4b0a2-f489f0f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-9b4b0a2-f489f0f]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by FlyingPikachu** [comment] 2018-11-25 02:57
Duplicate of #532

**Closed by FlyingPikachu** 2018-11-25 02:57 UTC
