### ISSUE TITLE
Color bug and \n sugg

### ISSUE THREAD

**Issue by SwimUp29** [FlyingPikachu/Quests#273] opened 2018-01-31 12:39 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.2 

Color codes do not apply to all text, if viewed through the NPC

![image](https://user-images.githubusercontent.com/35236355/35623428-09058978-06a5-11e8-8467-331ee8947d52.png)

https://pastebin.com/YLedH8KA

And can you add \n - character to force a line break?

**Comment by FlyingPikachu** [comment] 2018-02-01 03:17
Not currently possible at use "\n"; duplicate of #135

Colors do work, but you must specify them in time for each new line. For more details on what I mean (and an alternative method using ChestCommands), see #193

**Closed by FlyingPikachu** 2018-02-01 03:17 UTC
