### ISSUE TITLE
Compatibility with LuckPerms plugin

### ISSUE THREAD

**Issue by MrCreeperSteve** [FlyingPikachu/Quests#442] opened 2018-07-25 17:56 UTC
What is your Quests version / build number (do _not_ say "latest")?
Quests 3.3.4
Please describe the problem and how to replicate it. Any console errors?
When I tried to use Quests with LuckPerms permission plugin installed, plugin says that I have no permission to use Quests plugin commands. I have MySQL connected to LuckPerms(maybe it can change something).

**Comment by FlyingPikachu** [comment] 2018-07-30 20:12
Duplicate of #440

**Closed by FlyingPikachu** 2018-07-30 20:12 UTC
