### ISSUE TITLE
BlockPlaceEvent

### ISSUE THREAD

**Issue by SwimUp29** [FlyingPikachu/Quests#241] opened 2018-01-12 13:53 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.1 b234
(__Required__) Please describe the problem and how to replicate it. Any console errors?
[11:00:55] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to Quests v3.2.1-b234
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:150) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:207) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:505) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException

**Comment by FlyingPikachu** [comment] 2018-01-16 08:19
The error you've posted is missing the crucial part, which is the lines **after**
`Caused by: java.lang.NullPointerException`
Seeing as there's also a good possibility of this being related to #240, I've decided to close this issue.

**Closed by FlyingPikachu** 2018-01-16 08:19 UTC
