### ISSUE TITLE
Repeating error.  Not sure what it is.

### ISSUE THREAD

**Issue by Tristag** [FlyingPikachu/Quests#192] opened 2015-08-07 08:58 UTC
http://pastebin.com/0ds7vfyS

This is spammed in the console, I can't seem to find a source.

Awesome plugin nonetheless, have made some amazing quests so far!

**Comment by FlyingPikachu** [comment] 2015-08-08 03:35
Duplicate of #188

**Closed by FlyingPikachu** 2015-08-08 03:35 UTC
