### ISSUE TITLE
Deliver item potion

### ISSUE THREAD

**Issue by RaulCto** [FlyingPikachu/Quests#140] opened 2017-09-27 20:47 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?

Quests-3.0.0-Naomi

(__Required__) Please describe the problem and how to replicate it. Any console errors?

No error in console and the plugin is working all fine. I create this quest and can't deliver the potion. Even i want that the potion i have in my hand, that is fire resistant, can't register. Any potion i try it keeps allways register as: Potion x 1 And even when i accept the quest and try to deliver that same potion it says: Potion x 1 is not what you have to deliver.
<SS> https://imgur.com/a/ot60q

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
custom1:
    name: test
    npc-giver-id: 5
    ask-message: Hi
    finish-message: Bye
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-POTION:amount-1
          npc-delivery-ids:
          - 5
          delivery-messages:
          - Thx

**Comment by FlyingPikachu** [comment] 2017-10-01 03:06
Duplicate of #107

**Closed by FlyingPikachu** 2017-10-01 03:06 UTC
