### ISSUE TITLE
Quests aren't working

### ISSUE THREAD

**Issue by Alppuccino** [FlyingPikachu/Quests#74] opened 2017-07-25 10:10 UTC
In your issue, please include:

- Spigot and Quests versions (do not say "latest")
git-Spigot-7228328-14b597f (MC 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
Quests 2.9.5
- Description of problem & console errors
Quest editor just isn't processing any messages in chat since new update, quests are duplicating on reload and oak logs aren't being counted.
- Pastebin an example quest from quests.yml for testing, if applicable
https://pastebin.com/kbHgTzhn

**Comment by FlyingPikachu** [comment] 2017-07-26 02:01
Duplicate of #73

**Closed by FlyingPikachu** 2017-07-26 02:01 UTC
