### ISSUE TITLE
Plugin not working on last version (Quests v3.6.0-b611)

### ISSUE THREAD

**Issue by tiradorus** [FlyingPikachu/Quests#644] opened 2019-01-17 17:31 UTC
**What is your Quests version / build number (do _not_ say "latest")?**

Quests v3.6.0-b611 (the last updated)

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

Plugin isn't working at all ^^'

18:25:36: [Quests] Task #108 for Quests v3.6.0-b611 generated an exception
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.LinkedList
at me.blackvein.quests.Quests.loadQuestRewards(Quests.java:926) ~[?:?]
at me.blackvein.quests.Quests.loadQuests(Quests.java:865) ~[?:?]
at me.blackvein.quests.Quests$1.run(Quests.java:433) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

+

18:28:14: tiradorus issued server command: /questadmin reload
18:28:14: null
org.bukkit.command.CommandException: Unhandled exception executing command 'questadmin' in plugin Quests v3.6.0-b611
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.LinkedList
at me.blackvein.quests.Quests.loadQuestRewards(Quests.java:926) ~[?:?]
at me.blackvein.quests.Quests.loadQuests(Quests.java:865) ~[?:?]
at me.blackvein.quests.Quests.reloadQuests(Quests.java:696) ~[?:?]
at me.blackvein.quests.listeners.CmdExecutor.adminReload(CmdExecutor.java:838) ~[?:?]
at me.blackvein.quests.listeners.CmdExecutor.questAdminCommandHandler(CmdExecutor.java:261) ~[?:?]
at me.blackvein.quests.listeners.CmdExecutor.onCommand(CmdExecutor.java:72) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
... 15 more

That's all, i'll repass on a more stable version ;)

**Comment by FlyingPikachu** [comment] 2019-01-17 19:02
Thanks for the report. Please give this build a try, once available (I've undone the previous changes and tried something else):
http://ci.ac3-servers.eu/job/Quests/613/

@Borc55 may be interested in trying it as well.

**Comment by tiradorus** [comment] 2019-01-17 20:21
Now plugin reworks, but it's the extension that doesn't work xD

21:15:34: [Quests] Loaded Module: Class Level Requirement by Eniripsa96
21:15:34: [Quests] Loaded Module: Class Requirement by Eniripsa96
21:15:34: [Quests] Loaded Module: Class Reward by Eniripsa96
21:15:34: [Quests] Loaded Module: Class Skill Points Reward by Eniripsa96
21:15:34: [Quests] Loaded Module: Class Level Requirement by Eniripsa96
21:15:34: [Quests] Loaded Module: MythicMobs Item Reward by BerndiVader
21:15:34: [Quests] Loaded Module: MythicMobs Item Require by BerndiVader, idea Wahrheit
21:15:34: [Quests] Unable to load module from file: MythicMobsQuests.jar
21:15:34: java.lang.reflect.InvocationTargetException
21:15:34: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
21:15:34: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
21:15:34: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
21:15:34: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
21:15:34: at me.blackvein.quests.Quests.loadModule(Quests.java:547)
21:15:34: at me.blackvein.quests.Quests.loadModules(Quests.java:466)
21:15:34: at me.blackvein.quests.Quests$1.run(Quests.java:439)
21:15:34: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
21:15:34: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
21:15:34: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
21:15:34: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
21:15:34: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
21:15:34: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
21:15:34: at java.lang.Thread.run(Thread.java:748)
21:15:34: Caused by: java.lang.NoSuchFieldError: datamap
21:15:34: at com.gmail.berndivader.mythicmobsquests.MythicItemDeliverObjective.addDataAndDefault(MythicItemDeliverObjective.java:123)
21:15:34: at com.gmail.berndivader.mythicmobsquests.MythicItemDeliverObjective.<init>(MythicItemDeliverObjective.java:31)
21:15:34: ... 14 more
21:15:34: [Quests] Custom objective "Kill MythicMobs Objective" for Stage 1 of Quest "La grande infection" could not be found!
21:15:34: [Quests] Custom objective "Kill MythicMobs Objective" for Stage 1 of Quest "Les chevaliers corrompus" could not be found!
21:15:34: [Quests] Custom objective "Kill MythicMobs Objective" for Stage 1 of Quest "Les zombifiacs distordus" could not be found!
21:15:34: [Quests] Custom objective "Kill MythicMobs Objective" for Stage 1 of Quest "Dehors les envahisseurs!" could not be found!
21:15:34: [Quests] Custom objective "Kill MythicMobs Objective" for Stage 1 of Quest "Une terreur desertique" could not be found!
...

QuestsBuild #614

**Comment by FlyingPikachu** [comment] 2019-01-17 20:29
That’s to be expected with the recent refactor. I’ll submit a pull request for @BerndiVader ‘s module closer to the release of Quests 3.6.0.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BerndiVader** [comment] 2019-01-17 20:55
Fixed with https://github.com/BerndiVader/MythicMobsQuestsModule/commit/4a3c951e59fd0ed1abbe76fae6e212cb189e5af9

**Comment by trungbmt** [comment] 2019-01-19 06:49
The save quest error I encountered in #641 has not been fixed at b617

I first created a quest with the reward of a command: lp user <player> permission set quests.5 sdo
I saved it, there was no error.
then I use /quests editor and select that quests, then I enter 13 (Save) and enter 1 (Yes), nothing happens. Check that the Console appears an error: https://hastebin.com/jodociyoxu.md
Sorry for my english

**Comment by FlyingPikachu** [comment] 2019-01-19 06:55
@trungbmt seems like I confused your username with tiradorus, thinking you made a duplicate issue. My mistake!

I’ll try to replicate the problem with your steps soon.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FlyingPikachu** [comment] 2019-01-25 00:51
Should be resolved with most recent dev build and the updated MythicMobsQuestsModule, available here:
https://github.com/BerndiVader/MythicMobsQuestsModule/blob/8a27d96d62cd1b1fc223a007fe30b0a8c532a1e1/MythicMobsQuests.jar

@trungbmt Your hastebin has expired. I will re-open #641 for now. Thanks for your patience.

**Closed by FlyingPikachu** 2019-01-25 00:51 UTC
Labels: bug

**Comment by FlyingPikachu** [comment] 2019-01-31 04:17
Commit c8efb7d was intended for ticket 664. Please disregard that information.
