### ISSUE TITLE
Warn on load

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#108] opened 2017-08-18 15:02 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.0.1-b174
(__Required__) Please describe the problem and how to replicate it. Any console errors?
```
[10:58:53] [Server thread/INFO]: [Quests] Enabling Quests v3.0.1-b174
[10:58:53] [Server thread/WARN]: [Quests] Could not save quests.yml to plugins/Quests/quests.yml because quests.yml already exists.
[10:58:53] [Server thread/WARN]: [Quests] Could not save events.yml to plugins/Quests/events.yml because events.yml already exists.
[10:58:53] [Server thread/WARN]: [Quests] Could not save data.yml to plugins/Quests/data.yml because data.yml already exists.
```
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
N/A

**Comment by FlyingPikachu** [comment] 2017-08-18 16:53
Duplicate of #105

**Closed by FlyingPikachu** 2017-08-18 16:53 UTC
