### ISSUE TITLE
Bug When completing a part of a stage (say break 64 blocks) it displays a completed message saying 0/0 instead of 64/64.

### ISSUE THREAD

**Issue by OwnAgePau** [FlyingPikachu/Quests#40] opened 2017-07-12 19:50 UTC
Spigot 1.11.2
Quests 2.8.4 (build 130)

The problem is that the completed message given to the player after he complets a break block section of a stage of a quest it does not say the correct amounts but 0/0 instead.
Screenshot of the completed message: https://gyazo.com/6b7762c64414a9e398087801524f3321
Screenshot of the quest journal: https://gyazo.com/7a35e91f4c6e32a1b460f72b82ef3b3e

quets.yml content

  custom3:
    name: Bucket List
    npc-giver-id: 16
    ask-message: Do you want to help me? I have got some gold if you are interested!
    finish-message: Thanks a lot, you helped me a great deal. Here be thy gold!
    gui-display: name-BUCKET:amount-1
    requirements:
      items:
      - name-BUCKET:amount-1
      remove-items:
      - true
      fail-requirement-message: You don't have a bucket? Who are you!!
    stages:
      ordered:
        '1':
          break-block-names:
          - IRON_ORE
          break-block-amounts:
          - 64
          break-block-durability:
          - 0
          items-to-deliver:
          - name-IRON_ORE:amount-64
          npc-delivery-ids:
          - 16
          delivery-messages:
          - Thanks!
          start-message: I ran out of Iron Ore, can you get me some?
          complete-message: Thanks! I can finally start making some more swords, the guards will be please (I hope).
    rewards:
      money: 10

**Comment by FlyingPikachu** [comment] 2017-07-12 20:51
Is this only in the amount of 64? Does 65 work?

**Comment by OwnAgePau** [comment] 2017-07-13 18:14
Additional bug. I'll post an extra bug report. But I can't edit the block break settings of a stage.

**Comment by FlyingPikachu** [comment] 2017-07-14 03:47
That additional bug you've described was fixed in version 2.8.6

As for the OP bug, this is due to how Quests trying to get those numbers from an ItemStack, which maxes out at 64 (think of how you can only hold 64 blocks of dirt per slot).

Will try to think of the best way to handle this. For future reference, the problem is here - https://github.com/FlyingPikachu/Quests/blob/master/src/main/java/me/blackvein/quests/Quester.java#L1071

**Comment by OwnAgePau** [comment] 2017-07-15 14:04
Additional bug that sort of is the same, when having 10 eggs needing to be delivered it says in the Log message "Deliver: Egg" without an amount not sure if this is a bug or not. The journal then goes on displayed the right amount.

**Comment by FlyingPikachu** [comment] 2017-07-15 21:41
Will be fixed in version 2.6.1, thanks!

**Closed** 2017-07-15 21:41 UTC
Labels: bug
