### ISSUE TITLE
Players can re-log to bypass Quest Timer.

### ISSUE THREAD

**Issue by ravingraybits34** [FlyingPikachu/Quests#219] opened 2015-10-25 21:35 UTC
Title.
That's about it.
Running Quests 2.0. If you need any config files or whatnot lemme know. Everything seems to be in check.

**Comment by Belegalgar** [comment] 2015-10-26 15:58
sounds's like my issue: https://github.com/FlyingPikachu/Quests/issues/215

**Comment by FlyingPikachu** [comment] 2015-11-21 02:33
Duplicate of #67

**Closed by FlyingPikachu** 2015-11-21 02:33 UTC
