### ISSUE TITLE
Null error

### ISSUE THREAD

**Issue by Klyser8** [FlyingPikachu/Quests#258] opened 2018-01-26 16:16 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests-3.2.2.jar

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Whenever I tried inputting a command, it just says "NULL" when I press enter.
Also, the lang folder disappeared in my quests folder. Tried using older versions, or deleting the entire quests folder, but the folder never appears.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by FlyingPikachu** [comment] 2018-01-26 21:52
Likely duplicate of #256

What operating system (Windows/Mac/Linux) are you hosting your server on?

**Comment by FlyingPikachu** [comment] 2018-01-27 04:02
The following dev build should resolve this issue. Thanks for using Quests!

http://ci.ac3-servers.eu/job/Quests/249/

**Closed by FlyingPikachu** 2018-01-27 04:02 UTC
Labels: bug, duplicate
