### ISSUE TITLE
use blocks buggy

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#157] opened 2017-10-26 21:43 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
NAOMI
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Use blocks does not work correctly. on some blocks it doesnt work at all (for example skulls) and for some blocks it fires the use event to often. instead of clicking it 3 times i just need to click it once to fullfill "use 3 times" wuest

**Comment by FlyingPikachu** [comment] 2017-12-06 03:00
Not sure I understand the issue. Would you mind providing more info and an example from quests.yml?

**Comment by ScuroK** [comment] 2017-12-06 19:14
i dont have a .yml for it but i can tell you it was just a simple test setup like:

Stage 1: Use a certain block one times
Done

im sure you can find it

**Comment by FlyingPikachu** [comment] 2018-01-04 07:06
Confirmed that using a Stone Button during a quest that required it did not work. Possibly related to #146

**Comment by FlyingPikachu** [comment] 2018-01-09 05:51
Confirmed to be a duplicate of #146 

The durability for the Stone Button varies depending on facing and state (on/off). You most likely left the durability at its default value of 0, so they didn't match. Will be looking into a way around this.

**Closed by FlyingPikachu** 2018-01-09 05:51 UTC
Labels: bug
