### ISSUE TITLE
Duplicate objective still

### ISSUE THREAD

**Issue by SwimUp29** [FlyingPikachu/Quests#244] opened 2018-01-14 13:44 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.1
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Objectives still duplicate
https://pastebin.com/KGEqARHJ

if re-connected then the task of "break block" is duplicated

**Comment by PengBread** [comment] 2018-01-15 16:47
I'm having the same issue too. As stated above.

**Comment by FlyingPikachu** [comment] 2018-01-16 08:21
Should be fixed in 01cad69706e6969c0da71e3d16d8abb5f0c7c664

Counting as duplicate of #242

**Closed by FlyingPikachu** 2018-01-16 08:21 UTC
