### ISSUE TITLE
java.lang.NoClassDefFoundError 1.13.1

### ISSUE THREAD

**Issue by Straiker123** [FlyingPikachu/Quests#528] opened 2018-11-18 13:43 UTC
build 503 , server verison: 1.13.1

repeated error to console, npc effect does not work:

`[Quests] Task #132759 for Quests v3.4.2-b503 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_13_R1/entity/CraftPlayer
	at me.blackvein.particles.Eff_1_13_R1.sendToPlayer(Eff_1_13_R1.java:119) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.showEffect_1_13_R1(NpcEffectThread.java:224) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:70) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:54) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]`

please fix thanks.

**Comment by FlyingPikachu** [comment] 2018-11-20 03:31
Appears to be duplicate of #522

**Comment by FlyingPikachu** [comment] 2018-11-28 22:35
This build should resolve the issue once available - http://ci.ac3-servers.eu/job/Quests/510/

**Closed by FlyingPikachu** 2018-11-28 22:35 UTC
Labels: bug, duplicate

**Comment by Straiker123** [comment] 2018-11-29 22:20
not working.. i have same error

**Comment by FlyingPikachu** [comment] 2018-11-29 22:21
@Straiker123 Post the new error then, please (it will be slightly different).
