### ISSUE TITLE
currentStage was null

### ISSUE THREAD

**Issue by keodeovn** [FlyingPikachu/Quests#582] opened 2018-12-21 10:19 UTC
Hello Pikachu. Quests is an amazing plugin. I like it very much 😄
I saw all of issues about this problem and I knew that problem will appear when player chat with currentStage is null?
This issue happened on my server. Maybe it doesn't a big problem. Nothing went wrong went it appeared. But there were a lot of this line in my console and it made crazy.
Here an example of the issues:
- currentStage was null for 0479ec58-62fa-34c1-a2a3-84661cb41022 on chat
- 0479ec58-62fa-34c1-a2a3-84661cb41022.yml: https://pastebin.com/QZR46SiF

Thanks for reading!

**Comment by FlyingPikachu** [comment] 2018-12-22 00:17
Thanks for the report! However, without any symptoms to go off of, there's not much that can be done. Closing as duplicate of #463 and/or #501. If something stops working or behaves irregularly, feel free to include that information below.

**Closed by FlyingPikachu** 2018-12-22 00:17 UTC
