### ISSUE TITLE
ItemUtil.compareItems showing different data for the same items

### ISSUE THREAD

**Issue by frost-byte** [FlyingPikachu/Quests#557] opened 2018-12-04 22:57 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.4.6
 
(__Required__) Please describe the problem and how to replicate it. Any console errors?

Create an Item for an Event using while holding one cocoa bean, give it a display name of Kitty Litter
Create a Quest with a Stage where you need to deliver this same item to an npc.
Add a breakpoint for the onNPCRightClick function in the NPCListener class, and step into ItemUtil.compareItems.
The items show that they have the same meta data, but their data is different, one shows Black Dye(0) the other shows LEGACY_INK_SAC(3).  I'm not sure that getData is even supposed to be used any more with the changes to materials. (It doesn't appear to be deprecated)

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

here is the quest in quests.yml
https://pastebin.com/00cYkbgw
Here is the event
https://pastebin.com/8Frk0RHx

**Comment by frost-byte** [comment] 2018-12-05 03:04
This is the first time I've used Quests, starting with 1.13.
I used the commands within Minecraft itself to define the item for both the event and the Quest/Stage.
So I'm not sure what you mean when you mention updating the names.

I just tested your fix and it still does not work.

Perhaps you can do something similar to other plugins I've come across, regarding handling functions differently, based upon which version of Minecraft is being used.

You can throw something like this into one of your utility classes:
```Java
	public static final boolean v1_8, v1_9, v1_10, v1_11, v1_12, v1_13;

	static {
		String vers = Bukkit.getBukkitVersion(); // Returns in format like: 1.12.2-R0.1-SNAPSHOT
		v1_13 = vers.startsWith("1.13");
		v1_12 = vers.startsWith("1.12") || v1_13;
		v1_11 = vers.startsWith("1.11") || v1_12;
		v1_10 = vers.startsWith("1.10") || v1_11;
		v1_9 = vers.startsWith("1.9") || v1_10;
		v1_8 = vers.startsWith("1.8") || v1_9;
	}
```

Then, in your ItemUtil class you would reference the versions from the above:
```Java
	public static int compareItems(ItemStack one, ItemStack two, boolean ignoreAmount) {
		if (one == null || two == null) {
			return 0;
		}
		if (one.getType().name().equals(two.getType().name()) == false) {
			return -1;
		} else if ((one.getAmount() != two.getAmount()) && ignoreAmount == false) {
			return -2;
		} else if (!v_13 && one.getData().equals(two.getData()) == false) {
			return -3;
		}
		if (one.hasItemMeta() || two.hasItemMeta()) {
			if (one.hasItemMeta() && two.hasItemMeta() == false) {
				return -4;
			} else if (one.hasItemMeta() == false && two.hasItemMeta()) {
				return -4;
			} else if (one.getItemMeta().hasDisplayName() && two.getItemMeta().hasDisplayName() == false) {
				return -4;
			} else if (one.getItemMeta().hasDisplayName() == false && two.getItemMeta().hasDisplayName()) {
				return -4;
			} else if (one.getItemMeta().hasLore() && two.getItemMeta().hasLore() == false) {
				return -4;
			} else if (one.getItemMeta().hasLore() == false && two.getItemMeta().hasLore()) {
				return -4;
			} else if (one.getItemMeta().hasDisplayName() && two.getItemMeta().hasDisplayName() && ChatColor.stripColor(one.getItemMeta().getDisplayName()).equals(ChatColor.stripColor(two.getItemMeta().getDisplayName())) == false) {
				return -4;
			} else if (one.getItemMeta().hasLore() && two.getItemMeta().hasLore() && one.getItemMeta().getLore().equals(two.getItemMeta().getLore()) == false) {
				return -4;
			}
		}
		if (one.getEnchantments().equals(two.getEnchantments()) == false) {
			return -5;
		}
		if (one.getType().equals(Material.ENCHANTED_BOOK)) {
			EnchantmentStorageMeta esmeta1 = (EnchantmentStorageMeta) one.getItemMeta();
			EnchantmentStorageMeta esmeta2 = (EnchantmentStorageMeta) two.getItemMeta();
			if (esmeta1.hasStoredEnchants() && esmeta2.hasStoredEnchants() == false) {
				return -6;
			}
			if (esmeta1.getStoredEnchants().equals(esmeta2.getStoredEnchants()) == false) {
				return -6;
			}
		}
		return 0;
	}
```

**Comment by frost-byte** [comment] 2018-12-05 03:46
I just implemented the above change locally and this fixes my issues with acquiring the quest through the gui and completing the delivery of the item.
This still leads to an issue with the reward. One other issue I've noticed, your representation of item meta data does not allow for specifying ItemFlags. (If I want to hide enchants on custom items, for example)
I can open that as a separate issue.

**Comment by FlyingPikachu** [comment] 2018-12-05 17:01
I see. Often times players upgrading from pre-1.13 files experience these issues, since many of the Material names have changed. Anyway, sorry to hear the patch didn't work. The recent death of VaultAPI is proving a challenge to work around.

There are a couple of concerns I have with the fix you've suggested. Firstly, there is no future proofing; it is my goal to minimize the amount of work that needs to be done for each protocol change. As it stands, only the NPC particle code must be updated per MC release and I'd prefer to keep it that way.

Secondly, the issue at hand indicates a deeper underlying problem, because even though getData() is unnecessary for 1.13+ materials, it should still return the same value for both items. Something along the way is producing different values for the same item (as well as the item name itself).

ItemFlag support would be a welcome addition. I see you've submitted #558 and will look at that shortly.

**Comment by frost-byte** [comment] 2018-12-05 18:13
Well, I’m sure you’re aware that Spigot had a major overhaul to item names in 1.13 to match the material names used by mojang.  Not to mention the removal of data, because all items and blocks have their own material now.

I was under the impression that the behavior of getData in 1.13 was described as volatile or undefined.  Between creating different implementations or checking the version directly I don’t see how you can avoid the issue.  I did not see anything in your serialization that would allow me to specify what to assign to the data value.

Perhaps you could add a config flag that would indicate whether or not the data should be compared or used?

**Comment by FlyingPikachu** [comment] 2018-12-05 19:18
That's correct, and while the correct fix is to either manually update item names in the files or remake the quest through the editor, the temporary fix from the Spigot team is to prepend "LEGACY_" to any given item name that you wish to indicate is from the 1.12 naming scheme. However, I've been slow on taking advantage of this, hence e363cd4

LEGACY_ materials are deprecated in the same sense that getData is. It's simply a temporary way to maintain compatibility with older MC protocol and will undoubtedly be removed one day. When that day comes, Quests (and many other plugins) will have no choice but to cease supporting older protocol.

The things with getData is, it should return '0' on all 1.13 items, but you said that one cocoa bean is showing up as "LEGACY_INK_SAC(3)" which indicates that getData returned '3' instead. And since you say you have only started using Quests with 1.13 (so there's no way you made any of your quests pre-1.13), that tells me there is something deeply wrong with how Quests is processing your data.

Disabling material comparison would not be advisable. Let's say you want someone to deliver a enchanted Bow with lore to an NPC. If comparing items were disabled, nothing would stop the player from delivering a plain ol' Bow to complete the quest. The opposite is also true - a player might accidentally deliver a "rare" bow to an NPC that only needs a regular one.

On that note, I'll be pushing a commit shortly which address the ItemFlag thing. If you'd like to discuss that post-commit, please open a new issue about ItemFlags.

**Comment by frost-byte** [comment] 2018-12-06 06:57
Right, I was simply referring to the data portion.

**Comment by FlyingPikachu** [comment] 2018-12-09 05:06
Likely duplicate of #402

I've come to realize the issue. The getData method at your breakpoint is indeed the problem. However, the values aren't wrong... that line of code should actually be using _getDurability_. Perhaps my brain is stuck back in Indev, when item IDs were commonplace and durability was commonly known as the _data_ value, which caused me to mistake one method for the other.

Interestingly, the old Blackvein repo (from which this one was forked), has the getData method present, so it wasn't me whom introduced this bug. I'm unsure if maybe the Bukkit or Spigot team reused naming, or if this just wasn't an issue before, but regardless the method now refers to MaterialData which is not something we need to be checking (but hence why getData isn't deprecated).

The following commit and dev build will resolve the issue. Thanks for your patience!

**Closed** 2018-12-09 05:06 UTC
Labels: bug

**Comment by FlyingPikachu** [comment] 2018-12-09 05:08
http://ci.ac3-servers.eu/job/Quests/543/
