### ISSUE TITLE
Stage 2 / Delivery quests bug

### ISSUE THREAD

**Issue by Geedy** [FlyingPikachu/Quests#16] opened 2017-06-27 04:00 UTC
- Hello, i've been getting this problem, when i completed stage 1 everything seemed fine but when i started stage 2 which is delivery quest, i gave the npc the item needed to complete stage 2 then my chatlog said it "completed" just like stage 1 but it didn't continue to give me my rewards or continue to stage 3, it just notthing happen, the stage is completed but no rewards or continue to next stage.
- Image: http://imgur.com/a/D8DKX
- Im using Quests plugin 2.8.6 and Spigot 1.11.2, the console seemed fine, no errors appear. Please help me :( (sorry for bad english )

**Comment by QueenKisaki** [comment] 2017-06-27 18:22
Just found that bug too, even tried remaking the entire quest twice. It says completed in chat but no rewards and still in journal as well as not done in stats: 
![2017-06-27_13 21 08](https://user-images.githubusercontent.com/22261674/27603380-8e55664a-5b3b-11e7-991a-5464f46ad555.png)

**Comment by Enzo41814** [comment] 2017-06-28 04:17
I have a temporary solution:
- Create a mission with only 1 stage.
- When completing that mission, place as command "Questadmin give <player> [Quest]" as rewards.
- The next quest must also have only 1 stage.

**Comment by Geedy** [comment] 2017-06-28 10:57
Okay @Enzo41814 way looks good, ill try it out
*Still waiting for the fix of this bug lol...*

**Comment by FlyingPikachu** [comment] 2017-07-02 19:17
Could someone (ideally @Geedy) provide a quests.yml or pastebin of an example quest? I have not been able to replicate this using [this configuration](https://pastebin.com/cCxFrzuW); everything worked fine.

**Comment by QueenKisaki** [comment] 2017-07-02 19:45
https://pastebin.com/x1mxgqQ6 example quest. full quest.yml https://pastebin.com/8xx4Ycg2

**Comment by FlyingPikachu** [comment] 2017-07-04 00:04
@QueenKisaki I was able to complete a[ modified version of your quest](https://pastebin.com/xU41iHU6) without issue. Note that I replaced the MythicMob-related portions as I do not use that in my test environment.

It is my current suspicion that the MythicMobs compatibility module (not maintained by me) may be responsible. I will attempt to test this, but config from @Geedy would be appreciated.

**Comment by FlyingPikachu** [comment] 2017-07-04 00:34
@QueenKisaki Could you provide your MythicMob config for the "Fairy"?

**Comment by QueenKisaki** [comment] 2017-07-04 00:42
https://pastebin.com/hyhei7Ly is the mob file for fairy. It happens on other quests too, not just mm objectives. It happened on an npc we were just supposed to talk to (Druid Trainer) quest and I had to remove and redo the npc, haven't checked if it worked or not. It happens also on the marvin quest to turn in the fruit alot as well. It's mainly just completing quests is the issue. It counts all the kills for mm kill so thats fine, it takes the correct items used to turn in. It just has an issue with saying you've completed the actual quest even though it says you did.

**Comment by FlyingPikachu** [comment] 2017-07-04 16:51
@QueenKisaki The Fairies spawn but killing 3 doesn't complete stage 1 and my knowledge of MythicMobs is very limited, so it's likely I've done something wrong.

Do you have any non-MythicMobs quests that are currently affected by this bug?

**Comment by QueenKisaki** [comment] 2017-07-04 18:22
The fairies drop a fruit item (Natural Fruit) to turn in, that should complete the quest. Here is a non kill objective quest that does it: https://pastebin.com/ZVieTQKA
As you can see, its a simple talkto the druid trainer. I even tried adding the finish command to it but it wont work because the quest needs to complete before running the command lol.

**Comment by FlyingPikachu** [comment] 2017-07-04 18:25
@QueenKisaki They do not drop any fruit items. Perhaps I am missing part of the configuration?

It looks like your non-kill quest has only 1 stage (the issue at hand occurs at stage 2?) but I'll try it anyway.

**Comment by QueenKisaki** [comment] 2017-07-04 18:36
It's a phatloot that drops. But yes even the 1 stage simple quest to meet the npc does not complete. His second stage https://pastebin.com/x0AxcYxd will not complete either. It seems quite random whether a quest will actually be completed when you're done. Item turn ins or simple talk tos, but no errors in console.

**Comment by QueenKisaki** [comment] 2017-07-04 18:39
Just found this error https://pastebin.com/0AhXkhMu

**Comment by FlyingPikachu** [comment] 2017-07-05 04:57
@QueenKisaki I created a PhatLoot containing an appropriately-named Diamond Hoe (fruit) and although the Fairies dropped them, there was still no advancement to stage 2. My fault, I assume.

I tried both your Druid Trainer and Natural Materials quests and completed them without issue. The error you've provided is for a reach-location objective, and is therefore unrelated to this report.

The OP has not responded and Queen's quests do not seem to easily replicate the issue (although the attempt is appreciated). Therefore, I am closing this issue until such time it can be definitively reproduced.

**Closed by FlyingPikachu** 2017-07-05 04:57 UTC
Labels: bug, help wanted

**Comment by Enzo41814** [comment] 2017-07-05 05:41
![image](https://user-images.githubusercontent.com/29719828/27850466-4642ae94-612b-11e7-9c20-a28c0150989f.png)

**Comment by Enzo41814** [comment] 2017-07-05 05:43
Do I have to open a new topic?

**Comment by FlyingPikachu** [comment] 2017-07-05 06:07
@Enzo41814 I'm not sure what your picture is trying to show. Unless you have quest data (from your quests.yml) that can replicate the OP's issue, please create a new topic. Thanks!
