### ISSUE TITLE
Error: Could not pass event PlayerMoveEven [1.8.8]

### ISSUE THREAD

**Issue by PlugITNow** [FlyingPikachu/Quests#169] opened 2017-12-03 05:02 UTC
**What is your Quests version / build number ?**
Server: PaperSpigot-1.8.8-R0.1-SNAPSHOT
Plugin : Quests v3.0.6-b186

**Please describe the problem and how to replicate it. Any console errors?**
Several players can't do the quests and have an empty /quests , it can occur for a new player (he cant do any quest) or for a player which had done some quests.

The quests plugin throw a lot of errors when thoose bugy player are online (it makes large logs file)

I tried to reset / pass for stage or quest for those bugy players but it throw "An internal error occur..". I trie with other players wich are not bugy and these commands works fine.

**Can you provide an example quest from quests.yml _using Pastebin.com_?**

Errors : [https://pastebin.com/y3uSjB4G](url)

**Comment by FlyingPikachu** [comment] 2017-12-04 01:51
Welcome to the official Quests repo!

That is not a valid version of Quests. The current release is 3.0.0-Naomi. If you have used a fork of the plugin, please contact the author of said fork.

Additionally, PaperSpigot is not officially supported.

**Comment by FlyingPikachu** [comment] 2017-12-04 01:57
Duplicate of #154

**Closed by FlyingPikachu** 2017-12-04 01:57 UTC
