### ISSUE TITLE
Quests not loading or able to be created

### ISSUE THREAD

**Issue by JesterOwl** [FlyingPikachu/Quests#532] opened 2018-11-24 00:46 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?

Quests-3.4.2   on minecraft 1.13.2 with paper spigot
(__Required__) Please describe the problem and how to replicate it. Any console errors?

Basically, I load in a fresh install of quests and open up the editor. Everything works completely fine and I'm able to do everything I've tested. I can create the quest, edit stages- etc. 

The problem starts with finishing the quest. I save it and am then prompted with reloading the quests plugin with the command. That command ( /questadmin reload) doesn't work and it leaves an "Internal error etc." message. That leaves an error in the server and nothing happens. Restarting the server just removes the quest and then it's completely gone and my progress disappears and there are no quests.

Command Error : https://pastebin.com/iLPy1XmX

Full Log : https://pastebin.com/t8bpGLcf

**Comment by FlyingPikachu** [comment] 2018-11-24 22:17
Looks like a combination of issues. First, you have two copies of Vault in your /plugins folder - one named “Vault.jar” and “Vault-1.6.7.jar”. Secondly, the MythicMobsQuests module is failing to load. Not sure as to the cause, but that’d be a question for the developer of that module.

Feel free to open a new issue if you still experience hiccups after resolving those problems.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JesterOwl** [comment] 2018-11-24 23:53
Yea sorry, I didn't notice those problems. Unfortunately, neither fix the issue of quests not loading. To make sure I loaded a new server with only quests on it and I'm still receiving the same errors. My bad, I'm sure it's something dumb like having two vault jars but I just can't seem to figure it out : ( 

I also tried a few other things, like running in spigot over paper but it seems to have the same issue. The same thing seems to happen on 1.13.1. Just to clarify, there aren't any requirements for quests to run correctly, are there? I had quests on 1.12 and it worked perfectly, and I might have forgotten something as we ported the server over. I looked over the spigot page several times and didn't really see anything.

On Clean Server with only quests.jar (3.4.2) :

Command Error: https://pastebin.com/p6Qvs8Pm

Full Log: https://pastebin.com/kCWuCG5X

**Comment by FlyingPikachu** [comment] 2018-11-25 03:02
Looks like this actually a duplicate of #521 

It's already been fixed, so using the latest dev build should resolve the issue. I'll go ahead and publish it to Spigot as well.

**Closed by FlyingPikachu** 2018-11-25 03:02 UTC
Labels: bug, duplicate

**Comment by JesterOwl** [comment] 2018-11-25 05:43
Ahh, you're right. Sorry for being redundant, I should have checked the latest GitHub builds asjdfkla;sjdflka. I just stupidly assumed since they were named the same it wasn't different! Thanks for the quick responses and help, quests is now working perfectly again : )
