### ISSUE TITLE
 Bug when completing stage 1 it does NOT progress to stage 2. (Could not pass event NPCRightClickEvent to Quests v2.8.4-b130)

### ISSUE THREAD

**Issue by OwnAgePau** [FlyingPikachu/Quests#39] opened 2017-07-12 19:44 UTC
In your issue, please include:

Spigot 1.11.2
Quests 2.8.4 (build 130)

The problem is that I can't progress to a second stage after delivering the quest items.
Quest stage 1: 
- Break 64 iron ore blocks.
- Deliver 64 iron ore to Hogard (the quest giver).
Quest stage 2 (never arrives). Gets stuck there.

Quest File Content:

  custom3:
    name: Bucket List
    npc-giver-id: 16
    ask-message: Do you want to help me? I have got some gold if you are interested!
    finish-message: Thanks a lot, you helped me a great deal. Here be thy gold!
    gui-display: name-BUCKET:amount-1
    requirements:
      items:
      - name-BUCKET:amount-1
      remove-items:
      - true
      fail-requirement-message: You don't have a bucket? Who are you!!
    stages:
      ordered:
        '1':
          break-block-names:
          - IRON_ORE
          break-block-amounts:
          - 64
          break-block-durability:
          - 0
          items-to-deliver:
          - name-IRON_ORE:amount-64
          npc-delivery-ids:
          - 16
          delivery-messages:
          - Thanks!
          start-message: I ran out of Iron Ore, can you get me some?
          complete-message: Thanks! I can finally start making some more swords, the guards will be please (I hope).
        '2':
          break-block-names:
          - GOLD_ORE
          - COAL_ORE
          break-block-amounts:
          - 40
          - 32
          break-block-durability:
          - 1
          - 1
          items-to-deliver:
          - name-COAL:amount-32
          - name-GOLD_ORE:amount-40
          npc-delivery-ids:
          - 16
          - 16
          delivery-messages:
          - OOOOH SOO SHINY!!!
          start-message: Hey, can you also get me some gold ore and some coal please?
          complete-message: I am so grateful!
        '3':
          items-to-deliver:
          - name-IRON_PICKAXE:amount-1
          - name-IRON_PICKAXE:amount-1
          - name-IRON_SWORD:amount-1
          npc-delivery-ids:
          - 18
          - 18
          - 17
          delivery-messages:
          - Ooh a brand new tool, finally (my pickaxe was starting to break apart).
          - Ah, still no break? Thanks anyways.
          - Thanks for the deliveries!
          start-message: Our miners down the mine requested me to make them some tools, but I ain't going down that scary dark hole, here you bring it!
          complete-message: Thanks, it saved me a dangerous trip down the treacherous paths of the that scary dark place. Ugh.
    rewards:
      money: 10

Error:
ug when completing stage 1 it does NOT progress to stage 2.
Could not pass event NPCRightClickEvent to Quests v2.8.4-b130
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:414) [Citizens.jar:?]
at sun.reflect.GeneratedMethodAccessor351.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1537) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.
v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
at me.blackvein.quests.Quester.getObjectives(Quester.java:460) ~[?:?]
at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:416) ~[?:?]
at me.blackvein.quests.Quest.setStage(Quest.java:162) ~[?:?]
at me.blackvein.quests.Quest.nextStage(Quest.java:114) ~[?:?]
at me.blackvein.quests.Quester.finishObjective(Quester.java:1580) ~[?:?]
at me.blackvein.quests.Quester.deliverItem(Quester.java:1411) ~[?:?]
at me.blackvein.quests.NpcListener.onNPCRightClick(NpcListener.java:75) ~[?:?]
at sun.reflect.GeneratedMethodAccessor352.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]

**Comment by FlyingPikachu** [comment] 2017-07-14 03:14
Duplicate of #31 (fixed in version 2.9.0)

**Closed by FlyingPikachu** 2017-07-14 03:14 UTC

**Comment by OwnAgePau** [comment] 2017-07-15 08:40
I don't know why you closed both this one and the ones refrenced as dupes while this is clearly not fixed. I have just tested this in 2.9.0 build 140 and it still does NOT work. Same error message.

**Comment by FlyingPikachu** [comment] 2017-07-15 16:34
Closed because OP posted version as being 2.8.4, whereas a fix was applied in 2.9.0.

If you believe that fix did not work, post the new error message.
