### ISSUE TITLE
3.3.1 broken - "no permission"

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#380] opened 2018-04-26 19:49 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.1
(__Required__) Please describe the problem and how to replicate it. Any console errors?
after updating to 3.3.1 commands dont work anymore and every user get a "no permissions-message" in chat

**Comment by FlyingPikachu** [comment] 2018-04-26 20:44
Duplicate of #379

**Closed by FlyingPikachu** 2018-04-26 20:44 UTC
