### ISSUE TITLE
Delay Between Stages, stuck Quests.

### ISSUE THREAD

**Issue by Regnak85** [FlyingPikachu/Quests#297] opened 2018-02-17 19:51 UTC
Build:  DevBuild 261
Spigot 1.12.2

Sorry for my Bad English, i try to explain the Problem.

I Have a... "Welcome" Quest, Where the Player, has to "visit" some Locations on my Spawn.

So, first he got the Quest from NPC A, goes to NPC B. which gives him new Objectives.
There is everything fine, but then, nothing works anymore, because of the "Delay" i gave.
(Bevore Delay in Stages, everything worked fine)

------- Okay,  tried Code, wont work, i will upload the Quest...^^
[quests2.txt](https://github.com/FlyingPikachu/Quests/files/1734050/quests2.txt)

This is the Quest, WITHOUT Delay.
Because of the Long "Start" and "Complete" Messages, i wanted the Delay, so, Users have time to "read" the Quest.
But, if i put a delay, then, after stage 1 nothing happens if i Reach the Location

Ive Seen, after "Updating" the Quest Objective in Chat, there is a strange new line, only with Delay enabled:

---Willkommen!---
Besuche den Steinmetz

Without Delay, but with Delay its:

---Willkommen!---
(<quest>)
Besuche den Steinmetz

And, it stucks.
Sorry, i hope you can understand what i mean.... :/

**Comment by FlyingPikachu** [comment] 2018-02-17 23:06
Possible duplicate of #289

**Comment by FlyingPikachu** [comment] 2018-12-01 08:04
Fixed in the following dev build:
http://ci.ac3-servers.eu/job/Quests/519/

**Closed by FlyingPikachu** 2018-12-01 08:04 UTC
Labels: bug
