### ISSUE TITLE
3 bugs

### ISSUE THREAD

**Issue by Enzo41814** [FlyingPikachu/Quests#17] opened 2017-06-28 03:45 UTC
3 Bugs Found:
- Does not work with a second stage or more.
- When the user leaves the game and join the game again, the quests goes to the next stage or ends the quests.
- The file "config.yml" is not saved correctly.
A bug that appears in the console:
https://pastebin.com/xKWTsGPg
Tested in Minecraft 1.12

**Comment by FlyingPikachu** [comment] 2017-06-28 03:54
1st bug is duplicate of #16

@Enzo41814 For the 2nd bug, perhaps I don't fully understand, but it sounds like that and the 3rd bug are caused by the 1st bug. If you believe otherwise, feel free to open a new issue with more details.

Closing as duplicate.

**Closed by FlyingPikachu** 2017-06-28 03:54 UTC
