### ISSUE TITLE
All java errors with quests 3.4.3 that i have. (Not with quests 3.3.7)

### ISSUE THREAD

**Issue by tiradorus** [FlyingPikachu/Quests#536] opened 2018-11-29 10:01 UTC
**(__Required__) What is your Quests version / build number (do _not_ say "latest")?**

3.4.3 quest version.
1.8.8 Minecraft server version

**(__Required__) Please describe the problem and how to replicate it. Any console errors?**

Just instal quests, and take a quest from a NPC.

Here are the errors:

```
[10:53:52 WARN]: [Quests] Task #351 for Quests v3.4.3-b508 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/Particle
at me.blackvein.particles.Eff_1_13_R1.<clinit>(Eff_1_13_R1.java:20) ~[?:?]
at me.blackvein.quests.NpcEffectThread.showEffect_1_13_R1(NpcEffectThread.java:234) ~[?:?]
at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:76) ~[?:?]
at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:54) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Particle
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
... 11 more
```

```
[11:00:27 WARN]: [Quests] Task #351 for Quests v3.4.3-b508 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class me.blackvein.particles.Eff_1_13_R1
at me.blackvein.quests.NpcEffectThread.showEffect_1_13_R1(NpcEffectThread.java:234) ~[?:?]
at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:76) ~[?:?]
at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:54) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[11:00:28 WARN]: [Quests] Task #351 for Quests v3.4.3-b508 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class me.blackvein.particles.Eff_1_13_R1
at me.blackvein.quests.NpcEffectThread.showEffect_1_13_R1(NpcEffectThread.java:234) ~[?:?]
at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:76) ~[?:?]
at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:54) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

+

Players can pick-up items from NPC (The item to take a quest) and throw it on the ground.

**Comment by FlyingPikachu** [comment] 2018-11-29 18:05
Duplicate of #516

Use this dev build - http://ci.ac3-servers.eu/job/Quests/511/

**Closed by FlyingPikachu** 2018-11-29 18:05 UTC
