### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by KookaiPLZ** [FlyingPikachu/Quests#535] opened 2018-11-25 15:18 UTC
Hey, can you tell me, what these errormsgs mean and how to fix them? They get constantly every second into my console.
root@srv49689:~# screen -rx Freebuild
[10:17:22 WARN]: [Quests] Task #273788 for Quests v3.4.2-b500 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class me.blackvein.particles.Eff_1_13_R1
        at me.blackvein.quests.NpcEffectThread.showEffect_1_13_R1(NpcEffectThread.java:224) ~[?:?]
        at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:70) ~[?:?]
        at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:54) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
>

**Comment by FlyingPikachu** [comment] 2018-11-25 21:56
Please use the latest Spigot build (3.4.3) and post the new error if it doesn’t resolve the issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KookaiPLZ** [comment] 2018-11-27 14:35
Yeah, I think so, but what was the problem?

**Comment by FlyingPikachu** [comment] 2018-11-27 18:55
You have not posted the 3.4.3 version of the error as requested. Please download Quests 3.4.3 from Spigot and post the new error generated by that version.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KookaiPLZ** [comment] 2018-11-28 18:16
[13:15:57 WARN]: [Quests] Task #66379 for Quests v3.4.3-b508 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class me.blackvein.particles.Eff_1_13_R1
        at me.blackvein.quests.NpcEffectThread.showEffect_1_13_R1(NpcEffectThread.java:234) ~[?:?]
        at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:76) ~[?:?]
        at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:54) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by FlyingPikachu** [comment] 2018-11-28 22:34
Duplicate of #516

This build should resolve the issue once available - http://ci.ac3-servers.eu/job/Quests/510/

**Closed by FlyingPikachu** 2018-11-28 22:34 UTC

**Comment by KookaiPLZ** [comment] 2018-11-30 14:49
But it doesnt!!!!!!!

**Comment by FlyingPikachu** [comment] 2018-11-30 19:03
Sorry about that! Try http://ci.ac3-servers.eu/job/Quests/514/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
