### ISSUE TITLE
Minor Annoyance with the end title after a quest is finished.

### ISSUE THREAD

**Issue by HyperDioxide** [FlyingPikachu/Quests#166] opened 2017-11-23 15:40 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 3.0.0-Naomi

(__Required__) Please describe the problem and how to replicate it. Any console errors?
It's not really a major problem, but it is a minor annoyance for some ops. I know there is a gamerule for it but I require command feedback for other things.
When a quest is completed, a message known as " [Server: Title command succesfully executed]
Is there a way to prevent this without the gamerule? Thank you.
I appreciate the hard work you put in for this amazing plugin!

**Comment by FlyingPikachu** [comment] 2017-12-01 05:53
/gamerule sendCommandFeedback false

Duplicate of #98

**Closed by FlyingPikachu** 2017-12-01 05:53 UTC
