### ISSUE TITLE
Issue Grabbing Data

### ISSUE THREAD

**Issue by whoshenry** [FlyingPikachu/Quests#134] opened 2015-06-05 17:21 UTC
Just got spammed by this in the console - http://pastebin.com/b8N3my4L

This particular Quest has been working fine for the last week.

**Comment by FlyingPikachu** [comment] 2015-06-06 11:51
Probable duplicate of #93 

Please upload your "Give a dog a bone" quest as well as make sure the NPC for that quest is valid.

**Comment by whoshenry** [comment] 2015-06-06 14:28
Here is the Quest - http://pastebin.com/1VtaJG75

I have only had this happen once the whole time Quests has been released on my server, so it is rare but it obviously can happen. I think it might be due to data corruption in the player's profile? I looked at his UUID file in the data folder, removed all current quests and stages, restarted the server with the updated file and everything was working correctly.

The NPC is valid and working correctly also.

**Closed** 2015-06-06 20:10 UTC
