### ISSUE TITLE
Another BUG

### ISSUE THREAD

**Issue by LinearBotSystems** [FlyingPikachu/Quests#77] opened 2017-07-26 14:51 UTC
When you have a quest open with USE Block you can't make an new quest with a location in it reason is this 
in PlayerListiner in line 172
`	public void onPlayerInteract(PlayerInteractEvent evt) {
		if (plugin.checkQuester(evt.getPlayer().getUniqueId()) == false) {
			if (evt.getAction().equals(Action.RIGHT_CLICK_BLOCK)) {
				final Quester quester = plugin.getQuester(evt.getPlayer().getUniqueId());
				final Player player = evt.getPlayer();
				boolean hasObjective = false;
				for (Quest quest : quester.currentQuests.keySet()) {
					if (quester.hasObjective(quest, "useBlock")) {
						ItemStack i = new ItemStack(evt.getClickedBlock().getType(), 1, evt.getClickedBlock().getState().getData().toItemStack().getDurability());
						quester.useBlock(quest, i);
						hasObjective = true;
					}
				}
				if (!hasObjective) {`

hasObjective turns off all listener I don't know why maybe because you complete accidentally a quest while making a new one ? The other way around is much more BS

**Comment by FlyingPikachu** [comment] 2017-07-27 05:45
Closing as no Quests version has been provided.

Furthermore, I don't understand what the problem is. Are you saying that code should be run when the player has no objective? Like a I noted in a previous issue, I think your point would be better made through a PR.

**Closed by FlyingPikachu** 2017-07-27 05:45 UTC

**Comment by LinearBotSystems** [comment] 2017-07-27 06:08
Quest version was 2.9.6 (naturally)

I have no code because I don't know the site effect of this.

So far I understand it the code block which follow won't be run when you have an active quest with a USE Block objective.  Basically the first part has to do with active questing the second part has to do with all kinds of locations when creating new quests. I don't know how a changed quest state could affect the creation of a new quest when you are in the middle of it. But we need at least a warning otherwise people run into walls like I did and wondering why it won't work anymore.
