### ISSUE TITLE
Problem with language

### ISSUE THREAD

**Issue by EmpereurNero** [FlyingPikachu/Quests#534] opened 2018-11-25 12:04 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests-3.4.2

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Can't find the fr-FR translation
https://zupimages.net/up/18/47/jzrr.jpg 

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by FlyingPikachu** [comment] 2018-11-26 04:05
Likely duplicate of #481 

@EmpereurNero Hello, could you please answer the following questions:

1. What is your operating system (Ubuntu, Windows 10, et al.)
2. Does a _strings.yml_ file exist in `\plugins\Quests\lang\fr-FR` ?
3. Does upgrading to Quests-3.4.3 resolve the issue?

**Comment by EmpereurNero** [comment] 2018-11-27 21:29
Hello !

1.Windows 10
2. The folder lang is not created when i instal the plugin. But strings.yml file exist in the .jar only (not in the plugin folder)
3. No :/

**Comment by FlyingPikachu** [comment] 2018-11-28 05:50
@EmpereurNero  Please give the following dev build a try once available, then post the resulting your startup log:

http://ci.ac3-servers.eu/job/Quests/509/

**Comment by FlyingPikachu** [comment] 2018-12-01 08:59
Closing as issue should be resolved. If not, try the following:
https://github.com/FlyingPikachu/Quests/wiki/Translations#there-are-no-language-files-or-folders

**Closed by FlyingPikachu** 2018-12-01 08:59 UTC
Labels: bug, duplicate
