### ISSUE TITLE
Mobkill count doesn't increases. Problem happens on beta builds.

### ISSUE THREAD

**Issue by mariolars** [FlyingPikachu/Quests#143] opened 2017-10-05 12:21 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?

3.0.6 commit 14882fb3eddc8402598ff4ec5003942e772085b1

(__Required__) Please describe the problem and how to replicate it. Any console errors?

Builds after "Quests Naomi" doesn't count player mobkill in any way bow nor sword. No console error.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

https://pastebin.com/kWhvvpLR

**Comment by FlyingPikachu** [comment] 2017-12-11 04:21
After some investigation, I've determined that this is a duplicate of #117

**Closed by FlyingPikachu** 2017-12-11 04:21 UTC
Labels: bug
