### ISSUE TITLE
Server Announcements / Broken Heart

### ISSUE THREAD

**Issue by WanderingRaven** [FlyingPikachu/Quests#190] opened 2017-12-24 15:49 UTC
VERSION:  Quests 3.1.4

1.  Server Announcements:  There is a Server-wide Announcement after a person finishes a quest.  Is there any way to turn that off?  It sort of spams the chat, not to mention that there's some issue/error with it on my own server that instead of actually being the notification, it's a Server Error message.

2.  Once someone has completed a quest, there is a strange "broken heart" image above the NPC's head (instead of the little music note).  Is there a way to turn that off, or change it?  The broken heart is confusing (why is he so sad?).

3.  Updated to 3.1.5 and the plugin wouldn't work.  Had to downgrade to 3.1.4 to get it to show up.

That's it for now.  Thank you!

**Comment by FlyingPikachu** [comment] 2017-12-25 18:12
Which announcement specifically is it that everyone sees (please copy/paste or post screenshot)? It's just myself in my test environment so I have no way of telling which one you mean.

The "broken heart" is actually the angry_villager effect and was chosen for compatibility reasons. It can be changed in config.yml under 'npc-effects.redo-quest'

What is it that wouldn't work / show up in 3.1.5?

**Comment by WanderingRaven** [comment] 2017-12-27 01:54
Everytime a title shows up on the players screen while doing a quest, it comes up with the following message twice:
**[Server: Title command successfully executed]**
So when you accept the quest, the command pops up globally for ALL players in the chat twice.  Basically anytime the quest puts large text on your screen, this command pops up.

The entire plugin wouldn't work when I tried 3.1.5 - it wouldn't show up in the plugins list in game, nor would any commands work, but it was added to the plugins folder correctly.

**Comment by FlyingPikachu** [comment] 2017-12-27 16:39
The message you've described can not be seen by anyone whom is not an op. That said, I would hope you haven't opped all players in a public server. Run `/gamerule sendCommandFeedback false` to stop these messages. Duplicate of #166

As for 3.1.5 not loading, it's runs without any issue on my setup. Since you're the only person to report a problem, perhaps the file got corrupted somehow during download? Or maybe you forgot to delete the old Quests version? Unfortunately, the only other thing I could do is examine your startup log, should you wish to provide it.

Comment with startup log to reopen.

**Closed by FlyingPikachu** 2017-12-27 16:39 UTC
