### ISSUE TITLE
Stages + Delivery Messages

### ISSUE THREAD

**Issue by Midnight9746** [FlyingPikachu/Quests#35] opened 2017-07-10 06:16 UTC
Quests-2.8.7, spigot, 1.8.8/1.8.9

- Unsure how to fix some of stages not progressing when completed and delivery message won't display. It will get stuck on 4 and require a force stage even tho I gave the npc the items. Also, I wanted it to tell the player a custom delivery message, but it's still saying "Deliver x" I also don't know why it does "name-IRON_SWORD:amount-1:displayname-\xa70\xa70\xa70\xa70\xa70\xa70\xa70\xa7\
        8\xa75\xa7l\xa7f\xa7lSage" either.
[Help.zip](https://github.com/FlyingPikachu/Quests/files/1134557/Help.zip)

quests:
  custom2:
    name: Trouble In Hyrule Pt 1
    npc-giver-id: 0
    ask-message: "\xa74I've been investigating into Hyrule's Royal Guards,\\ \\ and\
      \ noticed something is off!"
    finish-message: "\xa74The Kingdome of \xa7cHyrule \xa74thanks you for your help,\
      \ Hope we can count on you again!"
    stages:
      ordered:
        '1':
          npc-ids-to-kill:
          - 127
          npc-kill-amounts:
          - 1
          locations-to-reach:
          - TP -56.0 76.0 -4961.0
          reach-location-radii:
          - 3
          reach-location-names:
          - Hyrule Castle
          start-message: '&4First we must kill the evil &0Link&4!'
          complete-message: '&4Continue through the castle and reach the top, Zelda
            is counting on you to save her!'
        '2':
          npc-ids-to-kill:
          - 128
          npc-kill-amounts:
          - 1
          locations-to-reach:
          - TP -56.0 139.0 -5000.0
          reach-location-radii:
          - 5
          reach-location-names:
          - Boss Room (Upstairs)
          start-message: '&4Onward to &4Z&celda&4, There are Checkpoints to help guide
            you on your quest!'
          complete-message: '&4Kill &4G&ca&7n&8o&0n'
        '3':
          npc-ids-to-kill:
          - 131
          npc-kill-amounts:
          - 1
          start-message: '&4Here we are, don''t turn away now!'
          complete-message: '&cHurry to the Princess!'
        '4':
          items-to-deliver:
          - "name-GOLD_AXE:amount-1:displayname-\xa78\xa7lAxe \xa77\xa7lOf \xa74H\xa7\
            ce\xa76l\xa7el"
          npc-delivery-ids:
          - 130
          **delivery-messages:
          - '&4Give &2L&aink&4, &4H&ce&6l&el&fs &4weapon!**'
          start-message: '&cI feel a change in the world'
          complete-message: '&cAh the &8&lAxe &7&lOf &4H&ce&6l&el&c!'
        '5':
          items-to-deliver:
          - "name-IRON_SWORD:amount-1:displayname-\xa7f\xa7lSage \xa77\xa7lSword"
          npc-delivery-ids:
          - 129
          delivery-messages:
          - '&4Give &8M&7idna&4, &4G&ca&7n&8o&0n&fs &4weapon!'
          start-message: '&cWhat about me'
          complete-message: '&cThank you for giving me this'
        '6':
          items-to-deliver:
          - "name-DIAMOND_SWORD:amount-1:displayname-\xa75\xa7lMaster \xa78\xa7lSword"
          npc-delivery-ids:
          - 126
          delivery-messages:
          - '&4Return the &5Master &8Sword &4back to &4Z&celda'
          start-message: '&cI hope you brought me the &5&lMaster &8&lSword, &cthat
            &0&lDark Link &ctook!'
          complete-message: '&cThank you very much. I have granted you 3 weapons,
            all improvments of what you brought'
    rewards:
      items:
      - "name-DIAMOND_SWORD:amount-1:displayname-\xa70\xa70\xa70\xa70\xa70\xa70\xa7\
        0\xa77\xa76\xa7l\xa75\xa7lMaster \xa78\xa7lSword:lore-\xa70\xa70\xa70\xa7\
        0\xa70\xa70\xa70\xa77\xa7fOne handed              \xa74\xa7lEvil's \xa78\xa7\
        lBane\xa7c\xa7a\xa7f\xa7e\xa70\xa70\xa70\xa70:lore-\xa7f40 Damage:lore-\xa7\
        aNever breaks:lore-\xa7aShoots an arrow. (1.0s cooldown):lore-\xa7e\xa7o\"\
        This sword was given you to by:lore-\xa7e\xa7o\xa74\xa7oZ\xa7c\xa7oelda\xa7\
        e\xa7o, as the new holder of the:lore-\xa7e\xa7osword!\":lore-\xa7f\xa75\xa7\
        lLegendary:lore-\xa7f\xa7d\xa7lSacred \xa7b\xa7lPower"
      - "name-IRON_SWORD:amount-1:displayname-\xa70\xa70\xa70\xa70\xa70\xa70\xa70\xa7\
        8\xa75\xa7l\xa7f\xa7lSage \xa77\xa7lSword:lore-\xa70\xa70\xa70\xa70\xa70\xa7\
        0\xa70\xa78\xa7fdouble     \xa7e\xa7lGods\xa7c\xa7a\xa7f\xa7e\xa70\xa70\xa7\
        0\xa70:lore-\xa7f35-40 Damage:lore-\xa7aNever breaks:lore-\xa7e\xa7o\"In the\
        \ olden:lore-\xa7e\xa7odays when the:lore-\xa7e\xa7o\xa7f\xa7l\xa7oStages\
        \ \xa7e\xa7otried to:lore-\xa7e\xa7okill \xa74\xa7l\xa7oG\xa7c\xa7l\xa7oa\xa7\
        7\xa7l\xa7on\xa78\xa7l\xa7oo\xa70\xa7l\xa7on\xa7e\xa7o,:lore-\xa7e\xa7othings\
        \ ended:lore-\xa7e\xa7obadly with the:lore-\xa7e\xa7odemise of a:lore-\xa7\
        e\xa7o\xa7f\xa7l\xa7oSage\xa7e\xa7o\":lore-\xa7f\xa75\xa7lCorrupted:lore-\xa7\
        f\xa7d\xa7lCursed"
      - "name-GOLD_AXE:amount-1:displayname-\xa70\xa70\xa70\xa70\xa70\xa70\xa70\xa7\
        9\xa75\xa7l\xa78\xa7lAxe \xa77\xa7lOf \xa74H\xa7ce\xa76l\xa7el:lore-\xa70\xa7\
        0\xa70\xa70\xa70\xa70\xa70\xa79\xa7fdouble     \xa74B\xa7cu\xa76r\xa7en\xa7\
        6i\xa7cn\xa74g\xa7c\xa7a\xa7f\xa7e\xa70\xa70\xa70\xa70:lore-\xa7f35-40 Damage:lore-\xa7\
        aNever breaks:lore-\xa7e\xa7o\"You never know:lore-\xa7e\xa7owhen you need\
        \ to:lore-\xa7e\xa7ocall apond:lore-\xa7e\xa7o\xa74\xa7l\xa7oH\xa78\xa7l\xa7\
        oades\xa74\xa7l\xa7o's \xa7e\xa7oWraith\":lore-\xa7f\xa74H\xa7ce\xa76l\xa7\
        el \xa78\xa7lIf \xa77\xa7lI \xa7f\xa7lKnow:lore-\xa7f\xa74\xa7lUnder\xa78\xa7\
        lworld"
      money: 5000

**Comment by FlyingPikachu** [comment] 2017-07-10 16:06
Duplicate of #31 

@Midnight9746 Use latest dev build, version 2.9.0

**Closed by FlyingPikachu** 2017-07-10 16:06 UTC

**Comment by Midnight9746** [comment] 2017-07-10 16:38
Ok! Thank you so very much, sorry that it was a duplicate, first time using the site.
