### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by haruh09** [FlyingPikachu/Quests#372] opened 2018-04-19 15:28 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
last
(__Required__) Please describe the problem and how to replicate it. Any console errors?
19.04 17:27:07 [Multicraft] Skipped 8 lines due to rate limit (30/s)
19.04 17:27:07 [Server] ERROR Could not pass event PlayerMoveEvent to Quests v3.3.0-b300
19.04 17:27:07 [Server] INFO org.bukkit.event.EventException: null
19.04 17:27:07 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-3d850ec-809c399]
19.04 17:27:07 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3d850ec-809c399]
19.04 17:27:07 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-3d850ec-809c399]
19.04 17:27:07 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-3d850ec-809c399]
19.04 17:27:07 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:654) [spigot.jar:git-Spigot-3d850ec-809c399]
19.04 17:27:07 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-3d850ec-809c399]
19.04 17:27:07 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot.jar:git-Spigot-3d850ec-809c399]
19.04 17:27:07 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-3d850ec-809c399]
19.04 17:27:07 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
19.04 17:27:07 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
19.04 17:27:07 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-3d850ec-809c399]
19.04 17:27:07 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-3d850ec-809c399]
19.04 17:27:07 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-3d850ec-809c399]
19.04 17:27:07 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-3d850ec-809c399]
19.04 17:27:07 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-3d850ec-809c399]
19.04 17:27:07 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
19.04 17:27:07 [Server] INFO Caused by: java.lang.NullPointerException

**Comment by FlyingPikachu** [comment] 2018-04-20 14:44
You've cut off the error. The important bits that I need follow the line

`19.04 17:27:07 [Server] INFO Caused by: java.lang.NullPointerException`

**Comment by haruh09** [comment] 2018-04-22 22:28
23.04 00:27:42 [Server] ERROR Could not pass event PlayerMoveEvent to Quests v3.3.0-b300
23.04 00:27:42 [Server] INFO org.bukkit.event.EventException: null
23.04 00:27:42 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:42 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:42 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:42 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:42 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:654) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:42 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:42 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:42 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:42 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
23.04 00:27:42 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
23.04 00:27:42 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:42 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:42 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:42 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:42 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:42 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
23.04 00:27:42 [Server] INFO Caused by: java.lang.NullPointerException
23.04 00:27:42 [Server] INFO at me.blackvein.quests.Quester.reachLocation(Quester.java:1094) ~[?:?]
23.04 00:27:42 [Server] INFO at me.blackvein.quests.PlayerListener.onPlayerMove(PlayerListener.java:726) ~[?:?]
23.04 00:27:42 [Server] INFO at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source) ~[?:?]
23.04 00:27:42 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
23.04 00:27:42 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
23.04 00:27:42 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:42 [Server] INFO ... 15 more
23.04 00:27:46 [Server] INFO CONSOLE issued server command: /list 
23.04 00:27:46 [Server] INFO Es sind 3 von maximal 23 Spielern online.
23.04 00:27:46 [Server] INFO Verbundene Spieler:haruh09, Valmgrim, waldi08
23.04 00:27:47 [Server] ERROR Could not pass event PlayerMoveEvent to Quests v3.3.0-b300
23.04 00:27:47 [Server] INFO org.bukkit.event.EventException: null
23.04 00:27:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:47 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:47 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:654) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:47 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:47 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:47 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:47 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
23.04 00:27:47 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
23.04 00:27:47 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:47 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:47 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:47 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:47 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:47 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
23.04 00:27:47 [Server] INFO Caused by: java.lang.NullPointerException
23.04 00:27:47 [Server] INFO at me.blackvein.quests.Quester.reachLocation(Quester.java:1094) ~[?:?]
23.04 00:27:47 [Server] INFO at me.blackvein.quests.PlayerListener.onPlayerMove(PlayerListener.java:726) ~[?:?]
23.04 00:27:47 [Server] INFO at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source) ~[?:?]
23.04 00:27:47 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
23.04 00:27:47 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
23.04 00:27:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:47 [Server] INFO ... 15 more
23.04 00:27:49 [Server] ERROR Could not pass event PlayerMoveEvent to Quests v3.3.0-b300
23.04 00:27:49 [Server] INFO org.bukkit.event.EventException: null
23.04 00:27:49 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:49 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:49 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:654) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:49 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:49 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:49 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:49 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
23.04 00:27:49 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
23.04 00:27:49 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:49 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:49 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:49 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:49 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:49 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
23.04 00:27:49 [Server] INFO Caused by: java.lang.NullPointerException
23.04 00:27:49 [Server] INFO at me.blackvein.quests.Quester.reachLocation(Quester.java:1094) ~[?:?]
23.04 00:27:49 [Server] INFO at me.blackvein.quests.PlayerListener.onPlayerMove(PlayerListener.java:726) ~[?:?]
23.04 00:27:49 [Server] INFO at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source) ~[?:?]
23.04 00:27:49 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
23.04 00:27:49 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
23.04 00:27:49 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:49 [Server] INFO ... 15 more
23.04 00:27:49 [Server] ERROR Could not pass event PlayerMoveEvent to Quests v3.3.0-b300
23.04 00:27:49 [Server] INFO org.bukkit.event.EventException: null
23.04 00:27:49 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-3d850ec-809c399]
23.04 00:27:49 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3d850ec-809c399]

**Comment by FlyingPikachu** [comment] 2018-12-01 08:11
Thanks for submitting this issue and sorry I wasn't able to get to it. Chances are the issue has been resolved in recent builds of Quests. If you find that not to be the case, post the error generated by a recent version of Quests and I'll re-open the issue.

**Closed by FlyingPikachu** 2018-12-01 08:11 UTC
