### ISSUE TITLE
Error occured when trying to enable quest

### ISSUE THREAD

**Issue by BinaryGh0st** [FlyingPikachu/Quests#40] opened 2015-03-02 03:02 UTC
When starting the server, I get an error when it tries to enable quests
Here is what i get in the console:
[02:54:11 INFO]: [Quests] Enabling Quests v2.2.5
[02:54:11 ERROR]: Error occurred while enabling Quests v2.2.5 (Is it up to date?)
java.lang.NoClassDefFoundError: com/herocraftonline/heroes/Heroes
	at me.blackvein.quests.Quests.linkOtherPlugins(Quests.java:419) ~[?:?]
	at me.blackvein.quests.Quests.onEnable(Quests.java:184) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
Caused by: java.lang.ClassNotFoundException: com.herocraftonline.heroes.Heroes
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_72]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_72]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_72]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_72]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_72]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_72]
	... 13 more

**Comment by FlyingPikachu** [comment] 2015-03-02 04:24
Heroes integration looks broken. Would you mind starting up without Heroes to confirm?

**Comment by BinaryGh0st** [comment] 2015-03-02 04:49
yeah that was the problem, it works now, thank you for the support

**Comment by BinaryGh0st** [comment] 2015-03-02 04:49
Much appreciated!

**Comment by BinaryGh0st** [comment] 2015-03-02 04:55
now it seems that none of the npcs are clickable like they used to be. There is also in not any errors spamming when i try right clicking so I'm not sure what could be causing that

**Comment by BinaryGh0st** [comment] 2015-03-02 04:55
I loaded in my old quest.yml from the original quest plugin along with the data and all the support files

**Comment by FlyingPikachu** [comment] 2015-03-02 05:01
Thanks. For you other issue, follow the directions on the Spigot page, in the Overview tab.

Leaving this ticket open until I can attempt to fix Heroes support. If you have any new issues, please create a new ticket.

**Comment by BinaryGh0st** [comment] 2015-03-02 05:18
alright should have done that in the first place, sorry to be a bother, but once again thanks for the support have a good day

**Comment by Leescar** [comment] 2015-03-02 17:57
The version of heroes that you are using -1.5.5.4 despite being "versionless" will still gets a heap of errors when your attempting to run it with some sort of compatibility with other plugins.

At best you would have to run spigot 1.7.9 and then whatever other plugins with their respective 1.7.9 spigot versions as most plugins read and run differently on 1.8 spigot. 
You might get lucky and find a few 1.8 spigot plugins that still have compatibility with heroes and attempt to stay at 1.8 spigot. 

The lead dev of heroes did say just last Wednesday that they are having show stopping bugs (enchanting system, skill issues) and other things preventing them from 1.8 and are openly looking for devs to volunteer time/knowledge.

**Comment by FlyingPikachu** [comment] 2015-03-04 18:21
It seems to me that the issue is on Heroes' end. Their issue tracker seems to be down so I posted a comment in the link below. Please upvote it if you have a Spigot account! :)

http://www.spigotmc.org/threads/heroes-rpg.10094/page-8#post-590550

**Comment by FlyingPikachu** [comment] 2015-03-19 13:56
It seems as though Heroes disables itself on-startup with the latest Spigot builds, which causes the OP's error. Until Heroes is updated, there's nothing I can do. Marking as 'help wanted' for now.

**Comment by Formula350** [comment] 2015-03-25 17:07
@FlyingPikachu
You had said "Thanks. For your other issue, follow the directions on the Spigot page, in the Overview tab."
Which I believe was in response to the "not being able to right-click NPCs" problem. If that's correct then I went up and down the Overview page and saw nothing that pertained to that, even read the comments. I know one of your updates (2.3.2 was it?) addressed that, but unfortunately it didn't fix it for my server. Even having the option to take quests via command for those which have an NPC being enabled is not quite solving the issue completely, as some quests require you to talk to an NPC or deliver something, and they are unable to. Up until recently I know that a lot of problems my players had, are not ones I could reproduce myself; however, this one afflicts me as well since even I'm unable to interact with quest-giving NPCs :\

Should I make a new issue post?
Is this also related to my server using Java 1.7? 
(Note: I have not updated to 1.8.3 either, on account of a couple of our main plugins breaking with that version of CraftBukkit. I'm using approximately the Feb 22nd release of CB1.8 R0.1)

**Comment by FlyingPikachu** [comment] 2015-03-25 18:04
@Formula350 I think I was talking about the Updating to 2.0.0 info, but I can't recall. Yes, please open a new issue.

**Comment by FlyingPikachu** [comment] 2015-04-17 12:39
@Leescar has pointed out that there is a new Heroes build: http://www.spigotmc.org/resources/heroes-rpg.305/update?update=21623

@BinaryGh0st Please test that build and let us know if the error persists! :)

**Comment by FlyingPikachu** [comment] 2015-06-04 21:35
Assuming the new Heroes build is working. If not, feel free to open a new issue.

**Closed by FlyingPikachu** 2015-06-04 21:35 UTC
Labels: help wanted
