### ISSUE TITLE
Could not pass event PlayerCommandPreprocessEvent

### ISSUE THREAD

**Issue by RubenStryker** [FlyingPikachu/Quests#492] opened 2018-10-18 20:06 UTC
Quests version: Quests v3.3.4-b316

The problem prevents doing any command with the user who suffers it, giving the following result:

![image](https://user-images.githubusercontent.com/24832320/47180771-a3c86180-d321-11e8-90e8-d9f08c00e27c.png)

The problem at the moment seems to affect specific users, it does not happen to all of them.

Quests.yml -> https://pastebin.com/2bVk3EXj
Logs -> https://pastebin.com/ASx0fenB

**Comment by FlyingPikachu** [comment] 2018-11-13 06:06
I'm thinking this was fixed in a recent build. Please try Quests 3.4.0 or greater and let us know whether the issue is resolved.

**Comment by FlyingPikachu** [comment] 2018-12-01 08:56
Closing due to lack of response from OP.

**Closed by FlyingPikachu** 2018-12-01 08:56 UTC
Labels: bug
