### ISSUE TITLE
Permission custome Quest

### ISSUE THREAD

**Issue by MatChev04** [FlyingPikachu/Quests#513] opened 2018-11-11 13:48 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?

(__Required__) Please describe the problem and how to replicate it. Any console errors?

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by FlyingPikachu** [comment] 2018-11-12 02:39
Duplicate of #514 by same user

**Closed by FlyingPikachu** 2018-11-12 02:39 UTC
