### ISSUE TITLE
Console spam error

### ISSUE THREAD

**Issue by craftercis** [FlyingPikachu/Quests#113] opened 2017-08-23 20:39 UTC
**Version: 3.0.0**

I have this error sometimes with a player. I dont know why en how... This is the error that spams in the console:
https://pastebin.com/7ha84Yug

**This is the link to my quests files**
[Quests.zip](https://github.com/FlyingPikachu/Quests/files/1247058/Quests.zip)
https://www.dropbox.com/s/8ie8hdfc1eun62v/Quests.zip?dl=0

I have a quest that you must wait an hour for you can go to the next quest. Idk of there the problem is..

Please help me out.

**Comment by FlyingPikachu** [comment] 2017-08-24 01:36
Your quests.yml file is corrupted. I tried downloading from both locations, but they both look the same. Here's an excerpt - https://pastebin.com/iVtg3cW2

I'm not saying that's the cause of the problem, but you'll have to resolve this before I can test anything.

**Comment by craftercis** [comment] 2017-08-24 08:22
This yml is weird because this is what it looks on my computer:
https://pastebin.com/FpanqN13

I hope you can now test it

**Comment by FlyingPikachu** [comment] 2017-08-24 18:30
Your quests.yml is still corrupted. Take a look at line 107 in the pastebin, for example, which consists of:

`§3§l=§b§l=§3§l=§b§l=§3§l=§b§l=§3§l=§b§l=§3§l=§b§l=§3§l=§b§l=§3§l=§b§l=§3§l=§b§l=§`

Those appear to be color values, but I think it's safe to say Quests can't handle that mess. Your events.yml and config.yml look fine.

**Comment by FlyingPikachu** [comment] 2017-08-28 18:43
Closing as an issue with quests.yml file. If you need further assistance after you've repaired the file, feel free to open a new issue. Thanks!

**Closed by FlyingPikachu** 2017-08-28 18:43 UTC
