### ISSUE TITLE
End_Stone not support

### ISSUE THREAD

**Issue by svmine** [FlyingPikachu/Quests#507] opened 2018-11-07 20:48 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?

(__Required__) Please describe the problem and how to replicate it. Any console errors?

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by svmine** [comment] 2018-11-07 20:52
Quests 3.3.4
error:
`[03:41:31 ERROR]: [Quests] The item name 'END_STONE' is invalid. Make sure quests.yml is UTF-8 encoded
[03:41:31 WARN]: Unexpected exception while parsing console command "questadmin reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'questadmin' in plugin Quests v3.3.4-b316
 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
 at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
 at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
 at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
 at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
 at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:94) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
 at me.blackvein.quests.Quests.processStages(Quests.java:2636) ~[Quests-3.3.4%20(1).jar:?]
 at me.blackvein.quests.Quests.loadQuests(Quests.java:2161) ~[Quests-3.3.4%20(1).jar:?]
 at me.blackvein.quests.Quests.reloadQuests(Quests.java:1991) ~[Quests-3.3.4%20(1).jar:?]
 at me.blackvein.quests.Quests.adminReload(Quests.java:743) ~[Quests-3.3.4%20(1).jar:?]
 at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:726) ~[Quests-3.3.4%20(1).jar:?]
 at me.blackvein.quests.Quests.onCommand(Quests.java:689) ~[Quests-3.3.4%20(1).jar:?]
 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
 ... 8 more
`
config quests.yml
https://pastebin.com/i0qZvhrW

**Comment by svmine** [comment] 2018-11-07 20:53
pls fix error, goodluck day

**Comment by FlyingPikachu** [comment] 2018-11-07 21:36
Possible duplicate of #446

**Comment by FlyingPikachu** [comment] 2018-11-08 01:35
Changing "END_STONE" to "ENDER_STONE" resolves the issue.

"ENDER_STONE" is for 1.12 while "END_STONE" is for 1.13. Leaving this open until I can find a way to gracefully convert legacy names.

**Comment by mercurialmusic** [comment] 2018-11-12 00:18
I'm not sure it's just a names thing. Quests doesn't seem to be recognizing any 1.13 items even when setting up a new quest. For example, I can't have players deliver a trident or phantom membrane -- it gives an error message of "No item in hand!" even when I'm clearly holding the item. Entering "trident" or "minecraft:trident" results in an "Invalid item name!" error.

Using Quests 3.4.0 with git-Spigot-947a8e7-3a91182 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by FlyingPikachu** [comment] 2018-11-13 05:11
@mercurialmusic Although I was able to confirm that Trident isn't loading, this is entirely unrelated as Ender Stone (and many 1.13 items, such as Shield and Totem) load fine. Please open a new issue to explore the Trident bug.

**Closed by FlyingPikachu** 2018-11-13 05:11 UTC
Labels: bug, duplicate

**Comment by FlyingPikachu** [comment] 2018-11-13 05:13
I have closed this as there is no graceful way I could find to convert 1.13 names to 1.12, One should expect to have to do manual edits to quests.yml if downgrading.
