### ISSUE TITLE
Npc effects not working 1.13.1

### ISSUE THREAD

**Issue by Straiker123** [FlyingPikachu/Quests#542] opened 2018-12-01 16:02 UTC
3.4.4 b515

no errors

need help npc effect not working !

there is my config:

# See https://github.com/FlyingPikachu/Quests/wiki/Configuration
accept-timeout: 20
allow-command-questing: true
allow-command-quests-with-npcs: false
allow-quitting: true
ask-confirmation: true
generate-files-on-join: true
ignore-locked-quests: true
kill-delay: 600
language: cs-CZ
max-quests: 3
npc-effects:
  enabled: true
  new-quest: note
  redo-quest: angry_villager
show-requirements: true
show-titles: false
translate-items: false
translate-subcommands: false
use-compass: true

**Comment by FlyingPikachu** [comment] 2018-12-01 16:35
Use latest dev build - http://ci.ac3-servers.eu/job/Quests/522/

**Comment by FlyingPikachu** [comment] 2018-12-01 16:36
I see this is a duplicate of #539 

Please let me know if the build I linked above does not resolve the issue. Thanks for your patience.

**Closed** 2018-12-02 12:38 UTC
Labels: bug, duplicate
