### ISSUE TITLE
experience heroes can only be given class 1, please correct. what would the experience went for all classes.

### ISSUE THREAD

**Issue by robertlera** [FlyingPikachu/Quests#161] opened 2017-10-31 12:58 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?

(__Required__) Please describe the problem and how to replicate it. Any console errors?

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by FlyingPikachu** [comment] 2017-12-01 05:50
Duplicate of #109

**Closed by FlyingPikachu** 2017-12-01 05:50 UTC
