### ISSUE TITLE
"out of memory" Server crashes and spams "1"

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#179] opened 2017-12-10 00:09 UTC
Version:
3.1.2

My server crashes/stopps over and over. And i got alot of "1" in the console.

Here is a error from quests:

[15:11:20] [Server thread/WARN]: [Quests] Task #90 for Quests v3.1.2-b192 generated an exception
java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:3332) ~[?:1.8.0_101]
    at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137) ~[?:1.8.0_101]
    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121) ~[?:1.8.0_101]
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421) ~[?:1.8.0_101]
    at java.lang.StringBuilder.append(StringBuilder.java:136) ~[?:1.8.0_101]
    at me.blackvein.quests.Quests.getLocation(Quests.java:3397) ~[?:?]
    at me.blackvein.quests.Event.loadEvent(Event.java:347) ~[?:?]
    at me.blackvein.quests.Quests.processStages(Quests.java:3084) ~[?:?]
    at me.blackvein.quests.Quests.loadQuests(Quests.java:2061) ~[?:?]
    at me.blackvein.quests.Quests$1.run(Quests.java:197) ~[?:?]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-00128b5-6cb752e]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [craftbukkit.jar:git-Spigot-00128b5-6cb752e]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [craftbukkit.jar:git-Spigot-00128b5-6cb752e]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [craftbukkit.jar:git-Spigot-00128b5-6cb752e]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [craftbukkit.jar:git-Spigot-00128b5-6cb752e]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [craftbukkit.jar:git-Spigot-00128b5-6cb752e]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

**Comment by dcapape** [comment] 2017-12-10 13:15
Updating to 3.1.3 you don't get this message anymore, but Quests are not working in 3.1.3

**Comment by ScuroK** [comment] 2017-12-10 13:18
How you mean Quests are not working in 3.1.3

**Comment by dcapape** [comment] 2017-12-10 13:37
Read this:
https://github.com/FlyingPikachu/Quests/issues/175
https://github.com/FlyingPikachu/Quests/issues/176
https://github.com/FlyingPikachu/Quests/issues/177
https://github.com/FlyingPikachu/Quests/issues/178

**Comment by ScuroK** [comment] 2017-12-10 14:58
i guess i stick to the naomi-version untill its fixed..

**Comment by FlyingPikachu** [comment] 2017-12-10 17:51
Duplicate of #173

Use latest dev build to correct this issue.

**Closed by FlyingPikachu** 2017-12-10 17:51 UTC
