### ISSUE TITLE
Plugin doesn't display the full name of the items.

### ISSUE THREAD

**Issue by Ziomkeee** [FlyingPikachu/Quests#359] opened 2018-04-07 19:38 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest") 3.2.7?

(__Required__) Please describe the problem and how to replicate it. Any console errors?
If I add an item with a double ID (5: 3), it displays only the main name, not "jungle wood", which means that the player doesn't know what to bring.

**Comment by AIphaDragon** [comment] 2018-04-10 19:16
Same problem. If this is important, then on 3.2.0 everything displays normally.

**Comment by FlyingPikachu** [comment] 2018-04-11 02:44
@Ziomkeee Provide an example quest? I'm curious why you mention IDs when they aren't supported.

**Comment by Ziomkeee** [comment] 2018-04-11 04:27
@FlyingPikachu 
 - name-1:amount-64:data-5

It only displays that it's stone.

**Comment by FlyingPikachu** [comment] 2018-04-12 02:47
That's wrong and should be

`name-STONE:amount-64:data-5`

since item IDs are not allowed. Marking as duplicate of #346

**Closed by FlyingPikachu** 2018-04-12 02:47 UTC
