### ISSUE TITLE
mythicmobs issue

### ISSUE THREAD

**Issue by Elioz** [FlyingPikachu/Quests#90] opened 2015-04-17 01:40 UTC
Hi,

When i'm trying to create quest with stage to kill mythicmob, after the mob is died, nothing happend
the plugin is still support by the new version of Quests?

Thanks!

**Comment by Leescar** [comment] 2015-04-17 03:52
I don't recall mythic mobs ever being supported by quests. Its been requested a lot, would be lovely.

Instead a way to work around this is to simply set only the 'type' of mob you want killed.
Example:
I have a mythic mob called 'Ancient king' He is a skeleton boss mob so I set the 'mobs to kill' goal to 'skeleton'
Now you might be thinking that a player can go and kill any mythic mob just any old place right?
Well that's where the 'area' portion of 'mobs to kill' stage comes in. Setting the area they will get credit for the kill in only the area they will find the mob.

Straight to the point version:
Set mob type as the type of mob it is
set area to prevent issues
set radii 
set goal display override with 'kill mobnamehere' otherwise goal will display 'kill mobtypehere'

Complications:

Are you disguising a mob as another? Ie: zombie disguised as cow for a 'mad cow'. If you are you will have to set the mob-to-kill as zombie instead of cow. Might have to set the other way around, but im pretty sure that spot on if setting to the base mob-type undisguised doesn't give credit then select the disguise mob-type.

Are you letting regular mobs spawn in the same area? yes? well then you will have to tweak somehow, no? Your good to go.

Does your stage have more then the goal of killing the mob? Yes? Then you need to set goal display override accordingly. no? Your good to go.

**Comment by FlyingPikachu** [comment] 2015-04-17 12:35
There is no native support for MythicMobs. The creators of that plugin made an Addon for Quests, but there's no guarantee it still works: http://dev.bukkit.org/bukkit-plugins/mythicmobs/files/37-mythic-mobs-quests-v0-4/

@Leescar Your help is appreciated. Thanks! :)

**Comment by Elioz** [comment] 2015-04-18 06:06
@Leescar 
Thanks for the great answer!
By another issue is when mythicmob summon minions from the same type he is?

**Comment by Leescar** [comment] 2015-04-18 06:25
Hmm as far as a mob summoning minions of the same type the best way around this would be to have the stage set the player to kill the number of minions + the boss. Here are the various ways to help:

1. The simple and easy way would be to change the mob-type the mythicmob summons.
 so a skeleton boss would summon zombies. 
This can be a bit off-putting for player emersion and 'effect'  so I have other more complex solutions.

2. The next most simply way is lets say you have a skeleton boss that summons  6 skeletons you would set the stage goal to kill 7 skeletons.
The goal would become 'Kill mobnamehere and his/her minions"
 There is a big issue however with possible mobs killing each other, other players involved.

3. Another way to deal with it is to require the player to retrieve a custom drop from the boss or the mythic-mob.
 making the goal "Slay mobnamehere and retrieve the itemnamehere and bring it to me"
To do this you would create the mythicmob item as normal then use the mythicmob item give command to give yourself a copy of the item,
 then in quests stage 'deliver items to npc' you would load from hand the custom mythicmob item.

4 Using items we can also have another way of using them. 
Create a custom drop in mythicmobs then have that drop be an item with lore the player needs to say.
Lets say something silly like 'barsnuggle'
The quest would tell the player to 'kill mobnamehere and retrieve the artifact, once you retrieve it speak the magical spell to break my curse' 
Or some other way or getting the player to understand they need to kill the mob and get the item then speak the words. 
The stage would be a passphrase stage.
The drawbacks are once players communicate they could give away the phrase and negate any effort needed.

You can combine any of the above in many ways and there are even a few more ways I can think of, but it really depends on your playerbase and how far you think you need to go to make sure people play the quest and your server as intended.

**Comment by FlyingPikachu** [comment] 2015-04-30 01:55
Closing as there is no native support. If you would like to add support, please create a pull request. I am unfortunately unable to work on integrating other plugins at this time. Thanks!

**Closed by FlyingPikachu** 2015-04-30 01:55 UTC
