### ISSUE TITLE
The problem in the name of objects

### ISSUE THREAD

**Issue by AIphaDragon** [FlyingPikachu/Quests#352] opened 2018-03-31 20:52 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.7
(__Required__) Please describe the problem and how to replicate it. Any console errors?
The issue is shown on video. Thank you in advance for your help.
quests 3.2.0: https://youtu.be/upGL3z6fVao
quests 3.2.7: https://youtu.be/mKQ4z2N8hRc

**Comment by FlyingPikachu** [comment] 2018-04-11 04:03
Sorry, but I'm having trouble understanding the issue from your videos. What is the problem exactly?

**Comment by AIphaDragon** [comment] 2018-04-11 13:29
The problem is in displaying a name of items. In vesion 3.2.0 they were displaying a name, that an item actaully has. But in version 3.2.7 it just shows "Poppy", as with example on video. And such problem is with every item, which has metadata

**Comment by FlyingPikachu** [comment] 2018-04-12 03:28
Ok, I see what you're getting at. This is likely caused by the fix for #195 

Currently, item names are acquired through VaultAPI. Although this worked just fine in the past, that API has become generally unreliable (see #172 and #282). It is one of my current goals for the plugin to both  drop Vault as a requirement for Quests (and, therefore, stop using VaultAPI) as well as find a way to reliably translate item names to other languages.

All that said, although the issue you've brought up is on my list of things to fix, I have no estimate for when that will happen.

**Comment by AIphaDragon** [comment] 2018-04-12 09:09
Thanks for the answer. Will wait :)

**Comment by FlyingPikachu** [comment] 2018-12-01 08:10
VaultAPI is no longer used, so this should be resolved in recent versions of Quests.

**Closed by FlyingPikachu** 2018-12-01 08:10 UTC
Labels: bug
