### ISSUE TITLE
Errors  when stepping on pressure plates

### ISSUE THREAD

**Issue by datsme** [FlyingPikachu/Quests#596] opened 2018-12-29 19:15 UTC
This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Quests: v3.5.7-b573

When I step on a pressure plate (creative or survival) my control panel spams "ERROR Could not pass event PlayerInteractEvent to Quests v3.5.7-b573"  

Pastebin[ Link ](https://pastebin.com/NGCq9bzG)to error log

**Comment by FlyingPikachu** [comment] 2018-12-29 22:37
Duplicate of #594 

Just pushed a commit which should resolve the issue. Try...

http://ci.ac3-servers.eu/job/Quests/578/

...once available. If issue persists, post new error in #594.

**Closed by FlyingPikachu** 2018-12-29 22:37 UTC

**Comment by datsme** [comment] 2018-12-30 01:57
Looks like that fixed it thanks!
