### ISSUE TITLE
Error When Players Join

### ISSUE THREAD

**Issue by HyperFierce** [FlyingPikachu/Quests#327] opened 2018-03-04 07:07 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")? 3.2.5 But I also used 3.2.2 and received the same error.

(__Required__) Please describe the problem and how to replicate it. Any console errors? When a player logs in I receive at least 3 different errors on my console and player is not able to do /quest because of internal error.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/1KX6d0b0

This is the error I receive: Notice there are multiple.
https://pastebin.com/XFM9TvaT

**Comment by Trigary** [comment] 2018-03-05 15:17
This issue is a duplicate of #311, but it provides more information.

**Comment by Trigary** [comment] 2018-03-05 15:42
The error is in [this line](https://github.com/FlyingPikachu/Quests/blob/master/src/main/java/me/blackvein/quests/Quester.java#L1965). The `LinkedList<E>#set(int, E)` method is used, despite the `LinkedList` being empty. This causes an `IndexOutOfBoundsException`, which can be reproduced by running this line of code: `new LinkedList<>().set(0, new Object());` The `LinkedList<E>#add(E)` method should be used instead.

**Closed** 2018-03-05 23:14 UTC
Labels: bug
