### ISSUE TITLE
Events Mob Spawn Crash

### ISSUE THREAD

**Issue by hwathi** [FlyingPikachu/Quests#124] opened 2017-09-03 04:01 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.0.5  (also had it with 3.0, upgraded to latest dev build to see if fixed)

(__Required__) Please describe the problem and how to replicate it. Any console errors?
When adding a new event that spawns mobs, the menus stop responding and a crash shows up on the server console after doing Add Mob then selecting Done.

[22:54:03 ERROR]: Error handling conversation prompt
java.lang.NullPointerException: null
        at me.blackvein.quests.Quests.getLocationInfo(Quests.java:3440) ~[?:?]
        at me.blackvein.quests.EventFactory$MobPrompt.getPromptText(EventFactory
.java:1479) ~[?:?]
        at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.j
ava:291) ~[spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:2
30) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at org.bukkit.craftbukkit.v1_12_R1.conversations.ConversationTracker.acc
eptConversationInput(ConversationTracker.java:58) [spigot-1.12.1.jar:git-Spigot-
65e8124-79e55b6]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.acceptConversation
Input(CraftPlayer.java:1068) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.PlayerConnection$5.evaluate(PlayerConne
ction.java:1235) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) [
spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:
758) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:
406) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:
679) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.jav
a:577) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]

**Comment by hwathi** [comment] 2017-09-05 03:52
Update:
This issue did in fact go away when I renamed my world from "Towns 1" to "Towns1" removing the space in the name.

**Comment by FlyingPikachu** [comment] 2017-09-05 05:04
This should have been fixed in #100

Hope to take a look soon

**Comment by FlyingPikachu** [comment] 2017-12-05 03:39
It seems the issue is only caused by world names containing a space AND a single number by itself. So, while "Towns 1" causes an issue, "Towns 1a" does not. This is because in "Towns 1" the number is being interpreted as the start of location coordinates.

Dev build version 3.0.9 should fix this.  Thanks!

**Closed** 2017-12-05 03:38 UTC
Labels: bug
