### ISSUE TITLE
Cannot Return Items to npc I get an error in console.

### ISSUE THREAD

**Issue by Biscoot1** [FlyingPikachu/Quests#131] opened 2017-09-05 12:36 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")? Quests - 3.0.0-Naomi

(__Required__) Please describe the problem and how to replicate it. Any console errors? Yes, This is the error produced when making the Quest make the user deliver and I selected "Done" beacause it doesn't bring back the previous menu.
https://hastebin.com/fulerinixu.vbs

Error # 2 produced when I complete the first stage. (killing 5 pigs) Then it doesn't show the next stage which is setup to be giving the NPC 5 Raw Pork.
https://hastebin.com/ugaluqezan.vbs

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
My quests.yml doesn't update from creating quests in-game

**Comment by FlyingPikachu** [comment] 2017-09-06 03:05
@Biscoot1 What is your Vault version?

Possible duplicate of #123

**Comment by Biscoot1** [comment] 2017-09-06 17:29
1.6.1

**Comment by Biscoot1** [comment] 2017-09-06 17:31
I have now got it to where no error come up in console. But when I try to return the items they leave my inventory and the quest doesn't complete.

**Comment by Biscoot1** [comment] 2017-09-07 06:06
So I have tested around. As soon as i got over 2 Tasks/Stages, It gives me this -[http://prntscr.com/gi3ezm]- and then doesn't tell me the next task/stage

**Comment by FlyingPikachu** [comment] 2017-10-01 02:49
Confirmed duplicate of #123, which will be addressed shortly. Feel free to open another issue for your new problem. Thanks!

**Closed by FlyingPikachu** 2017-10-01 02:49 UTC
