### ISSUE TITLE
Console spammed with error

### ISSUE THREAD

**Issue by Jordan44** [FlyingPikachu/Quests#4] opened 2015-02-08 19:59 UTC
Using the latest version of Quests, my console is being spammed by this error continuously.

http://pastebin.com/amsqj4JR

**Comment by FlyingPikachu** [comment] 2015-02-09 02:54
Would you mind uploading your Quests/data folder?

**Comment by Jordan44** [comment] 2015-02-09 20:34
https://www.dropbox.com/s/r68fh3cnku8ry61/Quests.zip?dl=0

**Comment by FlyingPikachu** [comment] 2015-02-10 00:37
Please try setting 'generate-files-on-join' to 'false' in your config.yml. If that resolves the problem, post back and I'll issue a fix.

**Comment by SimbaZockt** [comment] 2015-02-10 01:12
Fix: Just recreate all files or remove the player data only! :)

**Comment by Jordan44** [comment] 2015-02-10 15:02
Tried setting generate files to false, and the new update, to no avail. Perhaps I should remove the player data as SimbaZockt said? The issue only started happening after the conversion to UUIDs.

**Comment by FlyingPikachu** [comment] 2015-02-12 01:02
I'm stumped, so feel free to give it a shot. I would recommend keeping that backup just in-case.

**Comment by Mick43** [comment] 2015-02-14 09:02
i have the same probleme with the reach location, can you fix that's ?

**Comment by Mick43** [comment] 2015-02-15 17:49
![capture](https://cloud.githubusercontent.com/assets/10450256/6204223/6594a086-b543-11e4-9bd5-d7a37c599056.PNG)

**Comment by FlyingPikachu** [comment] 2015-02-15 18:20
@Mick43 That is a different error (albeit similar). Please open a new issue.

**Comment by Jordan44** [comment] 2015-02-15 19:52
Well I reset my data and a couple of days later the error came back...

**Comment by FlyingPikachu** [comment] 2015-02-15 23:50
Sorry to hear that. Your original pastebin got removed, would you mind posting the "new" error?

**Comment by FlyingPikachu** [comment] 2015-02-18 15:20
Proceeding with the error from @Mick43 as the OP's error is gone.

**Comment by FlyingPikachu** [comment] 2015-02-21 16:04
Please try this dev build as a potential fix for this issue: http://ci.ac3-servers.eu/job/Quests/34/

**Comment by Mick43** [comment] 2015-02-24 13:06
I have the spam error console with the last build:

[Server thread/ERROR]: Could not pass event PlayerJoinEvent to Quests v2.2.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.PlayerList.onPlayerJoin(PlayerList.java:272) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.PlayerList.a(PlayerList.java:156) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:109) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:800) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at java.lang.Thread.run(Thread.java:722) [?:1.7.0]
Caused by: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at me.blackvein.quests.PlayerListener.onPlayerJoin(PlayerListener.java:838) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0]
	at java.lang.reflect.Method.invoke(Method.java:601) ~[?:1.7.0]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	... 14 more

**Comment by FlyingPikachu** [comment] 2015-02-24 22:53
@Mick43 That is, again, a different error while similar. However, the latest commit, and thus the latest dev build, *should* fix that error. If not, please open a new ticket! :)

Closing as OP has not responded to request for "new" error.

**Closed by FlyingPikachu** 2015-02-24 22:53 UTC
