### ISSUE TITLE
kill players in certain region.

### ISSUE THREAD

**Issue by sahudon** [FlyingPikachu/Quests#99] opened 2017-08-11 15:08 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 3.0.0-Naomi-b${env.BUILD_NUMBER}
(__Required__) Please describe the problem and how to replicate it. Any console errors?
i cant do a mision with players kill others only count in certain region,when you kill a player count in everywhere
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
custom47:
    name: 'example'
    npc-giver-id: 26
    ask-message: kill 10 players in waterfall-cave
    finish-message: excelent.
    gui-display: name-DIAMOND_SWORD:amount-1
    stages:
      ordered:
        '1':
          locations-to-kill:
          - world -161.0 42.0 168.0
          kill-location-radii:
          - 30   
          kill-location-names:

**Comment by FlyingPikachu** [comment] 2017-08-11 15:26
Duplicate of #96

**Comment by ghacproductions** [comment] 2017-08-22 19:21
@FlyingPikachu Are you sure this is a duplicate? https://github.com/FlyingPikachu/Quests/issues/96 describes a bug whereas this issue is rather a feature-request than a bug-report. Maybe I'm wrong, but please check this again.

**Comment by FlyingPikachu** [comment] 2017-08-26 02:21
@ghacproductions Possible I interpreted OP wrong. However, in the event @sahudon is requesting the ability to track players killed in a region, this is already possible as kill-location-names and assoc. stage settings (see https://github.com/FlyingPikachu/Quests/wiki/Configuration).

I'm closing this because #96 has been closed and the aforementioned request would be invalid.

**Comment by ghacproductions** [comment] 2017-08-26 11:30
@FlyingPikachu The wiki says that the option "kill-location-names" is required if "locations-to-kill" is set. However, regarding the wiki, this options contains
`World and coordinates that the mobs need to be killed at. Format is "worldName x y z".`
This option, at least according to the wiki, is only applicable for _mobs_, not for _players_. Is there an other option that tracks players instead of mobs?

**Comment by FlyingPikachu** [comment] 2017-08-26 13:49
I could've sworn it could be used for players, or that a similar functionality was available. Will take a look at that soon, thanks!

Will reopen if @sahudon clarifies his request.

**Comment by sahudon** [comment] 2017-08-26 20:24
I want the assassinations of the mission to count if the player kills another within a specific region but does not detect it and no matter the place that is account for the same mission

**Comment by FlyingPikachu** [comment] 2017-08-26 21:25
@sahudon Should the "assassination" be detected if the _killer_ dies in a region, if the _target_ dies in a region, or if they are _both_ in a region?

**Comment by FlyingPikachu** [comment] 2017-08-27 05:40
So it's if the _killer_ does in a region. Ok, hope to look into this soon!

**Comment by ghacproductions** [comment] 2017-08-27 17:06
@FlyingPikachu Whats the point of tracking the deaths of the killer? It should either be the location of the killer OR the location of the target, I don't know how the killer should die at all, as he is the killer and not the target.

**Comment by FlyingPikachu** [comment] 2017-08-28 18:42
Seems I confused myself. Meant to write "if the _target_ dies" in my last comment.

Anyway, I was able to set "Player" as an option in mobs-to-kill (which I guess makes the players-to-kill option redundant...). Here's what it looks like in quests.yml

>stages:
      ordered:
        '1':
          mobs-to-kill:
          - Player
          mob-amounts:
          - 2
          locations-to-kill:
          - world -499.0 3.0 779.0
          kill-location-radii:
          - 30
          kill-location-names:
          - BattleArena

That will allow @sahudon to track player kills in a certain region as requested. I also believe that this requires that the _target_ be in the region regardless of whether the _killer_ is, as desired.

**Closed by FlyingPikachu** 2017-08-28 18:42 UTC
Labels: bug, duplicate, enhancement, invalid
