### ISSUE TITLE
Quest Delays Avoidable

### ISSUE THREAD

**Issue by Neoblade298** [FlyingPikachu/Quests#112] opened 2015-05-09 06:59 UTC
I'm not sure if this has been reported before, sorry if it has:

If a player logs out immediately after finishing a quest, he can bypass the delay for the quest.

To recreate:
1. Create a quest with a delay of 3600, for purpose of example
2. Complete whatever the quest is
3. Log off and on immediately after completing the quest
4. Try getting the quest again

I believe this issue was actually fixed in Blackvein's quest before you took over, because I do remember this issue not being a problem.

**Comment by FlyingPikachu** [comment] 2015-05-09 14:03
Duplicate of #67, please contribute there. Thanks!

**Closed by FlyingPikachu** 2015-05-09 14:03 UTC
