### ISSUE TITLE
Save Quests error

### ISSUE THREAD

**Issue by waiching514** [FlyingPikachu/Quests#655] opened 2019-01-26 05:14 UTC
When I type "Yes" to save,It not work and have error: https://pastebin.com/KJaaSWHQ

Quests 3.6.0

**Comment by FlyingPikachu** [comment] 2019-01-26 05:34
Thanks for your report. This appears to be a duplicate of #641 

May I ask what type of quest you were trying to create (Block Break, Deliver Item, etc.)?

**Comment by waiching514** [comment] 2019-01-26 05:39
Deliver Item

**Comment by FlyingPikachu** [comment] 2019-01-26 22:15
@waiching514 Please give the following build a try once available. It may or may not resolve the issue:
http://ci.ac3-servers.eu/job/Quests/632/

**Comment by waiching514** [comment] 2019-01-27 00:45
It is also having error: https://pastebin.com/jn8mT2ik

**Comment by waiching514** [comment] 2019-01-27 04:32
It is fixed now

**Comment by waiching514** [comment] 2019-01-27 04:43
But When I saved and reload, It having error: https://pastebin.com/CUMVHBEs
And Quest is work But item reward not work

**Closed** 2019-01-27 05:14 UTC
Labels: bug, duplicate

**Comment by FlyingPikachu** [comment] 2019-01-27 05:16
@waiching514 Glad to hear it! For that new error, try the following build once available:
http://ci.ac3-servers.eu/job/Quests/634/

If it still gives you problems, open a new ticket (since it's a now a different issue). Thanks!
