### ISSUE TITLE
Item Delivery Event Broken

### ISSUE THREAD

**Issue by Kizuuna** [FlyingPikachu/Quests#355] opened 2016-06-23 22:50 UTC
Once you deliver the item you have set the quest will stop working. In /quest it will tell you, delievered 1/1 items and the quest will not complete, nor will it move over to the next event.

**Comment by Kizuuna** [comment] 2016-06-23 23:04
Have this issue when I downgraded to 2.5.5???

**Comment by Kizuuna** [comment] 2016-06-23 23:13
Actually I have tested this multiple times and only some items cause it to break. I only realized this midway through my testing however, this item will cause the quest to break at deliver.

Id: 399 Name:&aMythical Gem Lore: &7Used to craft great weapons!

Tested 2.6.5 , 2.5.5

Possible that items with Lore's may cause the quest to break. Otherwise I do not know.

**Comment by Kizuuna** [comment] 2016-06-23 23:26
Nope its just that item. I even removed the lore. Still having that problem on both 2.6.5 and 2.5.5 I guess I'll have to change the item to a diamond or something and change the name.

**Comment by Kizuuna** [comment] 2016-06-23 23:44
Fixed by renaming the item, changing the item type, and removing the lore.

Bug is still unknown.

High possibility that the Nether Star is not supported in delivery.

**Comment by FlyingPikachu** [comment] 2016-06-24 01:24
Duplicate of #297

**Closed by FlyingPikachu** 2016-06-24 01:24 UTC
