### ISSUE TITLE
Cannot quit a player's quest - Internal Error Command

### ISSUE THREAD

**Issue by whoshenry** [FlyingPikachu/Quests#130] opened 2015-06-02 20:52 UTC
I get this error sometimes when I quit a player's quest for them - http://pastebin.com/CzQMruQ0

I am trying to quit that quest for them because they get this occasionally when they do /quest - http://pastebin.com/rAXgBCEh

I'm not entirely sure how or why this occurs either.

**Comment by whoshenry** [comment] 2015-06-04 14:26
I have some more info on this. It just happened to a player. 

He had this Quest active - http://pastebin.com/jrK4e9Hm

Then tried to quit it and then got this error when he did /quest - http://pastebin.com/3s6XQm8R

I am using Quests Version 'Quests-2.5.0-b81' on Spigot version - CraftBukkit version git-Spigot-044d928-e8c6403 (MC: 1.8.6) (Implementing API version 1.8.6-R0.1-SNAPSHOT)

**Comment by whoshenry** [comment] 2015-06-05 16:40
I have some more information on this that I found today. When this happens to a player, to solve the problem, I do /questsadmin quit <player> <quest> and sometimes, this works and it is fixed, they can do /quest again without an error.

Other times, I have to do /questsadmin quit <player> <quest> then an internal error command would occur, then they would leave, when they rejoin, I do the same command again and it would work.

Also, when this happens and a player is unable to do /quest they are able to actually take the GUI Items out of the NPC GUIS and have it in their inventory.

**Comment by FlyingPikachu** [comment] 2015-06-06 11:53
Could you post another example of the first error, from quitting? There should be a few lines after "Caused by: java.lang.NullPointerException" that are important.

**Comment by whoshenry** [comment] 2015-06-06 14:20
Just tried it, this is all I got in the console. Even with debugging enabled. - http://pastebin.com/6fjzGpqb

**Comment by whoshenry** [comment] 2015-06-06 14:35
Ok here's a good copy of what is happening. The first player 'GameLovesOreos' had the /quest internal error command. So I tried, via the console, to quit one of this quests and got this error - http://pastebin.com/BBKaqQms

As you can see this particular error has also happened to another player on the server with different quests. It is happening often.

**Comment by FlyingPikachu** [comment] 2015-06-07 02:54
@whoshenry I added something which should cause the full error to print. Please try dev build 85 once it's up and try again! :)

http://ci.ac3-servers.eu/job/Quests/85/

**Comment by whoshenry** [comment] 2015-06-07 11:11
Still getting this error on that Dev Build - http://pastebin.com/1ucRxyaZ

And here is the Quest quit error - http://pastebin.com/i6H1nTnR

**Comment by whoshenry** [comment] 2015-06-07 11:31
For some reason, when I started up this latest Dev Build. One of my players' Quests Data was wiped. His Quest Points stayed, but all of his Completed Quests have disappeared somehow...

**Comment by FlyingPikachu** [comment] 2015-06-07 15:14
I'm only interested in the error from using /questadmin quit, but thank you for the additional info. Any unexpected behavior after that, such as the data wipe, is going to be the result of the command issue. As such, I'll close #136 and try to avoid using the command regularly until I can kill the bug. Thanks!

**Comment by whoshenry** [comment] 2015-06-07 15:16
I only use the quit command when someone has the internal error command, only way to fix that for them unfortunately cos they can't do anything whilst they have that. No NPCs accept the item deliveries either.

**Comment by FlyingPikachu** [comment] 2015-06-07 15:30
Oh I see. In that case we should investigate the internal error command. I'll take a look at that next then.

I've uploaded a test fix so at least /questadmin quit *might* work, it'll be dev build 86 if you'd like to try it.

**Comment by whoshenry** [comment] 2015-06-07 15:31
Yeah it's a pretty major bug, and it happens often too. I will test that dev build now, thanks for the quick fixes :)

**Comment by whoshenry** [comment] 2015-06-07 21:41
Ok so I have been using the Dev Build 86 and still get the same error often with the internal error command, but /questsadmin quit seems to work. Haven't had an occasion where it doesn't yet.

Also, this just popped up and it might be the same sort of error or something due to the internal error command - http://pastebin.com/qAwHwGWf

Also when the internal error command happens for a player, they can take the GUI items showing the Quest with the ask-message out of the NPCs menu.

**Comment by FlyingPikachu** [comment] 2015-06-08 00:56
@whoshenry To clarify - /questadmin quit no longer produces a console error?

**Comment by whoshenry** [comment] 2015-06-08 10:08
I have not experienced a console error when doing that command using the Dev Build, no.

**Comment by FlyingPikachu** [comment] 2015-06-09 19:45
Please try /quest on dev build 87. Should still cause an error, but also give us some additional information.

I'd run this myself but /quest works perfectly for me.

http://ci.ac3-servers.eu/job/Quests/

**Comment by whoshenry** [comment] 2015-06-10 10:29
I am running this version now, will let you know what I find with the errors.

**Comment by whoshenry** [comment] 2015-06-10 11:15
Ok it just happened, here's the error - http://pastebin.com/LbdhXPiX

**Comment by FlyingPikachu** [comment] 2015-06-11 14:32
Okay, dev build 88 *may* resolve the errors, although there will still be debug output. Please post your results and thanks for testing.

http://ci.ac3-servers.eu/job/Quests/

**Comment by whoshenry** [comment] 2015-06-11 21:43
Fantastic, been using it for the last 4 hours and not one person has mentioned having the error, there are other errors in the console though, but I think they are unrelated to this one. Just some random NPCRightClickEvent errors etc. They probably refer to other issues posted here.

**Comment by FlyingPikachu** [comment] 2015-06-12 01:33
@whoshenry Just debug, I'll remove them soon if the fix continues to work. Is there any particular quest that returns null or is it seemingly random?

**Comment by whoshenry** [comment] 2015-06-12 07:24
I've seen about 6 Quests so far that do it, they can be completed correctly, so perhaps it's just random.

**Comment by whoshenry** [comment] 2015-06-12 07:27
I just had another issue with this, a player said he was receiving an error when doing /quest (whether this was before I uploaded the Dev build or not, I don't know). But I tried doing /sudo <name> quest and it said there was an error making him do that command, I took a look in the console and got this - http://pastebin.com/fVRCakjj

**Comment by whoshenry** [comment] 2015-06-12 10:27
Unfortunately, it just happened to one player, and this is the result in the Console - http://pastebin.com/dBY7YGa3

**Comment by FlyingPikachu** [comment] 2015-06-13 03:33
Removed the debug messages as well as took another approach to suppress the errors. Hopefully that works!

**Comment by whoshenry** [comment] 2015-06-14 07:07
Seems like it's all working correctly but I will still be testing it. I am also still getting this error - http://pastebin.com/FyutSyVN

**Comment by FlyingPikachu** [comment] 2015-07-08 20:03
Closing as initial issue has been solved and final error is not descriptive enough (there should be more info after the NullPointerException). If you get an error containing more information, please open a new ticket. Thanks!

**Closed by FlyingPikachu** 2015-07-08 20:03 UTC
