### ISSUE TITLE
Quests do not enable after update, caused by IllegalArgumentException

### ISSUE THREAD

**Issue by masterstreamer** [FlyingPikachu/Quests#246] opened 2018-01-16 09:20 UTC
Quests v3.2.1-b235

Quests are not working, getting this error on server startup

`[Quests] Enabling Quests v3.2.1-b235
[10:15:07] [Server thread/ERROR]: Error occurred while enabling Quests v3.2.1-b235 (Is it up to date?)
java.lang.IllegalArgumentException: character to be escaped is missing
	at java.util.regex.Matcher.appendReplacement(Unknown Source) ~[?:1.8.0_151]
	at java.util.regex.Matcher.replaceAll(Unknown Source) ~[?:1.8.0_151]
	at java.lang.String.replaceAll(Unknown Source) ~[?:1.8.0_151]
	at me.blackvein.quests.Quests.saveResourceAs(Quests.java:242) ~[?:?]
	at me.blackvein.quests.Quests.setupLang(Quests.java:219) ~[?:?]
	at me.blackvein.quests.Quests.onEnable(Quests.java:185) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot_server.jar:git-Spigot-109b080-ab09b27]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot_server.jar:git-Spigot-109b080-ab09b27]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot_server.jar:git-Spigot-109b080-ab09b27]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot_server.jar:git-Spigot-109b080-ab09b27]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot_server.jar:git-Spigot-109b080-ab09b27]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot_server.jar:git-Spigot-109b080-ab09b27]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot_server.jar:git-Spigot-109b080-ab09b27]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot_server.jar:git-Spigot-109b080-ab09b27]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot_server.jar:git-Spigot-109b080-ab09b27]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot_server.jar:git-Spigot-109b080-ab09b27]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]`

**Comment by FlyingPikachu** [comment] 2018-01-21 07:33
Duplicate of #239 which has already been fixed. Update to dev build 236

**Closed by FlyingPikachu** 2018-01-21 07:33 UTC
