### ISSUE TITLE
Quests aren't saving

### ISSUE THREAD

**Issue by Alppuccino** [FlyingPikachu/Quests#89] opened 2017-07-31 21:13 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 2.9.7
(__Required__) Please describe the problem and how to replicate it. Any console errors?
When we edit a quest or create a new one, the quests do not save whatsoever. I looked for what you told me to look for before in the config but couldn't find it.
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/QUHdWZGz

**Comment by FlyingPikachu** [comment] 2017-08-01 02:18
Closing as invalid as you did not fix your quests.yml as requested in #80 

To be more specific, go to line 292 in your Pastebin. Change the "1" to a "0"

**Closed by FlyingPikachu** 2017-08-01 02:18 UTC

**Comment by Alppuccino** [comment] 2017-08-01 13:02
I did that and it still happens :(

**Comment by FlyingPikachu** [comment] 2017-08-01 17:57
Because there are more problems with your file. For example, starting at line 546, durability of "4" and "5" are not valid for LOG (if you want Spruce/Birch/Jungle logs, I think you need LOG_2). You can find more information about that on the Wiki - https://github.com/FlyingPikachu/Quests/wiki/Item-Formatting

Regardless, I'm not going to fix your file for you, as this was caused by user error and I don't have the time. I am, however, trying to see if Quests can fix it automatically (as I mentioned in #80), but this is easier said than done - https://www.spigotmc.org/threads/validate-block-damage.260467/

If you need further assistance, please try asking on the Spigot forums. Thanks!
