### ISSUE TITLE
Module "Kill MythicMobs Objective" is loaded AFTER Quests ...

### ISSUE THREAD

**Issue by tiradorus** [FlyingPikachu/Quests#642] opened 2019-01-17 01:08 UTC
**What is your Quests version / build number (do _not_ say "latest")?**

- Quests 3.6.0-b610
- Minecraft 1.8.8

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

When you reload the server, all quests with custom modules like mythicMobs doesn't work. But, if you do a /questadmin reload, then all quests works.

It's a bit a huge problem, if server is restarting (for updates or anything else), then all quests with custom objectives are bugged
If like me you have a remanent reload at 4AM, then all quests are bugged every morning.
If server is crashing, for any reasons, have an auto-restart, then all quests are bugged.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

Every quests with the Module: "MythicMobsQuests"
I don't have tried with other modules, i don't have any.

But, it looks like the quests are loaded before the modules:

01:48:37: [Quests] Custom objective "Kill MythicMobs Objective" for Stage 2 of Quest "Une île noire" could not be found!
01:48:37: [Quests] Custom objective "Kill MythicMobs Objective" for Stage 1 of Quest "Test" could not be found!
01:48:37: [Quests] 88 Quest(s) loaded.
01:48:37: [Quests] 49 Event(s) loaded.
01:48:37: [Quests] 858 Phrase(s) loaded.
01:48:37: [Quests] Loaded Module: Class Attribute Requirement by Eniripsa96
01:48:37: [Quests] Loaded Module: Class Attribute Points Reward by Eniripsa96
01:48:37: [Quests] Loaded Module: Class Experience Reward by Eniripsa96
01:48:37: [Quests] Loaded Module: Class Level Requirement by Eniripsa96
01:48:37: [Quests] Loaded Module: Class Level Requirement by Eniripsa96
01:48:37: [Quests] Loaded Module: Class Requirement by Eniripsa96
01:48:37: [Quests] Loaded Module: Class Reward by Eniripsa96
01:48:37: [Quests] Loaded Module: Class Skill Points Reward by Eniripsa96
01:48:37: [Quests] Loaded Module: Class Level Requirement by Eniripsa96
01:48:37: [Quests] Loaded Module: MythicMobs Item Reward by BerndiVader
01:48:37: [Quests] Loaded Module: MythicMobs Item Require by BerndiVader, idea Wahrheit
01:48:37: [Quests] Loaded Module: MythicItem NPC Deliver Objective by BerndiVader, idea Wahrheit
01:48:37: [Quests] Registered events for custom objective "MythicItem NPC Deliver Objective"
01:48:37: [Quests] Loaded Module: Kill MythicMobs Objective by BerndiVader
01:48:37: [Quests] Registered events for custom objective "Kill MythicMobs Objective"
01:48:37: [Quests] Loaded Module: MythicMobs Conditions Require by BerndiVader, idea Wahrheit

**Comment by FlyingPikachu** [comment] 2019-01-17 03:05
Technically duplicate of #631 but I'll leave this open since it's a different plugin/module

**Comment by frost-byte** [comment] 2019-01-17 08:22
I'm having the same issue with 3.6.0-b611

```
[03:13:33 INFO]: [Quests] Loading Quests v3.6.0-b611
...
[03:13:59 WARN]: [Quests] Custom objective "NPC Command Objective" for Stage 1 of Quest "Around Town" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "NPC Command Objective" for Stage 2 of Quest "Around Town" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "NPC Command Objective" for Stage 3 of Quest "Around Town" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 4 of Quest "Around Town" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 5 of Quest "Around Town" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 6 of Quest "Around Town" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Claim Create Objective" for Stage 1 of Quest "Homies on the Range" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Claim Visualize Objective" for Stage 2 of Quest "Homies on the Range" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 3 of Quest "Homies on the Range" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Claim Modify Objective" for Stage 4 of Quest "Homies on the Range" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 5 of Quest "Homies on the Range" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 6 of Quest "Homies on the Range" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 7 of Quest "Homies on the Range" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 8 of Quest "Homies on the Range" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 2 of Quest "Shop til you Drop" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 3 of Quest "Shop til you Drop" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Interaction Objective" for Stage 4 of Quest "Shop til you Drop" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Interaction Objective" for Stage 5 of Quest "Shop til you Drop" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 6 of Quest "Shop til you Drop" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Interaction Objective" for Stage 7 of Quest "Shop til you Drop" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 1 of Quest "Are you Challenging Me?" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 2 of Quest "Are you Challenging Me?" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Interaction Objective" for Stage 3 of Quest "Are you Challenging Me?" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 4 of Quest "Are you Challenging Me?" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 5 of Quest "Are you Challenging Me?" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 6 of Quest "Are you Challenging Me?" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Check Shopkeeper Inventory Objective" for Stage 1 of Quest "Hey Big Spender!" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Shopkeeper Trade Objective" for Stage 2 of Quest "Hey Big Spender!" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Shopkeeper Trade Objective" for Stage 8 of Quest "Hey Big Spender!" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Check Shopkeeper Inventory Objective" for Stage 9 of Quest "Hey Big Spender!" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Check Shopkeeper Inventory Objective" for Stage 10 of Quest "Hey Big Spender!" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 1 of Quest "Status Update!" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 2 of Quest "Status Update!" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Interaction Objective" for Stage 3 of Quest "Status Update!" could not be found!
[03:13:59 WARN]: [Quests] Custom objective "Command Completed Objective" for Stage 4 of Quest "Status Update!" could not be found!
[03:13:59 INFO]: [Quests] 17 Quest(s) loaded.
[03:13:59 INFO]: [Quests] 24 Event(s) loaded.
[03:13:59 INFO]: [Quests] 858 Phrase(s) loaded.
[03:13:59 INFO]: [Quests] Loaded Module: Check Shopkeeper Inventory Objective by beerye3
[03:13:59 INFO]: [Quests] Registered events for custom objective "Check Shopkeeper Inventory Objective"
[03:13:59 INFO]: [Quests] Loaded Module: Claim Create Objective by beerye3
[03:13:59 INFO]: [Quests] Registered events for custom objective "Claim Create Objective"
[03:13:59 INFO]: [Quests] Loaded Module: Claim Modify Objective by beerye3
[03:13:59 INFO]: [Quests] Registered events for custom objective "Claim Modify Objective"
[03:13:59 INFO]: [Quests] Loaded Module: Claim Visualize Objective by beerye3
[03:13:59 INFO]: [Quests] Registered events for custom objective "Claim Visualize Objective"
[03:13:59 INFO]: [Quests] Loaded Module: Command Completed Objective by beerye3
[03:13:59 INFO]: [Quests] Registered events for custom objective "Command Completed Objective"
[03:13:59 INFO]: [Quests] Loaded Module: Interaction Objective by beerye3
[03:13:59 INFO]: [Quests] Registered events for custom objective "Interaction Objective"
[03:13:59 INFO]: [Quests] Loaded Module: NPC Command Objective by beerye3
[03:13:59 INFO]: [Quests] Registered events for custom objective "NPC Command Objective"
[03:13:59 INFO]: [Quests] Loaded Module: Shopkeeper Trade Objective by beerye3
[03:13:59 INFO]: [Quests] Registered events for custom objective "Shopkeeper Trade Objective"
```

**Closed** 2019-01-17 19:53 UTC

**Comment by FlyingPikachu** [comment] 2019-01-17 19:56
On closer inspection, this is not a duplicate, but rather the result of a change I made to try fixing #631 

Essentially, I delayed the loading of modules without delaying the loading of their config sections. I've pushed a commit which resolves that - I tested it with the MagicQuests module. Use this build: http://ci.ac3-servers.eu/job/Quests/614/

Please defer further comments on the matter to #631 (do not open a new issue).
