### ISSUE TITLE
Problems with title

### ISSUE THREAD

**Issue by AIphaDragon** [FlyingPikachu/Quests#262] opened 2018-01-27 16:46 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Version - 3.1.6

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Hello! At the beginning / end of the quest, we made it possible to display the title. The problem is that each time we display messages in the console and in the game, as administrators. How can I remove it? Thanks in advance for your help.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
Config: https://pastebin.com/2AKvpQVx
Screen: https://imgur.com/a/Xx7O5

**Comment by FlyingPikachu** [comment] 2018-01-27 18:16
Run `/gamerule sendCommandFeedback false` to stop these messages. Duplicate of #166

**Closed by FlyingPikachu** 2018-01-27 18:16 UTC
