### ISSUE TITLE
Quests couldn't detect the paperspigot's version correctly

### ISSUE THREAD

**Issue by smartmadio** [FlyingPikachu/Quests#522] opened 2018-11-15 13:35 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
3.4.2

Please describe the problem and how to replicate it. Any console errors?
Just move to any npc that bind to quests.
>`[Server thread/WARN]: [Quests] Task #293 for Quests v3.4.2-b500 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class me.blackvein.particles.Eff_1_13_R1
	at me.blackvein.quests.NpcEffectThread.showEffect_1_13_R1(NpcEffectThread.java:224) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:70) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:54) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1587]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1587]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1587]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1587]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1587]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1587]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]`

**Server version:**
Paperspigot 1.12.2

Seems quests couldn't detect the paperspigot's version correctly?

**Comment by FlyingPikachu** [comment] 2018-11-16 04:07
PaperSpigot is not officially supported.

It's likely you can avoid this error by setting `npc-effects.enabled: false` in your config.yml

**Comment by smmmadden** [comment] 2018-11-16 13:04
That's news to me @FlyingPikachu - I've been using PaperSpigot for a while now.  It is a direct replacement for Spigot that requires no changes and comes with more performance improvements.

**Comment by FlyingPikachu** [comment] 2018-11-20 03:30
Although PaperSpigot is not supported, recent open issues seem to indicate that this issue is not specific to PaperSpigot. As such, I'm reopening this issue.

The aforementioned fix is still recommeneded for the time being.

**Comment by FlyingPikachu** [comment] 2018-11-20 03:34
Marking as duplicate of #516

**Comment by FlyingPikachu** [comment] 2018-11-28 22:35
This build should resolve the issue once available - http://ci.ac3-servers.eu/job/Quests/510/

**Closed by FlyingPikachu** 2018-11-28 22:35 UTC
Labels: bug, duplicate
