### ISSUE TITLE
AutoSave

### ISSUE THREAD

**Issue by SwimUp29** [FlyingPikachu/Quests#271] opened 2018-01-30 15:16 UTC
Hello, can you add AutoSave data function?

As before, there is a problem of resetting quests (tasks are reset to 1 stage). I think the automatic saving of quest data will help solve this problem?

**Comment by FlyingPikachu** [comment] 2018-01-30 18:07
Quests already saves a player's quest data at various points, including when the quest is completed. If you are asking if player data can be saved at certain time intervals, the answer is 'no'.

The "tasks are reset to 1 stage" sounds like a bug. Can you provide more details?

**Comment by SwimUp29** [comment] 2018-01-30 18:18
At different intervals (usually about 1 day), the active quests are reset to 1 stage for players. In the console there are no errors, they just go to the server and see that the quest that was completed yesterday was started first.

I noticed that quests can be reset if the server is rebooted (in the normal way). I did a server restart at night, when there are no players, the less, some players still face this problem.

So I thought that autosave could solve the problem.

**Comment by FlyingPikachu** [comment] 2018-01-31 00:26
That may or may not resolve the issue. It's impossible to know without first knowing the cause of the reset issue. And once we know the cause, it'd be much simpler to just fix it rather than add a convoluted auto-save feature. But I appreciate the thought :)

I'll do my best to try and replicate the resetting issue. If I can't, I'll have to close this ticket as there's no material for me to investigate.

**Comment by FlyingPikachu** [comment] 2018-02-03 18:59
Unfortunately, after leaving my test server running for about 36 hours, I was unable to replicate the problem. Without an error or at least _some_ indication of what's causing the issue, there's no way for me to proceed. "Hopefully" someone else experiencing the issue soon and can provide more information :)

**Closed by FlyingPikachu** 2018-02-03 18:59 UTC
