### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by miglas** [FlyingPikachu/Quests#408] opened 2018-05-24 07:21 UTC
(__Required__) 3.3.4

(__Required__) Consoleerror

java.lang.NullPointerException
[木, 24. 5 2018 16:07:49 JST WARN]     at me.blackvein.quests.Quests.showObjectives(Quests.java:1842)
[木, 24. 5 2018 16:07:49 JST WARN]     at me.blackvein.quests.Quests.questCommandHandler(Quests.java:1682)
[木, 24. 5 2018 16:07:49 JST WARN]     at me.blackvein.quests.Quests.onCommand(Quests.java:685)
[木, 24. 5 2018 16:07:49 JST WARN]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[木, 24. 5 2018 16:07:49 JST WARN]     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[木, 24. 5 2018 16:07:49 JST WARN]     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[木, 24. 5 2018 16:07:49 JST WARN]     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[木, 24. 5 2018 16:07:49 JST WARN]     at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1313)
[木, 24. 5 2018 16:07:49 JST WARN]     at net.aufdemrand.denizen.nms.impl.packets.handlers.AbstractListenerPlayIn_v1_12_R1.chat(AbstractListenerPlayIn_v1_12_R1.java:71)
[木, 24. 5 2018 16:07:49 JST WARN]     at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.chat(CraftPlayer.java:239)
[木, 24. 5 2018 16:07:49 JST WARN]     at com.gmail.filoghost.chestcommands.internal.icon.command.PlayerIconCommand.execute(PlayerIconCommand.java:15)
[木, 24. 5 2018 16:07:49 JST WARN]     at com.gmail.filoghost.chestcommands.internal.CommandsClickHandler.onClick(CommandsClickHandler.java:34)
[木, 24. 5 2018 16:07:49 JST WARN]     at com.gmail.filoghost.chestcommands.api.Icon.onClick(Icon.java:319)
[木, 24. 5 2018 16:07:49 JST WARN]     at com.gmail.filoghost.chestcommands.internal.icon.ExtendedIcon.onClick(ExtendedIcon.java:243)
[木, 24. 5 2018 16:07:49 JST WARN]     at com.gmail.filoghost.chestcommands.task.ExecuteCommandsTask.run(ExecuteCommandsTask.java:21)
[木, 24. 5 2018 16:07:49 JST WARN]     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[木, 24. 5 2018 16:07:49 JST WARN]     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[木, 24. 5 2018 16:07:49 JST WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[木, 24. 5 2018 16:07:49 JST WARN]     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[木, 24. 5 2018 16:07:49 JST WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[木, 24. 5 2018 16:07:49 JST WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[木, 24. 5 2018 16:07:49 JST WARN]     at java.lang.Thread.run(Thread.java:748)
[木, 24. 5 2018 16:07:49 JST WARN] java.lang.NullPointerException
[木, 24. 5 2018 16:07:49 JST WARN]     at me.blackvein.quests.Quests.showObjectives(Quests.java:1842)
[木, 24. 5 2018 16:07:49 JST WARN]     at me.blackvein.quests.Quests.questCommandHandler(Quests.java:1682)
[木, 24. 5 2018 16:07:49 JST WARN]     at me.blackvein.quests.Quests.onCommand(Quests.java:685)
[木, 24. 5 2018 16:07:49 JST WARN]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[木, 24. 5 2018 16:07:49 JST WARN]     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[木, 24. 5 2018 16:07:49 JST WARN]     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[木, 24. 5 2018 16:07:49 JST WARN]     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[木, 24. 5 2018 16:07:49 JST WARN]     at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1313)
[木, 24. 5 2018 16:07:49 JST WARN]     at net.aufdemrand.denizen.nms.impl.packets.handlers.AbstractListenerPlayIn_v1_12_R1.chat(AbstractListenerPlayIn_v1_12_R1.java:71)
[木, 24. 5 2018 16:07:49 JST WARN]     at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.chat(CraftPlayer.java:239)
[木, 24. 5 2018 16:07:49 JST WARN]     at com.gmail.filoghost.chestcommands.internal.icon.command.PlayerIconCommand.execute(PlayerIconCommand.java:15)
[木, 24. 5 2018 16:07:49 JST WARN]     at com.gmail.filoghost.chestcommands.internal.CommandsClickHandler.onClick(CommandsClickHandler.java:34)
[木, 24. 5 2018 16:07:49 JST WARN]     at com.gmail.filoghost.chestcommands.api.Icon.onClick(Icon.java:319)
[木, 24. 5 2018 16:07:49 JST WARN]     at com.gmail.filoghost.chestcommands.internal.icon.ExtendedIcon.onClick(ExtendedIcon.java:243)
[木, 24. 5 2018 16:07:49 JST WARN]     at com.gmail.filoghost.chestcommands.task.ExecuteCommandsTask.run(ExecuteCommandsTask.java:21)
[木, 24. 5 2018 16:07:49 JST WARN]     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[木, 24. 5 2018 16:07:49 JST WARN]     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[木, 24. 5 2018 16:07:49 JST WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[木, 24. 5 2018 16:07:49 JST WARN]     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[木, 24. 5 2018 16:07:49 JST WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[木, 24. 5 2018 16:07:49 JST WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[木, 24. 5 2018 16:07:49 JST WARN]     at java.lang.Thread.run(Thread.java:748)

**Comment by miglas** [comment] 2018-05-24 10:14
this error too
Could not pass event EntityDamageEvent to DivineItemsRPG v3.0.4-Beta

**Comment by miglas** [comment] 2018-05-24 10:22
this too

[木, 24. 5 2018 19:16:16 JST INFO] test_ issued server command: /quest
[木, 24. 5 2018 19:16:16 JST ERROR] [Quests] currentStage was null for hideuuidforeport on command
[木, 24. 5 2018 19:16:16 JST WARN] java.lang.NullPointerException
[木, 24. 5 2018 19:16:16 JST WARN] 	at me.blackvein.quests.Quests.showObjectives(Quests.java:1842)
[木, 24. 5 2018 19:16:16 JST WARN] 	at me.blackvein.quests.Quests.questCommandHandler(Quests.java:1682)
[木, 24. 5 2018 19:16:16 JST WARN] 	at me.blackvein.quests.Quests.onCommand(Quests.java:685)
[木, 24. 5 2018 19:16:16 JST WARN] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[木, 24. 5 2018 19:16:16 JST WARN] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[木, 24. 5 2018 19:16:16 JST WARN] 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[木, 24. 5 2018 19:16:16 JST WARN] 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[木, 24. 5 2018 19:16:16 JST WARN] 	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1313)
[木, 24. 5 2018 19:16:16 JST WARN] 	at net.aufdemrand.denizen.nms.impl.packets.handlers.AbstractListenerPlayIn_v1_12_R1.chat(AbstractListenerPlayIn_v1_12_R1.java:71)
[木, 24. 5 2018 19:16:16 JST WARN] 	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.chat(CraftPlayer.java:239)
[木, 24. 5 2018 19:16:16 JST WARN] 	at com.gmail.filoghost.chestcommands.internal.icon.command.PlayerIconCommand.execute(PlayerIconCommand.java:15)
[木, 24. 5 2018 19:16:16 JST WARN] 	at com.gmail.filoghost.chestcommands.internal.CommandsClickHandler.onClick(CommandsClickHandler.java:34)
[木, 24. 5 2018 19:16:16 JST WARN] 	at com.gmail.filoghost.chestcommands.api.Icon.onClick(Icon.java:319)
[木, 24. 5 2018 19:16:16 JST WARN] 	at com.gmail.filoghost.chestcommands.internal.icon.ExtendedIcon.onClick(ExtendedIcon.java:243)

**Comment by FlyingPikachu** [comment] 2018-08-07 17:07
First, I would suggest fixing whatever problem you have with DivineItemsRPG, as indicated by

>Could not pass event EntityDamageEvent to DivineItemsRPG v3.0.4-Beta

Second, I'm not sure what "hideuuidforeport" is, but it seems to be messing with Quests.

>[木, 24. 5 2018 19:16:16 JST ERROR] [Quests] currentStage was null for hideuuidforeport on command

Closing as this does not appear to be inherently caused by Quests.

**Closed by FlyingPikachu** 2018-08-07 17:07 UTC
