### ISSUE TITLE
Java Error in Console

### ISSUE THREAD

**Issue by nexlemav** [FlyingPikachu/Quests#498] opened 2018-10-26 17:49 UTC
One of my staff members is the one setting all this up. I, for, one haven't fully researched quests but my staff member has been using Quests for several years to where this is the first time we are both unfamiliar with these errors.

Quests v3.3.8-b488

26.10 13:40:03 [Server] WARN [Quests] Task #146 for Quests v3.3.8-b488 generated an exception
26.10 13:40:03 [Server] INFO java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_13_R1/entity/CraftPlayer
26.10 13:40:03 [Server] INFO at me.blackvein.particles.Eff_1_13_R1.sendToPlayer(Eff_1_13_R1.java:119) ~[?:?]
26.10 13:40:03 [Server] INFO at me.blackvein.quests.NpcEffectThread.showEffect_1_13_R1(NpcEffectThread.java:130) ~[?:?]
26.10 13:40:03 [Server] INFO at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:88) ~[?:?]
26.10 13:40:03 [Server] INFO at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:54) ~[?:?]
26.10 13:40:03 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.2-R0.1-SNAPSHOT-b1963.jar:git-Spigot-a1ba5fe-3359cb1]
26.10 13:40:03 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.2-R0.1-SNAPSHOT-b1963.jar:git-Spigot-a1ba5fe-3359cb1]
26.10 13:40:03 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.2-R0.1-SNAPSHOT-b1963.jar:git-Spigot-a1ba5fe-3359cb1]
26.10 13:40:03 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2-R0.1-SNAPSHOT-b1963.jar:git-Spigot-a1ba5fe-3359cb1]
26.10 13:40:03 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2-R0.1-SNAPSHOT-b1963.jar:git-Spigot-a1ba5fe-3359cb1]
26.10 13:40:03 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2-R0.1-SNAPSHOT-b1963.jar:git-Spigot-a1ba5fe-3359cb1]
26.10 13:40:03 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

https://pastebin.com/Vh2uzaWF

**Comment by nexlemav** [comment] 2018-10-26 17:50
Running spigot-1.13.2-R0.1-SNAPSHOT-b1963 if that helps

**Comment by nexlemav** [comment] 2018-10-30 12:51
I get this error on startup using build 489

[08:47:21 WARN]: [Quests] Task #165 for Quests v3.4.0-b489 generated an exception
java.lang.IllegalArgumentException: Material cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.13.2-R0.1-SNAPSHOT-b1962.jar:git-Spigot-a1ba5fe-3359cb1]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:69) ~[spigot-1.13.2-R0.1-SNAPSHOT-b1962.jar:git-Spigot-a1ba5fe-3359cb1]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:57) ~[spigot-1.13.2-R0.1-SNAPSHOT-b1962.jar:git-Spigot-a1ba5fe-3359cb1]
        at me.blackvein.quests.Quests.processStages(Quests.java:2734) ~[?:?]
        at me.blackvein.quests.Quests.loadQuests(Quests.java:2181) ~[?:?]
        at me.blackvein.quests.Quests$1.run(Quests.java:296) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.2-R0.1-SNAPSHOT-b1962.jar:git-Spigot-a1ba5fe-3359cb1]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.2-R0.1-SNAPSHOT-b1962.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.2-R0.1-SNAPSHOT-b1962.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2-R0.1-SNAPSHOT-b1962.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2-R0.1-SNAPSHOT-b1962.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2-R0.1-SNAPSHOT-b1962.jar:git-Spigot-a1ba5fe-3359cb1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

**Comment by nexlemav** [comment] 2018-10-30 12:54
I deleted the Quests directory and loads fine now except it cant load a new lang file

ERROR]: [Quests] Failed loading lang files for en-US because they were not found. Using default en-US

**Comment by FlyingPikachu** [comment] 2018-10-30 21:15
Duplicate of #496

**Closed by FlyingPikachu** 2018-10-30 21:15 UTC

**Comment by nexlemav** [comment] 2018-10-30 22:08
Sorry I posted twice by error. The above mentioned error happens when starting a new install of Quests v 3.4.0 b-489. This is not resolved.

[ERROR]: [Quests] Failed loading lang files for en-US because they were not found. Using default en-US
