### ISSUE TITLE
Add MySQL support

### ISSUE THREAD

**Issue by HansscMe** [FlyingPikachu/Quests#504] opened 2018-11-03 17:23 UTC
I own a bungee server network.It's a pity I couldn't use this great plugin for
I want to share the data across the servers,but there is no solution.
I'll appreciate it if you do it.Thank you!

**Comment by FlyingPikachu** [comment] 2018-11-05 18:29
Duplicate of #312 

Thanks for your interest in Quests! Please contribute your ideas for MySQL in #312

**Closed by FlyingPikachu** 2018-11-05 18:29 UTC
