### ISSUE TITLE
Bug + Suggestion on language support

### ISSUE THREAD

**Issue by InfroDaz** [FlyingPikachu/Quests#449] opened 2018-08-06 18:28 UTC
(__Required__) 3.3.4-b316

(__Required__) Dilver items with same id and different data values are listed as [id]:0

Ex:

The questgiver asks a player to carry 4 different types of wood planks. In a progression message they are all listed as oak planks.

https://media.discordapp.net/attachments/397341289517154314/476085067764989992/2018-08-06_20.51.28.png?width=995&height=559

**Comment by InfroDaz** [comment] 2018-08-06 18:29
Suggestion:

Please make it possible to change the names of items to different languages or translate 'em

**Comment by FlyingPikachu** [comment] 2018-08-07 15:46
Bug is likely related to #441 

Item names in different languages is currently not possible as discussed in #172

**Comment by FlyingPikachu** [comment] 2018-12-01 17:38
@InfroDaz If you mean based on the client language, no. Based on the plugin language, yes.

Item names in different languages are now possible starting with Quests 3.4.4 (set `translate-items: true` in config.yml).

Seeing as this is now a close duplicate of #441, I'm closing this issue as such.

**Closed by FlyingPikachu** 2018-12-01 17:38 UTC
Labels: bug
