### ISSUE TITLE
PlayerInteractEvent Error Spam

### ISSUE THREAD

**Issue by ArathiaMC** [FlyingPikachu/Quests#597] opened 2018-12-29 23:01 UTC
Version: 3.5.7-b573

Error is being constantly in console: https://pastebin.com/qcXh4ug4

**Comment by arturek1666** [comment] 2018-12-30 00:31
Same issue for me, so I can confirm this issue.

**Comment by FlyingPikachu** [comment] 2018-12-30 01:11
Duplicate of #594

**Closed by FlyingPikachu** 2018-12-30 01:11 UTC
