### ISSUE TITLE
Crop harvest bug Item ID 59

### ISSUE THREAD

**Issue by johnsoncui02** [FlyingPikachu/Quests#226] opened 2018-01-07 04:27 UTC
Quest Version: build # 220 one of the jenkens build.
Problem with item ID 59 which is supposedly to be a full grown crop ID. I used it as a break-block event in the quest . I'm assuming that wouldn't work and wasn't implemented on the quest plugin already. But i still want to state this to be called to attention.

Error Message:
> [04:17:18 WARN]: java.lang.NullPointerException
> [04:17:18 WARN]: at me.blackvein.quests.Quester.getObjectives(Quester.java:382)
> [04:17:18 WARN]: at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:368)
> [04:17:18 WARN]: at me.blackvein.quests.Quests.showObjectives(Quests.java:1775)
> [04:17:18 WARN]: at me.blackvein.quests.Quests.questCommandHandler(Quests.java:1611)
> [04:17:18 WARN]: at me.blackvein.quests.Quests.onCommand(Quests.java:578)
> [04:17:18 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
> [04:17:18 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
> [04:17:18 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
> [04:17:18 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
> [04:17:18 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
> [04:17:18 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [04:17:18 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
> [04:17:18 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
> [04:17:18 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [04:17:18 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [04:17:18 WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
> [04:17:18 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
> [04:17:18 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
> [04:17:18 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
> [04:17:18 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
> [04:17:18 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by FlyingPikachu** [comment] 2018-01-07 05:17
Possibly related to issue #223

**Comment by FlyingPikachu** [comment] 2018-02-14 16:48
It seems this is caused by the issue discussed in #282. Seeing as that issue is more detailed, I'm opting to close this one.

**Closed by FlyingPikachu** 2018-02-14 16:48 UTC
Labels: bug
