### ISSUE TITLE
Click Event

### ISSUE THREAD

**Issue by QueenKisaki** [FlyingPikachu/Quests#13] opened 2017-06-25 18:40 UTC
https://pastebin.com/51GmFdFT

**Comment by FlyingPikachu** [comment] 2017-06-25 21:43
@QueenKisaki I see another plugin's error mixed in with this, as well as you have your Citizens jar named 'Citizens%20(1)' which may introduce its own set of problems.

Given the nature of your recently closed issue (#12) and the fact you've provided no context with this error, I'm choosing to close this as I feel there's a good chance the error could be caused by your server environment.

Please address some other issues with your server before making future reports.

**Closed by FlyingPikachu** 2017-06-25 21:43 UTC

**Comment by QueenKisaki** [comment] 2017-06-25 23:21
https://pastebin.com/wwQ0EE8L I corrected the jar names but still getting the same error. This is full startup and as you can see the moment a player logs in the error comes up as well as again I try questing and get https://pastebin.com/t59UB0yD If this is not from Quests than from what, Citizens?
