### ISSUE TITLE
Error: Could not pass event EntityDeathEvent to Quests

### ISSUE THREAD

**Issue by arturek1666** [FlyingPikachu/Quests#384] opened 2018-04-30 07:50 UTC
Plugin Version:
3.3.2-b311
Issue:
I don't really see an issue with the plugin for now but the error is showing up
Console error: 
`[K[31;1m[09:13:10 ERROR]: Could not pass event EntityDeathEvent to Quests v3.3.2-b311
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[craftbukkit.jar:git-Paper-1386]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[craftbukkit.jar:git-Paper-1386]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Paper-1386]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [craftbukkit.jar:git-Paper-1386]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [craftbukkit.jar:git-Paper-1386]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:396) [craftbukkit.jar:git-Paper-1386]
        at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1139) [craftbukkit.jar:git-Paper-1386]
        at net.minecraft.server.v1_12_R1.EntityCreeper.die(EntityCreeper.java:145) [craftbukkit.jar:git-Paper-1386]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:979) [craftbukkit.jar:git-Paper-1386]
        at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [craftbukkit.jar:git-Paper-1386]
        at net.minecraft.server.v1_12_R1.Explosion.a(Explosion.java:140) [craftbukkit.jar:git-Paper-1386]
        at net.minecraft.server.v1_12_R1.World.createExplosion(World.java:2041) [craftbukkit.jar:git-Paper-1386]
        at net.minecraft.server.v1_12_R1.WorldServer.createExplosion(WorldServer.java:1250) [craftbukkit.jar:git-Paper-1386]
        at net.minecraft.server.v1_12_R1.EntityCreeper.dr(EntityCreeper.java:211) [craftbukkit.jar:git-Paper-1386]
        at net.minecraft.server.v1_12_R1.EntityCreeper.B_(EntityCreeper.java:116) [craftbukkit.jar:git-Paper-1386]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1771) [craftbukkit.jar:git-Paper-1386]
        at net.minecraft.server.v1_12_R1.World.h(World.java:1741) [craftbukkit.jar:git-Paper-1386]
        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1562) [craftbukkit.jar:git-Paper-1386]
        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:675) [craftbukkit.jar:git-Paper-1386]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:914) [craftbukkit.jar:git-Paper-1386]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [craftbukkit.jar:git-Paper-1386]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [craftbukkit.jar:git-Paper-1386]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [craftbukkit.jar:git-Paper-1386]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
[39;0m`
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by FlyingPikachu** [comment] 2018-04-30 18:32
Duplicate of #381

**Closed by FlyingPikachu** 2018-04-30 18:32 UTC
