### ISSUE TITLE
GUI Multi Line

### ISSUE THREAD

**Issue by Sprungente** [FlyingPikachu/Quests#293] opened 2018-02-16 01:44 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
b253

(__Required__) Please describe the problem and how to replicate it. Any console errors?
https://picload.org/view/darlrgpa/2018-02-16_02.38.47.png.html
Chatcolors and other formatting don't use for every lines. I know you will link me to other Issues but it's underline that you should try to fix it. I will very thanksfull when you could fix it. 

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://picload.org/view/darlrgpa/2018-02-16_02.38.47.png.html

**Comment by FlyingPikachu** [comment] 2018-02-16 03:58
You are correct that I will link you to other issues, take a look at #193 for a good workaround.

Firstly, chatcolors DO work, but you must specify them at each new line. What I suspect you want is a way to predict or control when a new line will start, which Quests does not currently offer. That said, this is not a bug, and such does not require a "fix".

Now, I haven't taken a look at why Quests does not offer new line prediction/control in a while, but given the fact I've closed issues like this one countless times (most recently #273), I assume that I had good reason. However, I'll leave this open until I can take a closer look and perhaps recall that reasoning.

**Comment by Sprungente** [comment] 2018-02-16 23:03
Cow do you think when the startmessage will set per line?

**Comment by FlyingPikachu** [comment] 2018-11-29 21:39
Looking into this once again, I don't see any easy way to implement this given the way this portion of the plugin is coded (each line is treated separately and cannot carry over the previous line's ChatColor). If anyone creative would like to submit a PR with a workaround, I'll leave a link to the code below, but I'm closing this for now.

https://github.com/FlyingPikachu/Quests/blob/83ef4e849e4ae67e6030119fff0687c6d06153ac/src/main/java/me/blackvein/quests/Quester.java#L2607

**Closed by FlyingPikachu** 2018-11-29 21:39 UTC
Labels: duplicate, enhancement

**Comment by Sprungente** [comment] 2018-12-03 17:03
@mastercake10 
Could you maybe get an eye on it? Maybe you're finding a solution to save all lines in color.
