### ISSUE TITLE
Can only enter LOG and no other LOG types allowed

### ISSUE THREAD

**Issue by Klawdek** [FlyingPikachu/Quests#680] opened 2019-02-05 00:00 UTC
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.1 
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When attempting to enter anything other than LOG like LOG:1 it will not accept it and says LOG:1 not a valid block name.  It was suggested that I try using the durability option but when entering multiple LOG types such AS LOG LOG LOG it claims duplicate entries not allowed.  I would suggest supporting item ids such as 17:0 17:1.  This was mentioned before in sept 2018 and the issue was closed but is has never been resolved.  This issue kills any woodcutter quest and from the previous report means any alternate block type cannot be used in quests.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by FlyingPikachu** [comment] 2019-02-05 04:12
Would you post a screenshot of the "duplicate entries" error you got? It would help me diagnose this faster. Thanks!

**Comment by Klawdek** [comment] 2019-02-05 05:01
I have already posted some shots on your discord with what I typed and the error message.  Sorry if it was too many shots but I wanted to cover the different syntaxes that have been suggested previously on discord.

**Comment by FlyingPikachu** [comment] 2019-02-05 05:04
That’s alright, but please at least link to your screenshots from here in case others want to contribute to the issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Klawdek** [comment] 2019-02-05 07:05
Ok here are links to all the screenshots.  The first has what I typed and the second has the resultant error and so on.
https://media.discordapp.net/attachments/510222124237979674/542165863693025290/Screenshot_7787.png?width=726&height=409

https://media.discordapp.net/attachments/510222124237979674/542165909947678730/Screenshot_7788.png?width=726&height=409

https://media.discordapp.net/attachments/510222124237979674/542165991506051101/Screenshot_7789.png?width=726&height=409

https://media.discordapp.net/attachments/510222124237979674/542166024750104626/Screenshot_7790.png?width=726&height=409

https://media.discordapp.net/attachments/510222124237979674/542166090961256458/Screenshot_7791.png?width=726&height=409

https://media.discordapp.net/attachments/510222124237979674/542166126533017601/Screenshot_7792.png?width=726&height=409

**Comment by FlyingPikachu** [comment] 2019-02-05 18:49
Thanks. After further investigation, this isn't a bug nor a duplicate of #483, but rather the plugin is intentionally blocking the use of duplicate entries. Since it isn't clear to me _why_ it's blocking it, I'll push a commit which will allow you to have duplicates. However, I can't guarantee that there won't be side-effects, so I'll re-instate the block if this becomes a problem.

Use this build, once available:
http://ci.ac3-servers.eu/job/Quests/651/

**Closed** 2019-02-05 18:48 UTC
Labels: bug, duplicate
