### ISSUE TITLE
Quests stacking up and not ending 

### ISSUE THREAD

**Issue by Vestle** [FlyingPikachu/Quests#178] opened 2017-12-10 00:02 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 3.1.2
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Players quests are not clearing after completion and just stacking on top of each other eventually getting stuck. 
https://prnt.sc/hlb3ly
https://prnt.sc/hlb3xd
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
Personally no because these are all custom made quests. Private message if needed.

**Comment by FlyingPikachu** [comment] 2017-12-10 17:51
Duplicate of #173

Use latest dev build to correct this issue.

**Closed by FlyingPikachu** 2017-12-10 17:51 UTC
