### ISSUE TITLE
Could not pass event NPCRightClickEvent to Quests v3.1.6-b203

### ISSUE THREAD

**Issue by NevendyND** [FlyingPikachu/Quests#220] opened 2018-01-03 02:46 UTC
Version Quests-3.1.6

I can't complete the Quest he gives me the item but not the permission

![grdhyh](https://user-images.githubusercontent.com/28860034/34507661-7e545bc4-f038-11e7-86b4-af6b23fa7ef2.jpg)

I can't copy the text sorry hope you can read the picture...

And here is the Quest

  custom1:
    name: Test
    npc-giver-id: 0
    ask-message: Help me pls
    finish-message: Thanks..
    gui-display: name-SPECKLED_MELON:amount-1
    stages:
      ordered:
        '1':
          npc-ids-to-talk-to:
          - 0
          mobs-to-kill:
          - Skeleton
          mob-amounts:
          - 1
          start-message: Please come to me
        '2':
          npc-ids-to-talk-to:
          - 0
          start-message:  Please come to me again
    rewards:
      items:
      - name-SPECKLED_MELON:amount-1:displayname-Warpstone
      permissions:
      - clickwarp.warp.*

**Comment by FlyingPikachu** [comment] 2018-01-03 03:14
Duplicate of #155 (unresolved)

**Comment by NevendyND** [comment] 2018-01-03 03:21
Good Luck :s

**Comment by NevendyND** [comment] 2018-01-03 03:31
ps

Could not pass event EntityDeathEvent to Quests v3.1.6-b201

its appears too when i delete the talk to npc.

**Comment by FlyingPikachu** [comment] 2018-01-03 03:51
This should be resolved in http://ci.ac3-servers.eu/job/Quests/221/ once the download is available in a matter of minutes.

As for the EntityDeathEvent, please try the dev build I've linked and, if the error still occurs, create a new issue containing the exact error generated by that build. Thanks!

**Comment by FlyingPikachu** [comment] 2018-01-03 20:04
User indicated issue is resolved when the permission reward is removed. Exploring as new issue in #221

**Comment by FlyingPikachu** [comment] 2018-01-03 20:50
Fix was discovered to be insufficient as user cannot communicate with NPC once mob-to-kill task has been satisfied (however, error no longer appears).

**Closed** 2018-01-04 04:57 UTC
Labels: bug, duplicate

**Comment by FlyingPikachu** [comment] 2018-01-04 05:00
@NevendyND An error in my previous fix caused this behavior. The following dev build shall resolve the issue, once available. Thanks for using Quests!

http://ci.ac3-servers.eu/job/Quests/224/

**Comment by NevendyND** [comment] 2018-01-04 05:16
fix it 
works perfect :3 
You God :D 

Thank you <3

I love your Plugin
