### ISSUE TITLE
Right click on any block event error

### ISSUE THREAD

**Issue by ThousandX** [FlyingPikachu/Quests#600] opened 2018-12-30 17:42 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
v3.5.7-b573
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Yep, Error log http://prntscr.com/m1delx
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/wndFKxRH

Error when right click on any block https://pastebin.com/vqKxXhVh

**Comment by FlyingPikachu** [comment] 2018-12-30 18:37
Duplicate of #594

Use latest dev build.

**Closed by FlyingPikachu** 2018-12-30 18:37 UTC
