### ISSUE TITLE
Player data is lost (v3.2.7)

### ISSUE THREAD

**Issue by RubenStryker** [FlyingPikachu/Quests#343] opened 2018-03-27 19:49 UTC
The problem I have had with this version and with previous versions, is that the progress of the players is lost, in addition to the costs involved in each mission.
At any time the plugin starts to fail, does not count the killed mobs, or other errors and from one moment to another the user loses the progress in the mission.

Quests version: 3.2.7
`[Quests] Loading Quests v3.2.7-b284`

Console errors:
`Line x: [15:55:00] [Server thread/ERROR]: [Quests] currentStage was null for 97a0169f-d9ee-384f-8314-7d7395efa638 on command
Line z:[15:56:12] [Async Chat Thread - #43/ERROR]: [Quests] currentStage was null for 97a0169f-d9ee-384f-8314-7d7395efa638 on chat
Some errors:[15:57:21] [Server thread/ERROR]: [Quests] currentStage was null for 97a0169f-d9ee-384f-8314-7d7395efa638 on command
[15:57:25] [Server thread/INFO]: resdicam0909 issued server command: /t
[15:57:25] [Server thread/INFO]: [PLAYER_COMMAND] resdicam0909: /t 
[15:57:25] [Server thread/INFO]: o_Xo issued server command: /quests journal
[15:57:25] [Server thread/ERROR]: [Quests] currentStage was null for 97a0169f-d9ee-384f-8314-7d7395efa638 on command
[15:57:26] [Server thread/INFO]: o_Xo issued server command: /quests journal
[15:57:26] [Server thread/ERROR]: [Quests] currentStage was null for 97a0169f-d9ee-384f-8314-7d7395efa638 on command
[15:57:27] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'quests' in plugin Quests v3.2.7-b284
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:374) ~[?:?]
	at me.blackvein.quests.Quester.updateJournal(Quester.java:268) ~[?:?]
	at me.blackvein.quests.Quests.questsJournal(Quests.java:1555) ~[?:?]
	at me.blackvein.quests.Quests.questActionsCommandHandler(Quests.java:1351) ~[?:?]
	at me.blackvein.quests.Quests.onCommand(Quests.java:710) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]`
	... 15 more

[Config.yml - PasteBin](https://pastebin.com/BPRkMhVh)

Thanks.

**Comment by andinis** [comment] 2018-03-29 10:31
on my end the data is not lost only the stages are bugged for players here is an example:
currentQuests:
- Clean the statue of the Hokage's nose
- Helping the villagers in the small village
- Team in Need!
- Talk to my friend
- Orochimaru
- Stolen Sunagakure Intel
- Find Missing Cat
- Speedy Kitty
- Finding the LostKid
currentStages:
- 0
- 0
- null
- 0
- null
- 2
- 0
- null
- 0

**Comment by RubenStryker** [comment] 2018-03-29 11:50
The user data is fine, they are missions that disappear from one moment to another in the middle of the mission.
`currentQuests: none
currentStages: none
quest-points: 60
completed-Quests:
- Atraco 1
- ModernWar Mision
- Atraco 2
hasJournal: false
lastKnownName: o_Xo
`
This user, had an active mission called "Modern War 2", and as you can see he does not have it in his configuration.

**Comment by andinis** [comment] 2018-04-12 08:25
Since the developer doesn't do anything. Meanwhile I found out why this happens. /quests journal is breaking players and all their permissions they cant do anything and it's duplicating the quests book instead of removing them

**Comment by FlyingPikachu** [comment] 2018-04-12 18:08
@RubenStryker The error you've posted means that a quester with a UUID of `97a0169f-d9ee-384f-8314-7d7395efa638` does not have any current stages even though Quests expects that they should. Looking up that UUID online, it doesn't appear to match with any known Minecraft player...

![uuid](https://user-images.githubusercontent.com/2267126/38695484-6921c596-3e5a-11e8-9014-147bc1e8eaba.png)

It could be that an NPC has been mistaken for a quester somehow or perhaps you're running in offline mode? Hard to suggest a fix when there's no obvious way to replicate the problem. You could try blacklisting the UUID and see if that resolves the issue (believe the command is `/questadmin purge 97a0169f-d9ee-384f-8314-7d7395efa638`).

@andinis That journal issue sounds unrelated and is more likely a duplicate of #332

**Comment by RubenStryker** [comment] 2018-04-13 15:36
That uuid that does not find, on my server is the user "O_xo" that if you look for your username on that website gives a different uuid.
I do not know why, maybe it's because the server is non-premium, if I do what you tell me this user will not be able to perform any mission.

I have warned the users of my server not to do missions until this is solved, since they lose the money and the items that are required to start some missions.

My users are waiting for you to solve it, if you want to provide more information about the error I can provide all you need.

A greeting.

**Comment by FlyingPikachu** [comment] 2018-04-13 20:38
If by "non-premium" you mean the server is running in offline mode, chances are that is part of the issue. In your config.yml, there is a note that says:

`#The server is no-premium, and as previously the user data was also lost I have tried to modify these last two options.`
`convert-data-on-startup: false`
`generate-files-on-join: false`


Quests needs to know a player's UUID to save and load their data. Here's what I think happened: since your server is offline, it saved whatever the player's client claimed its UUID to be when they joined, in this case the unofficial `97a0169f-d9ee-384f-8314-7d7395efa638`. However, when you enabled `convert-data-on-startup`, Quests tried to get their official UUID from Mojang's servers, which is `29ba6c34-a53c-4a8b-8d55-306526a8822a`. It stands to reason that, since the two are obviously different, Quests is having trouble figuring out which UUID to use.

Unfortunately, the only way to fix this would be to stop the server, wipe all traces of either UUID from the `Quests/data/` folder and start the server with `convert-data-on-startup: false`. You could try replacing every instance of the official UUID with the unofficial one, but frankly that may or may not work. In the future, do not enable settings you're unfamiliar with.

**Closed by FlyingPikachu** 2018-04-13 20:38 UTC
Labels: bug
