### ISSUE TITLE
this is the plugin problem or my config?

### ISSUE THREAD

**Issue by newbie029** [FlyingPikachu/Quests#371] opened 2018-04-19 07:41 UTC
> [15:40:16 ERROR]: [Quests] currentStage was null for 9b091d57-1b75-3e25-8a75-f5dcc803dbcb on command
> [15:40:16 ERROR]: [Quests] currentStage was null for 9b091d57-1b75-3e25-8a75-f5dcc803dbcb on command
> [15:40:16 ERROR]: [Quests] currentStage was null for 9b091d57-1b75-3e25-8a75-f5dcc803dbcb on command
> [15:40:16 ERROR]: [Quests] currentStage was null for 9b091d57-1b75-3e25-8a75-f5dcc803dbcb on command
> [15:40:16 ERROR]: [Quests] currentStage was null for 9b091d57-1b75-3e25-8a75-f5dcc803dbcb on command
> [15:40:16 ERROR]: [Quests] currentStage was null for 9b091d57-1b75-3e25-8a75-f5dcc803dbcb on command

**Comment by newbie029** [comment] 2018-04-19 07:48
> [15:46:54 ERROR]: [Quests] currentStage was null for 9b091d57-1b75-3e25-8a75-f5dcc803dbcb on command
> [15:46:54 ERROR]: [Quests] currentStage was null for 9b091d57-1b75-3e25-8a75-f5dcc803dbcb on command
> [15:46:54 ERROR]: [Quests] currentStage was null for 9b091d57-1b75-3e25-8a75-f5dcc803dbcb on command
> [15:46:54 ERROR]: [Quests] currentStage was null for 9b091d57-1b75-3e25-8a75-f5dcc803dbcb on command
> [15:46:54 ERROR]: [Quests] currentStage was null for 9b091d57-1b75-3e25-8a75-f5dcc803dbcb on command
> [15:46:54 ERROR]: [Quests] currentStage was null for 9b091d57-1b75-3e25-8a75-f5dcc803dbcb on command
> [15:46:54 WARN]: java.lang.NullPointerException
> [15:46:54 WARN]: at me.blackvein.quests.Quests.showObjectives(Quests.java:1882)
> [15:46:54 WARN]: at me.blackvein.quests.Quests.questCommandHandler(Quests.java:1722)
> [15:46:54 WARN]: at me.blackvein.quests.Quests.onCommand(Quests.java:694)
> [15:46:54 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
> [15:46:54 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
> [15:46:54 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
> [15:46:54 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [15:46:54 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
> [15:46:54 WARN]: at java.lang.Thread.run(Thread.java:748)
> [15:46:54 WARN]: java.lang.NullPointerException
> [15:46:54 WARN]: at me.blackvein.quests.Quests.showObjectives(Quests.java:1882)
> [15:46:54 WARN]: at me.blackvein.quests.Quests.questCommandHandler(Quests.java:1722)
> [15:46:54 WARN]: at me.blackvein.quests.Quests.onCommand(Quests.java:694)
> [15:46:54 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
> [15:46:54 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
> [15:46:54 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
> [15:46:54 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [15:46:54 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
> [15:46:54 WARN]: at java.lang.Thread.run(Thread.java:748)
> [15:46:54 WARN]: java.lang.NullPointerException
> [15:46:54 WARN]: at me.blackvein.quests.Quests.showObjectives(Quests.java:1882)
> [15:46:54 WARN]: at me.blackvein.quests.Quests.questCommandHandler(Quests.java:1722)
> [15:46:54 WARN]: at me.blackvein.quests.Quests.onCommand(Quests.java:694)
> [15:46:54 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
> [15:46:54 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
> [15:46:54 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
> [15:46:54 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [15:46:54 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
> [15:46:54 WARN]: at java.lang.Thread.run(Thread.java:748)
> [15:46:54 WARN]: java.lang.NullPointerException
> [15:46:54 WARN]: at me.blackvein.quests.Quests.showObjectives(Quests.java:1882)
> [15:46:54 WARN]: at me.blackvein.quests.Quests.questCommandHandler(Quests.java:1722)
> [15:46:54 WARN]: at me.blackvein.quests.Quests.onCommand(Quests.java:694)
> [15:46:54 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
> [15:46:54 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
> [15:46:54 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
> [15:46:54 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [15:46:54 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
> [15:46:54 WARN]: at java.lang.Thread.run(Thread.java:748)
> [15:46:54 WARN]: java.lang.NullPointerException
> [15:46:54 WARN]: at me.blackvein.quests.Quests.showObjectives(Quests.java:1882)
> [15:46:54 WARN]: at me.blackvein.quests.Quests.questCommandHandler(Quests.java:1722)
> [15:46:54 WARN]: at me.blackvein.quests.Quests.onCommand(Quests.java:694)
> [15:46:54 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
> [15:46:54 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
> [15:46:54 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
> [15:46:54 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [15:46:54 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
> [15:46:54 WARN]: at java.lang.Thread.run(Thread.java:748)
> [15:46:54 WARN]: java.lang.NullPointerException
> [15:46:54 WARN]: at me.blackvein.quests.Quests.showObjectives(Quests.java:1882)
> [15:46:54 WARN]: at me.blackvein.quests.Quests.questCommandHandler(Quests.java:1722)
> [15:46:54 WARN]: at me.blackvein.quests.Quests.onCommand(Quests.java:694)
> [15:46:54 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
> [15:46:54 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
> [15:46:54 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
> [15:46:54 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [15:46:54 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
> [15:46:54 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
> [15:46:54 WARN]: at java.lang.Thread.run(Thread.java:748)

this happen everytime

**Comment by FlyingPikachu** [comment] 2018-04-20 14:47
Duplicate of #343. Use the latest dev build and follow the instructions in #343

**Closed by FlyingPikachu** 2018-04-20 14:47 UTC
