### ISSUE TITLE
Error when adding rewards

### ISSUE THREAD

**Issue by jeannen** [FlyingPikachu/Quests#95] opened 2015-04-26 21:09 UTC
Hi, when i try to add a reward, the text in the editor don't show up, and there is an error in the logs:
(The problem can be solved when i select the third option [choose item] )

Here are my logs:

[23:04:18 ERROR]: Error handling conversation prompt
java.lang.NullPointerException
at me.blackvein.quests.util.ItemUtil.getDisplayString(ItemUtil.java:168) ~[?:?]
at me.blackvein.quests.prompts.RewardsPrompt$ItemListPrompt.getPromptText(RewardsPrompt.java:347) ~[?:?]
at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:291) ~[spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:230) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at org.bukkit.craftbukkit.v1_8_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1033) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.PlayerConnection$2.evaluate(PlayerConnection.java:964) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at org.bukkit.craftbukkit.v1_8_R1.util.Waitable.run(Waitable.java:24) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:715) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[23:04:19 INFO]: kikooadept issued server command: /f home
[23:04:20 INFO]: <[é��]Skolll> Salut tibo
[23:04:20 ERROR]: Error handling conversation prompt
java.lang.NullPointerException
at me.blackvein.quests.util.ItemUtil.getDisplayString(ItemUtil.java:168) ~[?:?]
at me.blackvein.quests.prompts.RewardsPrompt$ItemListPrompt.getPromptText(RewardsPrompt.java:347) ~[?:?]
at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:291) ~[spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:230) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at org.bukkit.craftbukkit.v1_8_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1033) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.PlayerConnection$2.evaluate(PlayerConnection.java:964) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at org.bukkit.craftbukkit.v1_8_R1.util.Waitable.run(Waitable.java:24) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:715) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]

------------------------------------------------------------------
I've got also an error when I use /questadmin reload:

[23:12:10 WARN]: [Quests] Task #3276435 for Quests v2.4.0 generated an exception
java.lang.NullPointerException
at me.blackvein.quests.Quests.checkList(Quests.java:4911) ~[?:?]
at me.blackvein.quests.Quests.loadRewards(Quests.java:2841) ~[?:?]
at me.blackvein.quests.Quests.loadQuests(Quests.java:2807) ~[?:?]
at me.blackvein.quests.Quests$1.run(Quests.java:219) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]

**Comment by Leescar** [comment] 2015-04-27 12:17
The first error happens when you set a reward and attempt to save the quest after the reward is set right?
What steps did you take and can you pastebin your quests.yml?

**Comment by jeannen** [comment] 2015-04-27 17:05
Yep, i don't have any message, the text don't show up !

I add the reward in last, but it's the same when i add it in first

Here is my quest.yml
http://pastebin.com/ZfrK9Gby

**Comment by Leescar** [comment] 2015-04-28 03:41
That's your config.yml file
There are three other .yml files quests.yml events.yml and data.yml in the same folder.
The one needed to test the issue is the quests.yml

**Comment by jeannen** [comment] 2015-04-28 18:44
Oh, sorry:
http://pastebin.com/FetgHeF5

**Comment by Leescar** [comment] 2015-04-29 07:23
Alright the issue your getting is because of this quest:
http://pastebin.com/UG4JJZjd
As you can see that quest has - null and it has duplicates of the reward you want five times.
Get rid of the null and the duplicate rewards like so:
http://pastebin.com/uFAZ90cj
Then your error should be fixed.

**Comment by jeannen** [comment] 2015-04-29 16:57
Oooh, thanks you a lot, I try that and i tell you if the issue is fixed :)

**Comment by Leescar** [comment] 2015-05-04 14:49
Alright well since you haven't responded yet I am under the impression this is solved.

**Comment by jeannen** [comment] 2015-05-04 17:45
Yep, but i've got 2 others haha :p
( https://github.com/FlyingPikachu/Quests/issues/105 )

**Comment by FlyingPikachu** [comment] 2015-05-05 13:38
Closing as solved. Thanks @Leescar !

**Closed by FlyingPikachu** 2015-05-05 13:38 UTC
