### ISSUE TITLE
Objective Duplication

### ISSUE THREAD

**Issue by PengBread** [FlyingPikachu/Quests#247] opened 2018-01-17 10:19 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.1 and 3.2.2 [ Dev Build ]

(__Required__) Please describe the problem and how to replicate it. Any console errors?
After taking a quest and log out, the objective will duplicate into multiple never ending quest.
https://cdn.discordapp.com/attachments/228816365459341312/403130673994661888/unknown.png

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/G8SBQxBf

**Comment by FlyingPikachu** [comment] 2018-01-17 23:40
Possible duplicate of #245

**Comment by FlyingPikachu** [comment] 2018-01-18 02:47
@PengBread Hoping to look into this soon. In the meantime, I see your quest has commas after stone and iron_ore, as shown below:

>
      ordered:
        '1':
          break-block-names:
          - stone,
          - iron_ore,
          - gold_ore

Removing those commas might help as they certainly shouldn't be there.

**Comment by PengBread** [comment] 2018-01-18 04:05
Not working, still duplicating.

**Comment by FlyingPikachu** [comment] 2018-01-18 22:44
I was able to replicate this using your quest. Seems to occur when a player quits, but not when the server is stopped. Removing commas from the block names had no noticeable effect.

Continuing to work on this. By the way, I noticed your quest asks "Type Yes to accept, No to deny". Did you know you can set `ask-confirmation:false` in config.yml to disable Yes/No confirmaton?

**Comment by PengBread** [comment] 2018-01-19 07:54
There's no "ask-confirmation:false" in my config.yml

**Comment by FlyingPikachu** [comment] 2018-01-20 05:40
That's... odd. The option was added in Quests 3.2.1 with the default being "true".

No matter, we can look into why that is after the main issue is resolved. Will let you know once progress has been made.

**Comment by FlyingPikachu** [comment] 2018-01-21 07:31
Fix is available in the dev build linked below. Thanks for using Quests!

http://ci.ac3-servers.eu/job/Quests/245/

**Closed** 2018-01-21 07:30 UTC
Labels: bug, duplicate
