### ISSUE TITLE
Conversation tracking errors when attempting to edit events

### ISSUE THREAD

**Issue by Flubberschnub** [FlyingPikachu/Quests#444] opened 2018-08-03 01:22 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
My version is 3.2.5-b264.
(__Required__) Please describe the problem and how to replicate it. Any console errors?
I typed in /quests events, and the event editor menu popped up.  I type 2 to edit an event, then I typed in the name of the event (which was CelHotelShard, if that's important).  Then the plugin stopped responding to my commands, and nothing else popped up on the chat.  I get this error every time I try to type something:

```
[18:17:14 WARN]: [Quests] Plugin Quests v3.2.5-b264 generated an exception whilst handling conversation input
java.lang.NullPointerException: null
	at me.blackvein.quests.util.ItemUtil.getString(ItemUtil.java:192) ~[?:?]
	at me.blackvein.quests.EventFactory$CreateMenuPrompt.getPromptText(EventFactory.java:408) ~[?:?]
	at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:284) ~[spigot.jar:git-Spigot-eb3d921-b9f1615]
	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) ~[spigot.jar:git-Spigot-eb3d921-b9f1615]
	at org.bukkit.craftbukkit.v1_12_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:60) [spigot.jar:git-Spigot-eb3d921-b9f1615]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1118) [spigot.jar:git-Spigot-eb3d921-b9f1615]
	at net.minecraft.server.v1_12_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1246) [spigot.jar:git-Spigot-eb3d921-b9f1615]
	at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) [spigot.jar:git-Spigot-eb3d921-b9f1615]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:758) [spigot.jar:git-Spigot-eb3d921-b9f1615]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-eb3d921-b9f1615]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-eb3d921-b9f1615]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-eb3d921-b9f1615]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```
I am unable to send any chat messages when this occurs, and the only way to stop it is to relog.

**Comment by FlyingPikachu** [comment] 2018-08-03 03:53
This issue is likely fixed in newer builds of Quests. Please update and post back if the issue is not resolved.

**Comment by Flubberschnub** [comment] 2018-08-03 17:43
I've updated it, but the same problem persists.

**Comment by FlyingPikachu** [comment] 2018-08-05 02:48
Would you mind posting the error for the new version, please?

**Comment by Flubberschnub** [comment] 2018-08-08 06:16
Sorry for the delay, here it is:

[23:14:00 WARN]: [Quests] Plugin Quests v3.3.4-b316 generated an exception whilst handling conversation input
java.lang.NullPointerException: null
	at me.blackvein.quests.util.ItemUtil.getString(ItemUtil.java:198) ~[?:?]
	at me.blackvein.quests.EventFactory$CreateMenuPrompt.getPromptText(EventFactory.java:407) ~[?:?]
	at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:284) ~[spigot.jar:git-Spigot-eb3d921-b9f1615]
	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) ~[spigot.jar:git-Spigot-eb3d921-b9f1615]
	at org.bukkit.craftbukkit.v1_12_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:60) [spigot.jar:git-Spigot-eb3d921-b9f1615]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1118) [spigot.jar:git-Spigot-eb3d921-b9f1615]
	at net.minecraft.server.v1_12_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1246) [spigot.jar:git-Spigot-eb3d921-b9f1615]
	at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) [spigot.jar:git-Spigot-eb3d921-b9f1615]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:758) [spigot.jar:git-Spigot-eb3d921-b9f1615]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-eb3d921-b9f1615]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-eb3d921-b9f1615]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-eb3d921-b9f1615]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by FlyingPikachu** [comment] 2018-12-12 06:38
Use http://ci.ac3-servers.eu/job/Quests/554/ once available

**Closed** 2018-12-12 06:37 UTC
Labels: bug
