### ISSUE TITLE
Hello Error with the Effects!

### ISSUE THREAD

**Issue by mig25Zockt** [FlyingPikachu/Quests#540] opened 2018-11-30 09:49 UTC
Hello! Ich habe a Problem with the  Effects on a NPC. 
Error Code: https://hastebin.com/anehulimun.css

**Comment by FlyingPikachu** [comment] 2018-11-30 18:56
Closing as OP did follow issue instructions. Need Quests version

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mig25Zockt** [comment] 2018-11-30 19:44
What you mean?

**Comment by FlyingPikachu** [comment] 2018-11-30 19:52
@mig25Zockt You must tell us your Quests version number, per the instructions.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mig25Zockt** [comment] 2018-11-30 20:29
Oh Okey i have the version: 3.4.3

**Comment by FlyingPikachu** [comment] 2018-12-01 03:31
Duplicate of #516 

Use this dev build once available - http://ci.ac3-servers.eu/job/Quests/515/

**Comment by mig25Zockt** [comment] 2018-12-01 08:38
Hello yet ist this error! Version: 3.4.4
https://hastebin.com/ekamehuqux.cs

**Comment by FlyingPikachu** [comment] 2018-12-01 09:08
Sorry and thanks for your patience. This should do it, once available:
http://ci.ac3-servers.eu/job/Quests/521/

**Closed** 2018-12-01 09:07 UTC
Labels: bug, duplicate
