### ISSUE TITLE
Reset objective

### ISSUE THREAD

**Issue by SwimUp29** [FlyingPikachu/Quests#242] opened 2018-01-12 15:28 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.1 b234
(__Required__) Please describe the problem and how to replicate it. Any console errors?
I apologize for the many topics, it seems to me so it will be easier to solve the gaps.

My players are faced with the fact that sometimes their task is reset.
For example, there is an assignment to bring 64 apples and 32 bread NPCs. The player brought 64 apples, and after some time (it's hard to say when this happens) they again need to bring 64 apples and 32 bread

Sry for my eng

**Comment by FlyingPikachu** [comment] 2018-01-14 00:42
I prefer that you made separate issues, thanks. Please post the quest from quests.yml that your players are having problems with.

**Comment by SwimUp29** [comment] 2018-01-14 09:03
you need my quests.yml?

https://pastebin.com/TPi3cbGt

**Comment by FlyingPikachu** [comment] 2018-01-14 21:19
I'm assuming "Пополнение запасов" is the problem quest based on your example. Will run some tests with this soon.

**Comment by SwimUp29** [comment] 2018-01-15 10:38
Yes. It seems that the stages are reset for those players who are on the server at the time of server restart, but this is not accurate

**Comment by FlyingPikachu** [comment] 2018-01-16 01:01
I was able to confirm that, after delivering 64/64 Apples to the npc, a restart of the server caused this to become 64/32 Cooked Porkchops (according to the Quests Journal). No errors so finding the cause of this may take some time. Marking as a Bug for now.

**Closed** 2018-01-16 08:05 UTC
Labels: bug

**Comment by FlyingPikachu** [comment] 2018-01-16 08:08
Dev build which will contain fix for this issue:

http://ci.ac3-servers.eu/job/Quests/237/
