### ISSUE TITLE
Items-to-deliver issue

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#619] opened 2019-01-06 03:08 UTC
**What is your Quests version / build number (do _not_ say "latest")?**

3.6.0-b595

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

Ink Sack listed instead of Cocoa, and not accepted. Also, it should be "sac" not "sack."

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

```yaml
  Daily Cocoa:
    name: Cocoa for the countrymen (Daily)
    planner:
      start: 30:2:2018:19:0:0:SystemV/EST5
      repeat: 86400
      cooldown: 43200
    npc-giver-id: 25
    ask-message: <darkgreen>We need 5 stacks of coacoa today to feed the people, can
      you help?
    finish-message: <darkgreen>Thank you kindly, your efforts are most appreciated!
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-ink_sack:amount-320:data-3
          npc-delivery-ids:
          - 25
          delivery-messages:
          - Thanks, keep it up!
    rewards:
      money: 50
      quest-points: 1
```

**Comment by FlyingPikachu** [comment] 2019-01-07 03:13
Prior to 1.13, Cocoa Beans were actually a variant of Ink Sack, albeit with a durability of 3. So it's correct! Furthermore, `ink_sac` was actually `ink_sack` prior to 1.13 ([here's proof](https://jd.bukkit.org/org/bukkit/Material.html)).

Try one of the latest dev builds. I pushed a commit recently that will tell the player in-game specifically what's wrong with their item being delivered.

**Comment by SXRWahrheit** [comment] 2019-01-07 12:38
I've got build 595, which I think was the latest at the time of filing. I'll get 599 today.

The naming issue is odd - it's listed as "ink sac" in game.

But it's still listed as an ink sac in the objective name, regardless.

**Comment by FlyingPikachu** [comment] 2019-01-07 16:18
Ah, I think build 590 contained the commit so you should be good. When you deliver the item to an NPC, you should get a second message in chat formatted like:

> The difference is '[reason]'.

With `[reason]` being the name, or item flags, or whatever's different. See #609 for more info.

**Comment by SXRWahrheit** [comment] 2019-01-07 16:19
Sure, but why is the objective listed as ink sac?

**Comment by FlyingPikachu** [comment] 2019-01-07 16:24
Despite what an item is called in-game, it's coded Material value is what matters to Quests. Prior to 1.13, this value often doesn't match up with the name displayed in-game. Another, more obvious example is activated redstone repeaters having been called `diode_block_on` while for 1.13 it was updated to just `repeater`. Use the following links to compare:

Bukkit 1.7.10 materials - https://jd.bukkit.org/org/bukkit/Material.html
Spigot 1.13.2 materials - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by SXRWahrheit** [comment] 2019-01-07 16:36
I understand the differences between materials in 1.13 and materials in 1.12 - but Quests displaying the wrong item-to-deliver to a player should be regarded as a bug. Telling them the durability does not match the expected delivery is not a solution. It should just display "Cocoa" - this can't be that hard to do, can it?

**Comment by SXRWahrheit** [comment] 2019-01-07 16:37
Put more simply - most players are not as well-versed about the inner-workings about Minecraft as server owners, and we shouldn't expect them to be. Quests should parse that material + data value = specific item in 1.12 and below.

**Comment by FlyingPikachu** [comment] 2019-01-07 16:45
That isn't meant to be a solution - just to inform the user _why_ their item isn't being accepted rather than just outright denying it.

As for showing Cocoa Beans instead of Ink Sac(k) in chat - yes, that is hard to do. There's no Bukkit/Spigot methods for getting the name used in-game (as it's actually client-side) so plugins only have access to the Material values. Previously, Quests used VaultAPI to pull from a huge list of in-game names, but that stopped getting updated and the developer recently retired it altogether.

However, you just jogged my memory in that this is a duplicate of #575. In that issue, the user had the same problem as you, albeit he was using a Spanish client. So, the solution for you would be to set `translate-items: true` in config.yml, which should also work for English clients.

**Closed by FlyingPikachu** 2019-01-07 16:45 UTC
