### ISSUE TITLE
Update Quests to fix Vault implementation

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#476] opened 2018-09-20 21:20 UTC
(__Required__) What is your Quests version / build number (do _not_ say "latest")?

3.3.4-b316

(__Required__) Please describe the problem and how to replicate it. Any console errors?

Quests utilizes old Vault APIs and needs to be updated. See also: https://github.com/MilkBowl/Vault/issues/742

```
[16:16:36] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'quest' in plugin Quests v3.3.4-b316
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: net/milkbowl/vault/item/Items
	at me.blackvein.quests.util.ItemUtil.getName(ItemUtil.java:217) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quester.getObjectives(Quester.java:612) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:452) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quests.showObjectives(Quests.java:1847) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quests.questCommandHandler(Quests.java:1682) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quests.onCommand(Quests.java:685) ~[Quests-3.3.4.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	... 15 more
```

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

This paste will expire in 1 week for privacy reasons: https://pastebin.com/FSxsGAjs

**Comment by SXRWahrheit** [comment] 2018-10-16 00:14
It's been over three weeks since this issue was opened - I know you're busy, but this seems important. Do you have a timeline for the update?

**Comment by FlyingPikachu** [comment] 2018-10-17 03:56
Closing as duplicate of #468

@SXRWahrheit I started working on this about a week ago. The Vault API being referenced was used for, among other things, converting a server-usable item Material to client-readable text (such as `Material.INKSACK, 1 ,4` -> "Lapus Lazuli"). Vault 1.6.7 removed the API entirely, and while https://github.com/MilkBowl/Vault/issues/742 implies fixing this is a simple matter of "no longer us[ing] the removed APIs", the fact is, there aren't many good replacements (well, [this API](https://www.spigotmc.org/resources/1-7-x-1-12-language-utils.8859/) comes to mind, but it hasn't been updated for MC 1.13). It became clear that I'd have to come up with my own utility to get proper item names, with enough future-proofing that it won't eventually fail like Vault's implementation. Then there's the matter of #172, which requests item names _also_ be translated to non-English languages. My stubbornness also demands that entity names (Pig, Sheep, etc,) be translated as well.

Easier said than done. First, I had to fix #107, because metadata can determine the name of some items (specifically Potions).  Next, after countless hours of toying around, I've finally managed to come up with a very hack-ish way of converting item Materials and EntityTypes -> text in the client's language using reflection, so that it will be compatible with older versions of Spigot (and, hopefully, future versions). Lastly - and this is the part of just started on - the entire plugin needs to be updated to use my new utility rather than Vault's API. Oh, and once that's done, I'd like to have Quests soft-depend Vault (make it optional), so that users will only need it if they want economy stuff.

So, I wish I could give a timeline for all this, but I'm gonna have to leave it at "soon-ish".

**Closed by FlyingPikachu** 2018-10-17 03:56 UTC

**Comment by SXRWahrheit** [comment] 2018-10-17 14:53
Cool, thanks for the update! Just wanted to check in - not like you to be radio silent.

**Comment by SXRWahrheit** [comment] 2018-10-17 14:54
And great work - that's quite the task!

**Comment by FlyingPikachu** [comment] 2018-10-30 06:58
http://ci.ac3-servers.eu/job/Quests/489/

If desired, one can enable the item/mob/enchant translation by adding `translate-items: true` to one's config.yml. Note the language is determined by the client. Please report bugs in new tickets.
