### ISSUE TITLE
deliver-to npc issue

### ISSUE THREAD

**Issue by ChenyangLin-J** [FlyingPikachu/Quests#33] opened 2017-07-08 06:51 UTC
In your issue, please include:

- Spigot and Quests versions (do not say "latest")
2.7.4,2.7.6,2.8.4,2.8.6,2.8.7 (I test)
- Description of problem & console errors
in my test, I want to give items to npc from citizens, and when I give all of necessary items to the npc but the next stage does not start.
- An example quest from quests.yml for testing, if applicable
 custom3:
    name: 新手任务
    npc-giver-id: 1
    ask-message: 【旅途的开始】新手任务
    finish-message: 恭喜恭喜
    gui-display: name-GOLDEN_APPLE:amount-1
    stages:
      ordered:
        '1':
          npc-ids-to-talk-to:
          - 0
          start-event: 新手任务一
          start-message: 您已成功接受【旅途的开始】新手任务，并收到任务道具12个橡木木板以及8个圆石
          complete-message: 快去找紫色区域的新手向导二吧，他会告诉你接下来的事情的，祝你在这片土地找到你的快乐！
        '2':
          npc-ids-to-talk-to:
          - 1
          complete-message: 向导二：哈哈哈哈，新来的小伙子啊，先让我看看你的基础如何，造一个工作台，箱子和熔炉给我吧！
        '3':
          items-to-deliver:
          - name-WORKBENCH:amount-1
          - name-CHEST:amount-1
          - name-FURNACE:amount-1
          npc-delivery-ids:
          - 1
          - 1
          - 1
          delivery-messages:
          - 成功递交
          complete-message: 哇，这么快就制作好了啊，真不愧的是来到这个猫王世界的玩家呢！快去找蓝色区域的向导三吧！
it is in chinese and it is a little part of the quest.  and when I type /quest it shows the picture below.
<img width="598" alt="2017-07-08 2 48 35" src="https://user-images.githubusercontent.com/29996370/27983350-e849ad64-63ec-11e7-870b-330441a1f9ed.png">

Failure to provide the first 2 bullets may result in your issue being closed!

**Comment by FlyingPikachu** [comment] 2017-07-08 16:11
May be a duplicate of #31

**Comment by FlyingPikachu** [comment] 2017-07-09 03:32
@ChenyangLin-J Most likely fixed in #31. Try this dev build. If that doesn't work, I'll re-open this issue. Thanks!

http://ci.ac3-servers.eu/job/Quests/139/

**Closed by FlyingPikachu** 2017-07-09 03:32 UTC

**Comment by ChenyangLin-J** [comment] 2017-07-09 05:12
ok  i'll try it.

**Comment by ChenyangLin-J** [comment] 2017-07-09 05:48
it is fixed completely, thank you for your help.
But I find a new bug, the step 2 in stage events that is finish event cannot used. Start event is available.
