### ISSUE TITLE
Quests Delete Themselves

### ISSUE THREAD

**Issue by biggestnate** [FlyingPikachu/Quests#2] opened 2017-06-22 18:59 UTC
The issue I've been havinga is this: Quests delete themselves.  At first everything was smooth and I had no problems but then I made a new quest and I needed to edit my quest so I went to /quests editor and I clicked edit a quest and then I typed in the quest I needed to edit but nothing appeared. After restarting the server the quest actually deleted itself. The quest was still in the quests.yml folder but it wasn't appearing in game. I tried making another quest to see if the problem persisted and sure enough it did. I tried reinstalling quests and putting in the yml file but the problem still was there. Then I tried reinstalling quests and making a new quest with a new yml. That quest worked. . I'm going to send the yml file over as a txt file. Please take a look and tell me how to fix this. I think the problem is with the yml, 
[quests.txt](https://github.com/FlyingPikachu/Quests/files/1095868/quests.txt)

**Comment by biggestnate** [comment] 2017-06-22 19:00
The last quest in the file is the one that isnt showing up

**Comment by FlyingPikachu** [comment] 2017-06-23 01:59
Thank you, I will take this into account when investigating the issue. However, this a duplicate of #1 and for that reason, I must close it.

**Closed by FlyingPikachu** 2017-06-23 01:59 UTC

**Comment by biggestnate** [comment] 2017-06-23 04:13
Okay thank you!

**Comment by biggestnate** [comment] 2017-06-23 04:19
Oh this is probably rather important: The quest plugin version i'm using is the one made for 1.10

**Comment by FlyingPikachu** [comment] 2017-06-23 06:29
@biggestnate Version 2.8.6 should resolve this issue. If you still experience issues after updating, you may need to manually add block durability for affected quests. Post your quests.yml if you would like assistance. Thanks!
