### ISSUE TITLE
Timer on Repeatable quests bugged 

### ISSUE THREAD

**Issue by xxahmxx** [FlyingPikachu/Quests#107] opened 2015-05-03 11:49 UTC
Hello, 
We found huge bug in Quests. There is way to bugg repeatable quests. U just need to fast relog on complete quest and then u can make it again without delay

**Comment by FlyingPikachu** [comment] 2015-05-05 13:34
Duplicate of #67. Please contribute there. Thanks!

**Closed by FlyingPikachu** 2015-05-05 13:34 UTC
