### ISSUE TITLE
 translation

### ISSUE THREAD

**Issue by MrKayfer** [FlyingPikachu/Quests#141] opened 2017-10-01 09:48 UTC
What is your Quests version / 3.0.0

I have decided to be engaged in the translation into Russian and I have faced a problem. After the translation everything flies to English. I have read a subject about the translation, and there it is written:
Keep the double quotation marks on the ends of each translation
Don't use double quotation marks in any of your translations or you will likely break them. You can use single quotes however.

And how it is correct to write?
I will take for example a line (original)
enterAnOption: Enter an option
And it is necessary to translate so?
enterAnOption: "Выберите вариант" or enterAnOption: 'Выберите вариант'?

**Comment by FlyingPikachu** [comment] 2017-12-06 02:22
Duplicate of #121

**Closed by FlyingPikachu** 2017-12-06 02:22 UTC
